// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Application summary for list operations
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ApplicationSummary {
    /// Unique identifier of the application
    pub application_id: ::std::string::String,
    /// Name of the application, automatically assigned by the service
    pub application_name: ::std::string::String,
    /// Domain where the application is available
    pub domain: ::std::string::String,
    /// Default KMS key identifier used to encrypt application data
    pub default_kms_key_id: ::std::option::Option<::std::string::String>,
}
impl ApplicationSummary {
    /// Unique identifier of the application
    pub fn application_id(&self) -> &str {
        use std::ops::Deref;
        self.application_id.deref()
    }
    /// Name of the application, automatically assigned by the service
    pub fn application_name(&self) -> &str {
        use std::ops::Deref;
        self.application_name.deref()
    }
    /// Domain where the application is available
    pub fn domain(&self) -> &str {
        use std::ops::Deref;
        self.domain.deref()
    }
    /// Default KMS key identifier used to encrypt application data
    pub fn default_kms_key_id(&self) -> ::std::option::Option<&str> {
        self.default_kms_key_id.as_deref()
    }
}
impl ApplicationSummary {
    /// Creates a new builder-style object to manufacture [`ApplicationSummary`](crate::types::ApplicationSummary).
    pub fn builder() -> crate::types::builders::ApplicationSummaryBuilder {
        crate::types::builders::ApplicationSummaryBuilder::default()
    }
}

/// A builder for [`ApplicationSummary`](crate::types::ApplicationSummary).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ApplicationSummaryBuilder {
    pub(crate) application_id: ::std::option::Option<::std::string::String>,
    pub(crate) application_name: ::std::option::Option<::std::string::String>,
    pub(crate) domain: ::std::option::Option<::std::string::String>,
    pub(crate) default_kms_key_id: ::std::option::Option<::std::string::String>,
}
impl ApplicationSummaryBuilder {
    /// Unique identifier of the application
    /// This field is required.
    pub fn application_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.application_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Unique identifier of the application
    pub fn set_application_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.application_id = input;
        self
    }
    /// Unique identifier of the application
    pub fn get_application_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.application_id
    }
    /// Name of the application, automatically assigned by the service
    /// This field is required.
    pub fn application_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.application_name = ::std::option::Option::Some(input.into());
        self
    }
    /// Name of the application, automatically assigned by the service
    pub fn set_application_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.application_name = input;
        self
    }
    /// Name of the application, automatically assigned by the service
    pub fn get_application_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.application_name
    }
    /// Domain where the application is available
    /// This field is required.
    pub fn domain(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.domain = ::std::option::Option::Some(input.into());
        self
    }
    /// Domain where the application is available
    pub fn set_domain(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.domain = input;
        self
    }
    /// Domain where the application is available
    pub fn get_domain(&self) -> &::std::option::Option<::std::string::String> {
        &self.domain
    }
    /// Default KMS key identifier used to encrypt application data
    pub fn default_kms_key_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.default_kms_key_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Default KMS key identifier used to encrypt application data
    pub fn set_default_kms_key_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.default_kms_key_id = input;
        self
    }
    /// Default KMS key identifier used to encrypt application data
    pub fn get_default_kms_key_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.default_kms_key_id
    }
    /// Consumes the builder and constructs a [`ApplicationSummary`](crate::types::ApplicationSummary).
    /// This method will fail if any of the following fields are not set:
    /// - [`application_id`](crate::types::builders::ApplicationSummaryBuilder::application_id)
    /// - [`application_name`](crate::types::builders::ApplicationSummaryBuilder::application_name)
    /// - [`domain`](crate::types::builders::ApplicationSummaryBuilder::domain)
    pub fn build(self) -> ::std::result::Result<crate::types::ApplicationSummary, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ApplicationSummary {
            application_id: self.application_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "application_id",
                    "application_id was not specified but it is required when building ApplicationSummary",
                )
            })?,
            application_name: self.application_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "application_name",
                    "application_name was not specified but it is required when building ApplicationSummary",
                )
            })?,
            domain: self.domain.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "domain",
                    "domain was not specified but it is required when building ApplicationSummary",
                )
            })?,
            default_kms_key_id: self.default_kms_key_id,
        })
    }
}
