// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Collection of assets to be tested or used during a pentest
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct Assets {
    /// List of web application endpoints to test
    pub endpoints: ::std::option::Option<::std::vec::Vec<crate::types::Endpoint>>,
    /// List of actors that interact with the system
    pub actors: ::std::option::Option<::std::vec::Vec<crate::types::Actor>>,
    /// List of documents providing context for testing
    pub documents: ::std::option::Option<::std::vec::Vec<crate::types::DocumentInfo>>,
    /// List of source code repositories for static analysis
    pub source_code: ::std::option::Option<::std::vec::Vec<crate::types::SourceCodeRepository>>,
    /// List of integrated code repositories
    pub integrated_repositories: ::std::option::Option<::std::vec::Vec<crate::types::IntegratedRepository>>,
}
impl Assets {
    /// List of web application endpoints to test
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.endpoints.is_none()`.
    pub fn endpoints(&self) -> &[crate::types::Endpoint] {
        self.endpoints.as_deref().unwrap_or_default()
    }
    /// List of actors that interact with the system
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.actors.is_none()`.
    pub fn actors(&self) -> &[crate::types::Actor] {
        self.actors.as_deref().unwrap_or_default()
    }
    /// List of documents providing context for testing
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.documents.is_none()`.
    pub fn documents(&self) -> &[crate::types::DocumentInfo] {
        self.documents.as_deref().unwrap_or_default()
    }
    /// List of source code repositories for static analysis
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.source_code.is_none()`.
    pub fn source_code(&self) -> &[crate::types::SourceCodeRepository] {
        self.source_code.as_deref().unwrap_or_default()
    }
    /// List of integrated code repositories
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.integrated_repositories.is_none()`.
    pub fn integrated_repositories(&self) -> &[crate::types::IntegratedRepository] {
        self.integrated_repositories.as_deref().unwrap_or_default()
    }
}
impl Assets {
    /// Creates a new builder-style object to manufacture [`Assets`](crate::types::Assets).
    pub fn builder() -> crate::types::builders::AssetsBuilder {
        crate::types::builders::AssetsBuilder::default()
    }
}

/// A builder for [`Assets`](crate::types::Assets).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AssetsBuilder {
    pub(crate) endpoints: ::std::option::Option<::std::vec::Vec<crate::types::Endpoint>>,
    pub(crate) actors: ::std::option::Option<::std::vec::Vec<crate::types::Actor>>,
    pub(crate) documents: ::std::option::Option<::std::vec::Vec<crate::types::DocumentInfo>>,
    pub(crate) source_code: ::std::option::Option<::std::vec::Vec<crate::types::SourceCodeRepository>>,
    pub(crate) integrated_repositories: ::std::option::Option<::std::vec::Vec<crate::types::IntegratedRepository>>,
}
impl AssetsBuilder {
    /// Appends an item to `endpoints`.
    ///
    /// To override the contents of this collection use [`set_endpoints`](Self::set_endpoints).
    ///
    /// List of web application endpoints to test
    pub fn endpoints(mut self, input: crate::types::Endpoint) -> Self {
        let mut v = self.endpoints.unwrap_or_default();
        v.push(input);
        self.endpoints = ::std::option::Option::Some(v);
        self
    }
    /// List of web application endpoints to test
    pub fn set_endpoints(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Endpoint>>) -> Self {
        self.endpoints = input;
        self
    }
    /// List of web application endpoints to test
    pub fn get_endpoints(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Endpoint>> {
        &self.endpoints
    }
    /// Appends an item to `actors`.
    ///
    /// To override the contents of this collection use [`set_actors`](Self::set_actors).
    ///
    /// List of actors that interact with the system
    pub fn actors(mut self, input: crate::types::Actor) -> Self {
        let mut v = self.actors.unwrap_or_default();
        v.push(input);
        self.actors = ::std::option::Option::Some(v);
        self
    }
    /// List of actors that interact with the system
    pub fn set_actors(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Actor>>) -> Self {
        self.actors = input;
        self
    }
    /// List of actors that interact with the system
    pub fn get_actors(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Actor>> {
        &self.actors
    }
    /// Appends an item to `documents`.
    ///
    /// To override the contents of this collection use [`set_documents`](Self::set_documents).
    ///
    /// List of documents providing context for testing
    pub fn documents(mut self, input: crate::types::DocumentInfo) -> Self {
        let mut v = self.documents.unwrap_or_default();
        v.push(input);
        self.documents = ::std::option::Option::Some(v);
        self
    }
    /// List of documents providing context for testing
    pub fn set_documents(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::DocumentInfo>>) -> Self {
        self.documents = input;
        self
    }
    /// List of documents providing context for testing
    pub fn get_documents(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::DocumentInfo>> {
        &self.documents
    }
    /// Appends an item to `source_code`.
    ///
    /// To override the contents of this collection use [`set_source_code`](Self::set_source_code).
    ///
    /// List of source code repositories for static analysis
    pub fn source_code(mut self, input: crate::types::SourceCodeRepository) -> Self {
        let mut v = self.source_code.unwrap_or_default();
        v.push(input);
        self.source_code = ::std::option::Option::Some(v);
        self
    }
    /// List of source code repositories for static analysis
    pub fn set_source_code(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::SourceCodeRepository>>) -> Self {
        self.source_code = input;
        self
    }
    /// List of source code repositories for static analysis
    pub fn get_source_code(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::SourceCodeRepository>> {
        &self.source_code
    }
    /// Appends an item to `integrated_repositories`.
    ///
    /// To override the contents of this collection use [`set_integrated_repositories`](Self::set_integrated_repositories).
    ///
    /// List of integrated code repositories
    pub fn integrated_repositories(mut self, input: crate::types::IntegratedRepository) -> Self {
        let mut v = self.integrated_repositories.unwrap_or_default();
        v.push(input);
        self.integrated_repositories = ::std::option::Option::Some(v);
        self
    }
    /// List of integrated code repositories
    pub fn set_integrated_repositories(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::IntegratedRepository>>) -> Self {
        self.integrated_repositories = input;
        self
    }
    /// List of integrated code repositories
    pub fn get_integrated_repositories(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::IntegratedRepository>> {
        &self.integrated_repositories
    }
    /// Consumes the builder and constructs a [`Assets`](crate::types::Assets).
    pub fn build(self) -> crate::types::Assets {
        crate::types::Assets {
            endpoints: self.endpoints,
            actors: self.actors,
            documents: self.documents,
            source_code: self.source_code,
            integrated_repositories: self.integrated_repositories,
        }
    }
}
