// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Error information regarding the pentest job
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ErrorInformation {
    /// Pentest job failure error code
    pub code: ::std::option::Option<crate::types::ErrorCode>,
    /// Pentest job failure error message
    pub message: ::std::option::Option<::std::string::String>,
}
impl ErrorInformation {
    /// Pentest job failure error code
    pub fn code(&self) -> ::std::option::Option<&crate::types::ErrorCode> {
        self.code.as_ref()
    }
    /// Pentest job failure error message
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }
}
impl ErrorInformation {
    /// Creates a new builder-style object to manufacture [`ErrorInformation`](crate::types::ErrorInformation).
    pub fn builder() -> crate::types::builders::ErrorInformationBuilder {
        crate::types::builders::ErrorInformationBuilder::default()
    }
}

/// A builder for [`ErrorInformation`](crate::types::ErrorInformation).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ErrorInformationBuilder {
    pub(crate) code: ::std::option::Option<crate::types::ErrorCode>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
}
impl ErrorInformationBuilder {
    /// Pentest job failure error code
    pub fn code(mut self, input: crate::types::ErrorCode) -> Self {
        self.code = ::std::option::Option::Some(input);
        self
    }
    /// Pentest job failure error code
    pub fn set_code(mut self, input: ::std::option::Option<crate::types::ErrorCode>) -> Self {
        self.code = input;
        self
    }
    /// Pentest job failure error code
    pub fn get_code(&self) -> &::std::option::Option<crate::types::ErrorCode> {
        &self.code
    }
    /// Pentest job failure error message
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    /// Pentest job failure error message
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    /// Pentest job failure error message
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Consumes the builder and constructs a [`ErrorInformation`](crate::types::ErrorInformation).
    pub fn build(self) -> crate::types::ErrorInformation {
        crate::types::ErrorInformation {
            code: self.code,
            message: self.message,
        }
    }
}
