// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Location information for execution logs
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct LogLocation {
    /// Type of log storage
    pub log_type: ::std::option::Option<crate::types::LogType>,
    /// CloudWatch log information if logs are stored in CloudWatch
    pub cloud_watch_log: ::std::option::Option<crate::types::CloudWatchLog>,
}
impl LogLocation {
    /// Type of log storage
    pub fn log_type(&self) -> ::std::option::Option<&crate::types::LogType> {
        self.log_type.as_ref()
    }
    /// CloudWatch log information if logs are stored in CloudWatch
    pub fn cloud_watch_log(&self) -> ::std::option::Option<&crate::types::CloudWatchLog> {
        self.cloud_watch_log.as_ref()
    }
}
impl LogLocation {
    /// Creates a new builder-style object to manufacture [`LogLocation`](crate::types::LogLocation).
    pub fn builder() -> crate::types::builders::LogLocationBuilder {
        crate::types::builders::LogLocationBuilder::default()
    }
}

/// A builder for [`LogLocation`](crate::types::LogLocation).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct LogLocationBuilder {
    pub(crate) log_type: ::std::option::Option<crate::types::LogType>,
    pub(crate) cloud_watch_log: ::std::option::Option<crate::types::CloudWatchLog>,
}
impl LogLocationBuilder {
    /// Type of log storage
    pub fn log_type(mut self, input: crate::types::LogType) -> Self {
        self.log_type = ::std::option::Option::Some(input);
        self
    }
    /// Type of log storage
    pub fn set_log_type(mut self, input: ::std::option::Option<crate::types::LogType>) -> Self {
        self.log_type = input;
        self
    }
    /// Type of log storage
    pub fn get_log_type(&self) -> &::std::option::Option<crate::types::LogType> {
        &self.log_type
    }
    /// CloudWatch log information if logs are stored in CloudWatch
    pub fn cloud_watch_log(mut self, input: crate::types::CloudWatchLog) -> Self {
        self.cloud_watch_log = ::std::option::Option::Some(input);
        self
    }
    /// CloudWatch log information if logs are stored in CloudWatch
    pub fn set_cloud_watch_log(mut self, input: ::std::option::Option<crate::types::CloudWatchLog>) -> Self {
        self.cloud_watch_log = input;
        self
    }
    /// CloudWatch log information if logs are stored in CloudWatch
    pub fn get_cloud_watch_log(&self) -> &::std::option::Option<crate::types::CloudWatchLog> {
        &self.cloud_watch_log
    }
    /// Consumes the builder and constructs a [`LogLocation`](crate::types::LogLocation).
    pub fn build(self) -> crate::types::LogLocation {
        crate::types::LogLocation {
            log_type: self.log_type,
            cloud_watch_log: self.cloud_watch_log,
        }
    }
}
