// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// User membership configuration
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UserConfig {
    /// Role of the user associated to the agent space
    pub role: ::std::option::Option<crate::types::UserRole>,
}
impl UserConfig {
    /// Role of the user associated to the agent space
    pub fn role(&self) -> ::std::option::Option<&crate::types::UserRole> {
        self.role.as_ref()
    }
}
impl UserConfig {
    /// Creates a new builder-style object to manufacture [`UserConfig`](crate::types::UserConfig).
    pub fn builder() -> crate::types::builders::UserConfigBuilder {
        crate::types::builders::UserConfigBuilder::default()
    }
}

/// A builder for [`UserConfig`](crate::types::UserConfig).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UserConfigBuilder {
    pub(crate) role: ::std::option::Option<crate::types::UserRole>,
}
impl UserConfigBuilder {
    /// Role of the user associated to the agent space
    pub fn role(mut self, input: crate::types::UserRole) -> Self {
        self.role = ::std::option::Option::Some(input);
        self
    }
    /// Role of the user associated to the agent space
    pub fn set_role(mut self, input: ::std::option::Option<crate::types::UserRole>) -> Self {
        self.role = input;
        self
    }
    /// Role of the user associated to the agent space
    pub fn get_role(&self) -> &::std::option::Option<crate::types::UserRole> {
        &self.role
    }
    /// Consumes the builder and constructs a [`UserConfig`](crate::types::UserConfig).
    pub fn build(self) -> crate::types::UserConfig {
        crate::types::UserConfig { role: self.role }
    }
}
