// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`SendMessage`](crate::operation::send_message::builders::SendMessageFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`agent_space_id(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::agent_space_id) / [`set_agent_space_id(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_agent_space_id):<br>required: **true**<br>The agent space identifier<br>
    ///   - [`execution_id(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::execution_id) / [`set_execution_id(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_execution_id):<br>required: **true**<br>The execution identifier for the chat session<br>
    ///   - [`content(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::content) / [`set_content(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_content):<br>required: **true**<br>The user message content<br>
    ///   - [`context(SendMessageContext)`](crate::operation::send_message::builders::SendMessageFluentBuilder::context) / [`set_context(Option<SendMessageContext>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_context):<br>required: **false**<br>Optional context for the message<br>
    ///   - [`user_id(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::user_id) / [`set_user_id(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_user_id):<br>required: **true**<br>Required user identifier<br>
    /// - On success, responds with [`SendMessageOutput`](crate::operation::send_message::SendMessageOutput) with field(s):
    ///   - [`events(EventReceiver<SendMessageEvents, SendMessageEventsError>)`](crate::operation::send_message::SendMessageOutput::events): The stream of chat message events
    /// - On failure, responds with [`SdkError<SendMessageError>`](crate::operation::send_message::SendMessageError)
    pub fn send_message(&self) -> crate::operation::send_message::builders::SendMessageFluentBuilder {
        crate::operation::send_message::builders::SendMessageFluentBuilder::new(self.handle.clone())
    }
}
