// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateBacklogTask`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`agent_space_id(impl Into<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::agent_space_id) / [`set_agent_space_id(Option<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::set_agent_space_id):<br>required: **true**<br>The unique identifier for the agent space containing the task<br>
    ///   - [`task_id(impl Into<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::task_id) / [`set_task_id(Option<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::set_task_id):<br>required: **true**<br>The unique identifier of the task to update<br>
    ///   - [`task_status(TaskStatus)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::task_status) / [`set_task_status(Option<TaskStatus>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::set_task_status):<br>required: **false**<br>Updated task status<br>
    ///   - [`client_token(impl Into<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::set_client_token):<br>required: **false**<br>Client-provided token for idempotent operations<br>
    /// - On success, responds with [`UpdateBacklogTaskOutput`](crate::operation::update_backlog_task::UpdateBacklogTaskOutput) with field(s):
    ///   - [`task(Option<Task>)`](crate::operation::update_backlog_task::UpdateBacklogTaskOutput::task): The updated task object
    /// - On failure, responds with [`SdkError<UpdateBacklogTaskError>`](crate::operation::update_backlog_task::UpdateBacklogTaskError)
    pub fn update_backlog_task(&self) -> crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder {
        crate::operation::update_backlog_task::builders::UpdateBacklogTaskFluentBuilder::new(self.handle.clone())
    }
}
