// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Inbound event stream for sending input and control events to manage bidirectional speech synthesis.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum StartSpeechSynthesisStreamActionStream {
    /// <p>An event indicating the end of the input stream.</p>
    CloseStreamEvent(crate::types::CloseStreamEvent),
    /// <p>A text event containing content to be synthesized.</p>
    TextEvent(crate::types::TextEvent),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl StartSpeechSynthesisStreamActionStream {
    /// Tries to convert the enum instance into [`CloseStreamEvent`](crate::types::StartSpeechSynthesisStreamActionStream::CloseStreamEvent), extracting the inner [`CloseStreamEvent`](crate::types::CloseStreamEvent).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_close_stream_event(&self) -> ::std::result::Result<&crate::types::CloseStreamEvent, &Self> {
        if let StartSpeechSynthesisStreamActionStream::CloseStreamEvent(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`CloseStreamEvent`](crate::types::StartSpeechSynthesisStreamActionStream::CloseStreamEvent).
    pub fn is_close_stream_event(&self) -> bool {
        self.as_close_stream_event().is_ok()
    }
    /// Tries to convert the enum instance into [`TextEvent`](crate::types::StartSpeechSynthesisStreamActionStream::TextEvent), extracting the inner [`TextEvent`](crate::types::TextEvent).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_text_event(&self) -> ::std::result::Result<&crate::types::TextEvent, &Self> {
        if let StartSpeechSynthesisStreamActionStream::TextEvent(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`TextEvent`](crate::types::StartSpeechSynthesisStreamActionStream::TextEvent).
    pub fn is_text_event(&self) -> bool {
        self.as_text_event().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
