// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_registry_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::create_registry::CreateRegistryInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.approval_configuration {
        #[allow(unused_mut)]
        let mut object_2 = object.key("approvalConfiguration").start_object();
        crate::protocol_serde::shape_approval_configuration::ser_approval_configuration(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.authorizer_configuration {
        #[allow(unused_mut)]
        let mut object_4 = object.key("authorizerConfiguration").start_object();
        crate::protocol_serde::shape_authorizer_configuration::ser_authorizer_configuration(&mut object_4, var_3)?;
        object_4.finish();
    }
    if let Some(var_5) = &input.authorizer_type {
        object.key("authorizerType").string(var_5.as_str());
    }
    if let Some(var_6) = &input.client_token {
        object.key("clientToken").string(var_6.as_str());
    }
    if let Some(var_7) = &input.description {
        object.key("description").string(var_7.as_str());
    }
    if let Some(var_8) = &input.name {
        object.key("name").string(var_8.as_str());
    }
    Ok(())
}
