// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// All possible error types for this service.
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub enum Error {
    /// <p>You don't have sufficient access to perform this action.</p>
    AccessDeniedException(crate::types::error::AccessDeniedException),
    /// <p>Unexpected error during processing of the request.</p>
    InternalServerException(crate::types::error::InternalServerException),
    /// <p>The specified resource doesn't exist.</p>
    ResourceNotFoundException(crate::types::error::ResourceNotFoundException),
    /// <p>The request was denied due to request throttling.</p>
    ThrottlingException(crate::types::error::ThrottlingException),
    /// <p>The input fails to satisfy the constraints specified by the service.</p>
    ValidationException(crate::types::error::ValidationException),
    /// An unexpected error occurred (e.g., invalid JSON returned by the service or an unknown error code).
    #[deprecated(note = "Matching `Unhandled` directly is not forwards compatible. Instead, match using a \
    variable wildcard pattern and check `.code()`:
     \
    &nbsp;&nbsp;&nbsp;`err if err.code() == Some(\"SpecificExceptionCode\") => { /* handle the error */ }`
     \
    See [`ProvideErrorMetadata`](#impl-ProvideErrorMetadata-for-Error) for what information is available for the error.")]
    Unhandled(crate::error::sealed_unhandled::Unhandled),
}
impl ::std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::AccessDeniedException(inner) => inner.fmt(f),
            Error::InternalServerException(inner) => inner.fmt(f),
            Error::ResourceNotFoundException(inner) => inner.fmt(f),
            Error::ThrottlingException(inner) => inner.fmt(f),
            Error::ValidationException(inner) => inner.fmt(f),
            Error::Unhandled(_) => {
                if let ::std::option::Option::Some(code) = ::aws_smithy_types::error::metadata::ProvideErrorMetadata::code(self) {
                    write!(f, "unhandled error ({code})")
                } else {
                    f.write_str("unhandled error")
                }
            }
        }
    }
}
impl From<::aws_smithy_types::error::operation::BuildError> for Error {
    fn from(value: ::aws_smithy_types::error::operation::BuildError) -> Self {
        Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source: value.into(),
            meta: ::std::default::Default::default(),
        })
    }
}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for Error {
    fn meta(&self) -> &::aws_smithy_types::error::metadata::ErrorMetadata {
        match self {
            Self::AccessDeniedException(inner) => inner.meta(),
            Self::InternalServerException(inner) => inner.meta(),
            Self::ResourceNotFoundException(inner) => inner.meta(),
            Self::ThrottlingException(inner) => inner.meta(),
            Self::ValidationException(inner) => inner.meta(),
            Self::Unhandled(inner) => &inner.meta,
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_listing::GetListingError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_listing::GetListingError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::get_listing::GetListingError> for Error {
    fn from(err: crate::operation::get_listing::GetListingError) -> Self {
        match err {
            crate::operation::get_listing::GetListingError::ResourceNotFoundException(inner) => Error::ResourceNotFoundException(inner),
            crate::operation::get_listing::GetListingError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::get_listing::GetListingError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::get_listing::GetListingError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::get_listing::GetListingError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::get_listing::GetListingError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer::GetOfferError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer::GetOfferError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::get_offer::GetOfferError> for Error {
    fn from(err: crate::operation::get_offer::GetOfferError) -> Self {
        match err {
            crate::operation::get_offer::GetOfferError::ResourceNotFoundException(inner) => Error::ResourceNotFoundException(inner),
            crate::operation::get_offer::GetOfferError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::get_offer::GetOfferError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::get_offer::GetOfferError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::get_offer::GetOfferError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::get_offer::GetOfferError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer_set::GetOfferSetError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer_set::GetOfferSetError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::get_offer_set::GetOfferSetError> for Error {
    fn from(err: crate::operation::get_offer_set::GetOfferSetError) -> Self {
        match err {
            crate::operation::get_offer_set::GetOfferSetError::ResourceNotFoundException(inner) => Error::ResourceNotFoundException(inner),
            crate::operation::get_offer_set::GetOfferSetError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::get_offer_set::GetOfferSetError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::get_offer_set::GetOfferSetError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::get_offer_set::GetOfferSetError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::get_offer_set::GetOfferSetError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer_terms::GetOfferTermsError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_offer_terms::GetOfferTermsError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::get_offer_terms::GetOfferTermsError> for Error {
    fn from(err: crate::operation::get_offer_terms::GetOfferTermsError) -> Self {
        match err {
            crate::operation::get_offer_terms::GetOfferTermsError::ResourceNotFoundException(inner) => Error::ResourceNotFoundException(inner),
            crate::operation::get_offer_terms::GetOfferTermsError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::get_offer_terms::GetOfferTermsError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::get_offer_terms::GetOfferTermsError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::get_offer_terms::GetOfferTermsError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::get_offer_terms::GetOfferTermsError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_product::GetProductError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::get_product::GetProductError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::get_product::GetProductError> for Error {
    fn from(err: crate::operation::get_product::GetProductError) -> Self {
        match err {
            crate::operation::get_product::GetProductError::ResourceNotFoundException(inner) => Error::ResourceNotFoundException(inner),
            crate::operation::get_product::GetProductError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::get_product::GetProductError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::get_product::GetProductError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::get_product::GetProductError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::get_product::GetProductError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_fulfillment_options::ListFulfillmentOptionsError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(
        err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_fulfillment_options::ListFulfillmentOptionsError, R>,
    ) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::list_fulfillment_options::ListFulfillmentOptionsError> for Error {
    fn from(err: crate::operation::list_fulfillment_options::ListFulfillmentOptionsError) -> Self {
        match err {
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::ResourceNotFoundException(inner) => {
                Error::ResourceNotFoundException(inner)
            }
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::AccessDeniedException(inner) => {
                Error::AccessDeniedException(inner)
            }
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::InternalServerException(inner) => {
                Error::InternalServerException(inner)
            }
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::list_fulfillment_options::ListFulfillmentOptionsError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_purchase_options::ListPurchaseOptionsError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_purchase_options::ListPurchaseOptionsError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::list_purchase_options::ListPurchaseOptionsError> for Error {
    fn from(err: crate::operation::list_purchase_options::ListPurchaseOptionsError) -> Self {
        match err {
            crate::operation::list_purchase_options::ListPurchaseOptionsError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::list_purchase_options::ListPurchaseOptionsError::InternalServerException(inner) => {
                Error::InternalServerException(inner)
            }
            crate::operation::list_purchase_options::ListPurchaseOptionsError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::list_purchase_options::ListPurchaseOptionsError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::list_purchase_options::ListPurchaseOptionsError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::search_facets::SearchFacetsError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::search_facets::SearchFacetsError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::search_facets::SearchFacetsError> for Error {
    fn from(err: crate::operation::search_facets::SearchFacetsError) -> Self {
        match err {
            crate::operation::search_facets::SearchFacetsError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::search_facets::SearchFacetsError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::search_facets::SearchFacetsError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::search_facets::SearchFacetsError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::search_facets::SearchFacetsError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl<R> From<::aws_smithy_runtime_api::client::result::SdkError<crate::operation::search_listings::SearchListingsError, R>> for Error
where
    R: Send + Sync + std::fmt::Debug + 'static,
{
    fn from(err: ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::search_listings::SearchListingsError, R>) -> Self {
        match err {
            ::aws_smithy_runtime_api::client::result::SdkError::ServiceError(context) => Self::from(context.into_err()),
            _ => Error::Unhandled(crate::error::sealed_unhandled::Unhandled {
                meta: ::aws_smithy_types::error::metadata::ProvideErrorMetadata::meta(&err).clone(),
                source: err.into(),
            }),
        }
    }
}
impl From<crate::operation::search_listings::SearchListingsError> for Error {
    fn from(err: crate::operation::search_listings::SearchListingsError) -> Self {
        match err {
            crate::operation::search_listings::SearchListingsError::AccessDeniedException(inner) => Error::AccessDeniedException(inner),
            crate::operation::search_listings::SearchListingsError::InternalServerException(inner) => Error::InternalServerException(inner),
            crate::operation::search_listings::SearchListingsError::ThrottlingException(inner) => Error::ThrottlingException(inner),
            crate::operation::search_listings::SearchListingsError::ValidationException(inner) => Error::ValidationException(inner),
            crate::operation::search_listings::SearchListingsError::Unhandled(inner) => Error::Unhandled(inner),
        }
    }
}
impl ::std::error::Error for Error {
    fn source(&self) -> std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match self {
            Error::AccessDeniedException(inner) => inner.source(),
            Error::InternalServerException(inner) => inner.source(),
            Error::ResourceNotFoundException(inner) => inner.source(),
            Error::ThrottlingException(inner) => inner.source(),
            Error::ValidationException(inner) => inner.source(),
            Error::Unhandled(inner) => ::std::option::Option::Some(&*inner.source),
        }
    }
}
impl ::aws_types::request_id::RequestId for Error {
    fn request_id(&self) -> Option<&str> {
        match self {
            Self::AccessDeniedException(e) => e.request_id(),
            Self::InternalServerException(e) => e.request_id(),
            Self::ResourceNotFoundException(e) => e.request_id(),
            Self::ThrottlingException(e) => e.request_id(),
            Self::ValidationException(e) => e.request_id(),
            Self::Unhandled(e) => e.meta.request_id(),
        }
    }
}
