// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains the parameters used to create a policy preview job.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PolicyPreviewJobParameters {
    /// <p>The start of the CloudTrail event analysis window.</p>
    pub start_time: ::aws_smithy_types::DateTime,
    /// <p>The end of the CloudTrail event analysis window.</p>
    pub end_time: ::aws_smithy_types::DateTime,
    /// <p>The list of policy configurations that were analyzed.</p>
    pub policy_configurations: ::std::vec::Vec<crate::types::PolicyConfiguration>,
}
impl PolicyPreviewJobParameters {
    /// <p>The start of the CloudTrail event analysis window.</p>
    pub fn start_time(&self) -> &::aws_smithy_types::DateTime {
        &self.start_time
    }
    /// <p>The end of the CloudTrail event analysis window.</p>
    pub fn end_time(&self) -> &::aws_smithy_types::DateTime {
        &self.end_time
    }
    /// <p>The list of policy configurations that were analyzed.</p>
    pub fn policy_configurations(&self) -> &[crate::types::PolicyConfiguration] {
        use std::ops::Deref;
        self.policy_configurations.deref()
    }
}
impl PolicyPreviewJobParameters {
    /// Creates a new builder-style object to manufacture [`PolicyPreviewJobParameters`](crate::types::PolicyPreviewJobParameters).
    pub fn builder() -> crate::types::builders::PolicyPreviewJobParametersBuilder {
        crate::types::builders::PolicyPreviewJobParametersBuilder::default()
    }
}

/// A builder for [`PolicyPreviewJobParameters`](crate::types::PolicyPreviewJobParameters).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct PolicyPreviewJobParametersBuilder {
    pub(crate) start_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) end_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) policy_configurations: ::std::option::Option<::std::vec::Vec<crate::types::PolicyConfiguration>>,
}
impl PolicyPreviewJobParametersBuilder {
    /// <p>The start of the CloudTrail event analysis window.</p>
    /// This field is required.
    pub fn start_time(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.start_time = ::std::option::Option::Some(input);
        self
    }
    /// <p>The start of the CloudTrail event analysis window.</p>
    pub fn set_start_time(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.start_time = input;
        self
    }
    /// <p>The start of the CloudTrail event analysis window.</p>
    pub fn get_start_time(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.start_time
    }
    /// <p>The end of the CloudTrail event analysis window.</p>
    /// This field is required.
    pub fn end_time(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.end_time = ::std::option::Option::Some(input);
        self
    }
    /// <p>The end of the CloudTrail event analysis window.</p>
    pub fn set_end_time(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.end_time = input;
        self
    }
    /// <p>The end of the CloudTrail event analysis window.</p>
    pub fn get_end_time(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.end_time
    }
    /// Appends an item to `policy_configurations`.
    ///
    /// To override the contents of this collection use [`set_policy_configurations`](Self::set_policy_configurations).
    ///
    /// <p>The list of policy configurations that were analyzed.</p>
    pub fn policy_configurations(mut self, input: crate::types::PolicyConfiguration) -> Self {
        let mut v = self.policy_configurations.unwrap_or_default();
        v.push(input);
        self.policy_configurations = ::std::option::Option::Some(v);
        self
    }
    /// <p>The list of policy configurations that were analyzed.</p>
    pub fn set_policy_configurations(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::PolicyConfiguration>>) -> Self {
        self.policy_configurations = input;
        self
    }
    /// <p>The list of policy configurations that were analyzed.</p>
    pub fn get_policy_configurations(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::PolicyConfiguration>> {
        &self.policy_configurations
    }
    /// Consumes the builder and constructs a [`PolicyPreviewJobParameters`](crate::types::PolicyPreviewJobParameters).
    /// This method will fail if any of the following fields are not set:
    /// - [`start_time`](crate::types::builders::PolicyPreviewJobParametersBuilder::start_time)
    /// - [`end_time`](crate::types::builders::PolicyPreviewJobParametersBuilder::end_time)
    /// - [`policy_configurations`](crate::types::builders::PolicyPreviewJobParametersBuilder::policy_configurations)
    pub fn build(self) -> ::std::result::Result<crate::types::PolicyPreviewJobParameters, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::PolicyPreviewJobParameters {
            start_time: self.start_time.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "start_time",
                    "start_time was not specified but it is required when building PolicyPreviewJobParameters",
                )
            })?,
            end_time: self.end_time.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "end_time",
                    "end_time was not specified but it is required when building PolicyPreviewJobParameters",
                )
            })?,
            policy_configurations: self.policy_configurations.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "policy_configurations",
                    "policy_configurations was not specified but it is required when building PolicyPreviewJobParameters",
                )
            })?,
        })
    }
}
