// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The error details for a session action that could not be retrieved in a batch get operation.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct BatchGetSessionActionError {
    /// <p>The farm ID of the session action that could not be retrieved.</p>
    pub farm_id: ::std::string::String,
    /// <p>The queue ID of the session action that could not be retrieved.</p>
    pub queue_id: ::std::string::String,
    /// <p>The job ID of the session action that could not be retrieved.</p>
    pub job_id: ::std::string::String,
    /// <p>The session action ID of the session action that could not be retrieved.</p>
    pub session_action_id: ::std::string::String,
    /// <p>The error code.</p>
    pub code: crate::types::BatchGetSessionActionErrorCode,
    /// <p>The error message.</p>
    pub message: ::std::string::String,
}
impl BatchGetSessionActionError {
    /// <p>The farm ID of the session action that could not be retrieved.</p>
    pub fn farm_id(&self) -> &str {
        use std::ops::Deref;
        self.farm_id.deref()
    }
    /// <p>The queue ID of the session action that could not be retrieved.</p>
    pub fn queue_id(&self) -> &str {
        use std::ops::Deref;
        self.queue_id.deref()
    }
    /// <p>The job ID of the session action that could not be retrieved.</p>
    pub fn job_id(&self) -> &str {
        use std::ops::Deref;
        self.job_id.deref()
    }
    /// <p>The session action ID of the session action that could not be retrieved.</p>
    pub fn session_action_id(&self) -> &str {
        use std::ops::Deref;
        self.session_action_id.deref()
    }
    /// <p>The error code.</p>
    pub fn code(&self) -> &crate::types::BatchGetSessionActionErrorCode {
        &self.code
    }
    /// <p>The error message.</p>
    pub fn message(&self) -> &str {
        use std::ops::Deref;
        self.message.deref()
    }
}
impl BatchGetSessionActionError {
    /// Creates a new builder-style object to manufacture [`BatchGetSessionActionError`](crate::types::BatchGetSessionActionError).
    pub fn builder() -> crate::types::builders::BatchGetSessionActionErrorBuilder {
        crate::types::builders::BatchGetSessionActionErrorBuilder::default()
    }
}

/// A builder for [`BatchGetSessionActionError`](crate::types::BatchGetSessionActionError).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct BatchGetSessionActionErrorBuilder {
    pub(crate) farm_id: ::std::option::Option<::std::string::String>,
    pub(crate) queue_id: ::std::option::Option<::std::string::String>,
    pub(crate) job_id: ::std::option::Option<::std::string::String>,
    pub(crate) session_action_id: ::std::option::Option<::std::string::String>,
    pub(crate) code: ::std::option::Option<crate::types::BatchGetSessionActionErrorCode>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
}
impl BatchGetSessionActionErrorBuilder {
    /// <p>The farm ID of the session action that could not be retrieved.</p>
    /// This field is required.
    pub fn farm_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.farm_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The farm ID of the session action that could not be retrieved.</p>
    pub fn set_farm_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.farm_id = input;
        self
    }
    /// <p>The farm ID of the session action that could not be retrieved.</p>
    pub fn get_farm_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.farm_id
    }
    /// <p>The queue ID of the session action that could not be retrieved.</p>
    /// This field is required.
    pub fn queue_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.queue_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The queue ID of the session action that could not be retrieved.</p>
    pub fn set_queue_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.queue_id = input;
        self
    }
    /// <p>The queue ID of the session action that could not be retrieved.</p>
    pub fn get_queue_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.queue_id
    }
    /// <p>The job ID of the session action that could not be retrieved.</p>
    /// This field is required.
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.job_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The job ID of the session action that could not be retrieved.</p>
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.job_id = input;
        self
    }
    /// <p>The job ID of the session action that could not be retrieved.</p>
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.job_id
    }
    /// <p>The session action ID of the session action that could not be retrieved.</p>
    /// This field is required.
    pub fn session_action_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.session_action_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The session action ID of the session action that could not be retrieved.</p>
    pub fn set_session_action_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.session_action_id = input;
        self
    }
    /// <p>The session action ID of the session action that could not be retrieved.</p>
    pub fn get_session_action_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.session_action_id
    }
    /// <p>The error code.</p>
    /// This field is required.
    pub fn code(mut self, input: crate::types::BatchGetSessionActionErrorCode) -> Self {
        self.code = ::std::option::Option::Some(input);
        self
    }
    /// <p>The error code.</p>
    pub fn set_code(mut self, input: ::std::option::Option<crate::types::BatchGetSessionActionErrorCode>) -> Self {
        self.code = input;
        self
    }
    /// <p>The error code.</p>
    pub fn get_code(&self) -> &::std::option::Option<crate::types::BatchGetSessionActionErrorCode> {
        &self.code
    }
    /// <p>The error message.</p>
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The error message.</p>
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    /// <p>The error message.</p>
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Consumes the builder and constructs a [`BatchGetSessionActionError`](crate::types::BatchGetSessionActionError).
    /// This method will fail if any of the following fields are not set:
    /// - [`farm_id`](crate::types::builders::BatchGetSessionActionErrorBuilder::farm_id)
    /// - [`queue_id`](crate::types::builders::BatchGetSessionActionErrorBuilder::queue_id)
    /// - [`job_id`](crate::types::builders::BatchGetSessionActionErrorBuilder::job_id)
    /// - [`session_action_id`](crate::types::builders::BatchGetSessionActionErrorBuilder::session_action_id)
    /// - [`code`](crate::types::builders::BatchGetSessionActionErrorBuilder::code)
    /// - [`message`](crate::types::builders::BatchGetSessionActionErrorBuilder::message)
    pub fn build(self) -> ::std::result::Result<crate::types::BatchGetSessionActionError, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::BatchGetSessionActionError {
            farm_id: self.farm_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "farm_id",
                    "farm_id was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
            queue_id: self.queue_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "queue_id",
                    "queue_id was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
            job_id: self.job_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "job_id",
                    "job_id was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
            session_action_id: self.session_action_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "session_action_id",
                    "session_action_id was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
            code: self.code.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "code",
                    "code was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
            message: self.message.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "message",
                    "message was not specified but it is required when building BatchGetSessionActionError",
                )
            })?,
        })
    }
}
