// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Defines the override behavior for jobs at the maximum priority (100) in weighted balanced scheduling.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum SchedulingMaxPriorityOverride {
    /// <p>Jobs at the maximum priority (100) are always scheduled before other jobs, regardless of the weighted scheduling formula. If multiple jobs have priority 100, ties are broken using the standard weighted formula.</p>
    AlwaysScheduleFirst(crate::types::SchedulingMaxPriorityOverrideAlwaysScheduleFirst),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl SchedulingMaxPriorityOverride {
    #[allow(irrefutable_let_patterns)]
    /// Tries to convert the enum instance into [`AlwaysScheduleFirst`](crate::types::SchedulingMaxPriorityOverride::AlwaysScheduleFirst), extracting the inner [`SchedulingMaxPriorityOverrideAlwaysScheduleFirst`](crate::types::SchedulingMaxPriorityOverrideAlwaysScheduleFirst).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_always_schedule_first(&self) -> ::std::result::Result<&crate::types::SchedulingMaxPriorityOverrideAlwaysScheduleFirst, &Self> {
        if let SchedulingMaxPriorityOverride::AlwaysScheduleFirst(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`AlwaysScheduleFirst`](crate::types::SchedulingMaxPriorityOverride::AlwaysScheduleFirst).
    pub fn is_always_schedule_first(&self) -> bool {
        self.as_always_schedule_first().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
