// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Represents a field in the detailed view of an insight, returned by the <code>DescribeInsightDetails</code> operation.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct InsightField {
    /// <p>The name of the insight field.</p>
    pub name: ::std::string::String,
    /// <p>The type of the insight field. Possible values are <code>text</code> and <code>metric</code>.</p>
    pub r#type: crate::types::InsightFieldType,
    /// <p>The value of the insight field.</p>
    pub value: ::std::string::String,
}
impl InsightField {
    /// <p>The name of the insight field.</p>
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
    /// <p>The type of the insight field. Possible values are <code>text</code> and <code>metric</code>.</p>
    pub fn r#type(&self) -> &crate::types::InsightFieldType {
        &self.r#type
    }
    /// <p>The value of the insight field.</p>
    pub fn value(&self) -> &str {
        use std::ops::Deref;
        self.value.deref()
    }
}
impl InsightField {
    /// Creates a new builder-style object to manufacture [`InsightField`](crate::types::InsightField).
    pub fn builder() -> crate::types::builders::InsightFieldBuilder {
        crate::types::builders::InsightFieldBuilder::default()
    }
}

/// A builder for [`InsightField`](crate::types::InsightField).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct InsightFieldBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) r#type: ::std::option::Option<crate::types::InsightFieldType>,
    pub(crate) value: ::std::option::Option<::std::string::String>,
}
impl InsightFieldBuilder {
    /// <p>The name of the insight field.</p>
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the insight field.</p>
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// <p>The name of the insight field.</p>
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// <p>The type of the insight field. Possible values are <code>text</code> and <code>metric</code>.</p>
    /// This field is required.
    pub fn r#type(mut self, input: crate::types::InsightFieldType) -> Self {
        self.r#type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The type of the insight field. Possible values are <code>text</code> and <code>metric</code>.</p>
    pub fn set_type(mut self, input: ::std::option::Option<crate::types::InsightFieldType>) -> Self {
        self.r#type = input;
        self
    }
    /// <p>The type of the insight field. Possible values are <code>text</code> and <code>metric</code>.</p>
    pub fn get_type(&self) -> &::std::option::Option<crate::types::InsightFieldType> {
        &self.r#type
    }
    /// <p>The value of the insight field.</p>
    /// This field is required.
    pub fn value(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The value of the insight field.</p>
    pub fn set_value(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.value = input;
        self
    }
    /// <p>The value of the insight field.</p>
    pub fn get_value(&self) -> &::std::option::Option<::std::string::String> {
        &self.value
    }
    /// Consumes the builder and constructs a [`InsightField`](crate::types::InsightField).
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](crate::types::builders::InsightFieldBuilder::name)
    /// - [`r#type`](crate::types::builders::InsightFieldBuilder::type)
    /// - [`value`](crate::types::builders::InsightFieldBuilder::value)
    pub fn build(self) -> ::std::result::Result<crate::types::InsightField, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::InsightField {
            name: self.name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "name",
                    "name was not specified but it is required when building InsightField",
                )
            })?,
            r#type: self.r#type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "r#type",
                    "r#type was not specified but it is required when building InsightField",
                )
            })?,
            value: self.value.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "value",
                    "value was not specified but it is required when building InsightField",
                )
            })?,
        })
    }
}
