// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeletePolicy`](crate::operation::delete_policy::builders::DeletePolicyFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`policy_store_id(impl Into<String>)`](crate::operation::delete_policy::builders::DeletePolicyFluentBuilder::policy_store_id) / [`set_policy_store_id(Option<String>)`](crate::operation::delete_policy::builders::DeletePolicyFluentBuilder::set_policy_store_id):<br>required: **true**<br><p>Specifies the ID of the policy store that contains the policy that you want to delete.</p> <p>To specify a policy store, use its ID or alias name. When using an alias name, prefix it with <code>policy-store-alias/</code>. For example:</p> <ul>  <li>   <p>ID: <code>PSEXAMPLEabcdefg111111</code></p></li>  <li>   <p>Alias name: <code>policy-store-alias/example-policy-store</code></p></li> </ul> <p>To view aliases, use <a href="https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_ListPolicyStoreAliases.html">ListPolicyStoreAliases</a>.</p><br>
    ///   - [`policy_id(impl Into<String>)`](crate::operation::delete_policy::builders::DeletePolicyFluentBuilder::policy_id) / [`set_policy_id(Option<String>)`](crate::operation::delete_policy::builders::DeletePolicyFluentBuilder::set_policy_id):<br>required: **true**<br><p>Specifies the ID of the policy that you want to delete.</p> <p>You can use the policy name in place of the policy ID. When using a name, prefix it with <code>name/</code>. For example:</p> <ul>  <li>   <p>ID: <code>SPEXAMPLEabcdefg111111</code></p></li>  <li>   <p>Name: <code>name/example-policy</code></p></li> </ul><br>
    /// - On success, responds with [`DeletePolicyOutput`](crate::operation::delete_policy::DeletePolicyOutput)
    /// - On failure, responds with [`SdkError<DeletePolicyError>`](crate::operation::delete_policy::DeletePolicyError)
    pub fn delete_policy(&self) -> crate::operation::delete_policy::builders::DeletePolicyFluentBuilder {
        crate::operation::delete_policy::builders::DeletePolicyFluentBuilder::new(self.handle.clone())
    }
}
