// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains information about an S3 File System Access Point returned in list operations.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListAccessPointsDescription {
    /// <p>The Amazon Resource Name (ARN) of the access point.</p>
    pub access_point_arn: ::std::string::String,
    /// <p>The ID of the access point.</p>
    pub access_point_id: ::std::string::String,
    /// <p>The ID of the S3 File System.</p>
    pub file_system_id: ::std::string::String,
    /// <p>The current status of the access point.</p>
    pub status: crate::types::LifeCycleState,
    /// <p>The Amazon Web Services account ID of the access point owner.</p>
    pub owner_id: ::std::string::String,
    /// <p>The POSIX identity configured for this access point.</p>
    pub posix_user: ::std::option::Option<crate::types::PosixUser>,
    /// <p>The root directory configuration for this access point.</p>
    pub root_directory: ::std::option::Option<crate::types::RootDirectory>,
    /// <p>The name of the access point.</p>
    pub name: ::std::option::Option<::std::string::String>,
}
impl ListAccessPointsDescription {
    /// <p>The Amazon Resource Name (ARN) of the access point.</p>
    pub fn access_point_arn(&self) -> &str {
        use std::ops::Deref;
        self.access_point_arn.deref()
    }
    /// <p>The ID of the access point.</p>
    pub fn access_point_id(&self) -> &str {
        use std::ops::Deref;
        self.access_point_id.deref()
    }
    /// <p>The ID of the S3 File System.</p>
    pub fn file_system_id(&self) -> &str {
        use std::ops::Deref;
        self.file_system_id.deref()
    }
    /// <p>The current status of the access point.</p>
    pub fn status(&self) -> &crate::types::LifeCycleState {
        &self.status
    }
    /// <p>The Amazon Web Services account ID of the access point owner.</p>
    pub fn owner_id(&self) -> &str {
        use std::ops::Deref;
        self.owner_id.deref()
    }
    /// <p>The POSIX identity configured for this access point.</p>
    pub fn posix_user(&self) -> ::std::option::Option<&crate::types::PosixUser> {
        self.posix_user.as_ref()
    }
    /// <p>The root directory configuration for this access point.</p>
    pub fn root_directory(&self) -> ::std::option::Option<&crate::types::RootDirectory> {
        self.root_directory.as_ref()
    }
    /// <p>The name of the access point.</p>
    pub fn name(&self) -> ::std::option::Option<&str> {
        self.name.as_deref()
    }
}
impl ListAccessPointsDescription {
    /// Creates a new builder-style object to manufacture [`ListAccessPointsDescription`](crate::types::ListAccessPointsDescription).
    pub fn builder() -> crate::types::builders::ListAccessPointsDescriptionBuilder {
        crate::types::builders::ListAccessPointsDescriptionBuilder::default()
    }
}

/// A builder for [`ListAccessPointsDescription`](crate::types::ListAccessPointsDescription).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListAccessPointsDescriptionBuilder {
    pub(crate) access_point_arn: ::std::option::Option<::std::string::String>,
    pub(crate) access_point_id: ::std::option::Option<::std::string::String>,
    pub(crate) file_system_id: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::LifeCycleState>,
    pub(crate) owner_id: ::std::option::Option<::std::string::String>,
    pub(crate) posix_user: ::std::option::Option<crate::types::PosixUser>,
    pub(crate) root_directory: ::std::option::Option<crate::types::RootDirectory>,
    pub(crate) name: ::std::option::Option<::std::string::String>,
}
impl ListAccessPointsDescriptionBuilder {
    /// <p>The Amazon Resource Name (ARN) of the access point.</p>
    /// This field is required.
    pub fn access_point_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.access_point_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the access point.</p>
    pub fn set_access_point_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.access_point_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the access point.</p>
    pub fn get_access_point_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.access_point_arn
    }
    /// <p>The ID of the access point.</p>
    /// This field is required.
    pub fn access_point_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.access_point_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the access point.</p>
    pub fn set_access_point_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.access_point_id = input;
        self
    }
    /// <p>The ID of the access point.</p>
    pub fn get_access_point_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.access_point_id
    }
    /// <p>The ID of the S3 File System.</p>
    /// This field is required.
    pub fn file_system_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.file_system_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the S3 File System.</p>
    pub fn set_file_system_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.file_system_id = input;
        self
    }
    /// <p>The ID of the S3 File System.</p>
    pub fn get_file_system_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.file_system_id
    }
    /// <p>The current status of the access point.</p>
    /// This field is required.
    pub fn status(mut self, input: crate::types::LifeCycleState) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    /// <p>The current status of the access point.</p>
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::LifeCycleState>) -> Self {
        self.status = input;
        self
    }
    /// <p>The current status of the access point.</p>
    pub fn get_status(&self) -> &::std::option::Option<crate::types::LifeCycleState> {
        &self.status
    }
    /// <p>The Amazon Web Services account ID of the access point owner.</p>
    /// This field is required.
    pub fn owner_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.owner_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Web Services account ID of the access point owner.</p>
    pub fn set_owner_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.owner_id = input;
        self
    }
    /// <p>The Amazon Web Services account ID of the access point owner.</p>
    pub fn get_owner_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.owner_id
    }
    /// <p>The POSIX identity configured for this access point.</p>
    pub fn posix_user(mut self, input: crate::types::PosixUser) -> Self {
        self.posix_user = ::std::option::Option::Some(input);
        self
    }
    /// <p>The POSIX identity configured for this access point.</p>
    pub fn set_posix_user(mut self, input: ::std::option::Option<crate::types::PosixUser>) -> Self {
        self.posix_user = input;
        self
    }
    /// <p>The POSIX identity configured for this access point.</p>
    pub fn get_posix_user(&self) -> &::std::option::Option<crate::types::PosixUser> {
        &self.posix_user
    }
    /// <p>The root directory configuration for this access point.</p>
    pub fn root_directory(mut self, input: crate::types::RootDirectory) -> Self {
        self.root_directory = ::std::option::Option::Some(input);
        self
    }
    /// <p>The root directory configuration for this access point.</p>
    pub fn set_root_directory(mut self, input: ::std::option::Option<crate::types::RootDirectory>) -> Self {
        self.root_directory = input;
        self
    }
    /// <p>The root directory configuration for this access point.</p>
    pub fn get_root_directory(&self) -> &::std::option::Option<crate::types::RootDirectory> {
        &self.root_directory
    }
    /// <p>The name of the access point.</p>
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the access point.</p>
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// <p>The name of the access point.</p>
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// Consumes the builder and constructs a [`ListAccessPointsDescription`](crate::types::ListAccessPointsDescription).
    /// This method will fail if any of the following fields are not set:
    /// - [`access_point_arn`](crate::types::builders::ListAccessPointsDescriptionBuilder::access_point_arn)
    /// - [`access_point_id`](crate::types::builders::ListAccessPointsDescriptionBuilder::access_point_id)
    /// - [`file_system_id`](crate::types::builders::ListAccessPointsDescriptionBuilder::file_system_id)
    /// - [`status`](crate::types::builders::ListAccessPointsDescriptionBuilder::status)
    /// - [`owner_id`](crate::types::builders::ListAccessPointsDescriptionBuilder::owner_id)
    pub fn build(self) -> ::std::result::Result<crate::types::ListAccessPointsDescription, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ListAccessPointsDescription {
            access_point_arn: self.access_point_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "access_point_arn",
                    "access_point_arn was not specified but it is required when building ListAccessPointsDescription",
                )
            })?,
            access_point_id: self.access_point_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "access_point_id",
                    "access_point_id was not specified but it is required when building ListAccessPointsDescription",
                )
            })?,
            file_system_id: self.file_system_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "file_system_id",
                    "file_system_id was not specified but it is required when building ListAccessPointsDescription",
                )
            })?,
            status: self.status.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "status",
                    "status was not specified but it is required when building ListAccessPointsDescription",
                )
            })?,
            owner_id: self.owner_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "owner_id",
                    "owner_id was not specified but it is required when building ListAccessPointsDescription",
                )
            })?,
            posix_user: self.posix_user,
            root_directory: self.root_directory,
            name: self.name,
        })
    }
}
