// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The configuration of deep health checks for an instance group.</p><note>
/// <p>Overlapping deep health check configurations will be merged into a single operation.</p>
/// </note>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct InstanceGroupHealthCheckConfiguration {
    /// <p>The name of the instance group.</p>
    pub instance_group_name: ::std::string::String,
    /// <p>A list of Amazon Elastic Compute Cloud (EC2) instance IDs on which to perform deep health checks.</p><note>
    /// <p>Leave this field blank to perform deep health checks on the entire instance group.</p>
    /// </note>
    pub instance_ids: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>A list of deep health checks to be performed.</p>
    pub deep_health_checks: ::std::vec::Vec<crate::types::DeepHealthCheckType>,
}
impl InstanceGroupHealthCheckConfiguration {
    /// <p>The name of the instance group.</p>
    pub fn instance_group_name(&self) -> &str {
        use std::ops::Deref;
        self.instance_group_name.deref()
    }
    /// <p>A list of Amazon Elastic Compute Cloud (EC2) instance IDs on which to perform deep health checks.</p><note>
    /// <p>Leave this field blank to perform deep health checks on the entire instance group.</p>
    /// </note>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.instance_ids.is_none()`.
    pub fn instance_ids(&self) -> &[::std::string::String] {
        self.instance_ids.as_deref().unwrap_or_default()
    }
    /// <p>A list of deep health checks to be performed.</p>
    pub fn deep_health_checks(&self) -> &[crate::types::DeepHealthCheckType] {
        use std::ops::Deref;
        self.deep_health_checks.deref()
    }
}
impl InstanceGroupHealthCheckConfiguration {
    /// Creates a new builder-style object to manufacture [`InstanceGroupHealthCheckConfiguration`](crate::types::InstanceGroupHealthCheckConfiguration).
    pub fn builder() -> crate::types::builders::InstanceGroupHealthCheckConfigurationBuilder {
        crate::types::builders::InstanceGroupHealthCheckConfigurationBuilder::default()
    }
}

/// A builder for [`InstanceGroupHealthCheckConfiguration`](crate::types::InstanceGroupHealthCheckConfiguration).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct InstanceGroupHealthCheckConfigurationBuilder {
    pub(crate) instance_group_name: ::std::option::Option<::std::string::String>,
    pub(crate) instance_ids: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) deep_health_checks: ::std::option::Option<::std::vec::Vec<crate::types::DeepHealthCheckType>>,
}
impl InstanceGroupHealthCheckConfigurationBuilder {
    /// <p>The name of the instance group.</p>
    /// This field is required.
    pub fn instance_group_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.instance_group_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the instance group.</p>
    pub fn set_instance_group_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.instance_group_name = input;
        self
    }
    /// <p>The name of the instance group.</p>
    pub fn get_instance_group_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.instance_group_name
    }
    /// Appends an item to `instance_ids`.
    ///
    /// To override the contents of this collection use [`set_instance_ids`](Self::set_instance_ids).
    ///
    /// <p>A list of Amazon Elastic Compute Cloud (EC2) instance IDs on which to perform deep health checks.</p><note>
    /// <p>Leave this field blank to perform deep health checks on the entire instance group.</p>
    /// </note>
    pub fn instance_ids(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.instance_ids.unwrap_or_default();
        v.push(input.into());
        self.instance_ids = ::std::option::Option::Some(v);
        self
    }
    /// <p>A list of Amazon Elastic Compute Cloud (EC2) instance IDs on which to perform deep health checks.</p><note>
    /// <p>Leave this field blank to perform deep health checks on the entire instance group.</p>
    /// </note>
    pub fn set_instance_ids(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.instance_ids = input;
        self
    }
    /// <p>A list of Amazon Elastic Compute Cloud (EC2) instance IDs on which to perform deep health checks.</p><note>
    /// <p>Leave this field blank to perform deep health checks on the entire instance group.</p>
    /// </note>
    pub fn get_instance_ids(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.instance_ids
    }
    /// Appends an item to `deep_health_checks`.
    ///
    /// To override the contents of this collection use [`set_deep_health_checks`](Self::set_deep_health_checks).
    ///
    /// <p>A list of deep health checks to be performed.</p>
    pub fn deep_health_checks(mut self, input: crate::types::DeepHealthCheckType) -> Self {
        let mut v = self.deep_health_checks.unwrap_or_default();
        v.push(input);
        self.deep_health_checks = ::std::option::Option::Some(v);
        self
    }
    /// <p>A list of deep health checks to be performed.</p>
    pub fn set_deep_health_checks(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::DeepHealthCheckType>>) -> Self {
        self.deep_health_checks = input;
        self
    }
    /// <p>A list of deep health checks to be performed.</p>
    pub fn get_deep_health_checks(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::DeepHealthCheckType>> {
        &self.deep_health_checks
    }
    /// Consumes the builder and constructs a [`InstanceGroupHealthCheckConfiguration`](crate::types::InstanceGroupHealthCheckConfiguration).
    /// This method will fail if any of the following fields are not set:
    /// - [`instance_group_name`](crate::types::builders::InstanceGroupHealthCheckConfigurationBuilder::instance_group_name)
    /// - [`deep_health_checks`](crate::types::builders::InstanceGroupHealthCheckConfigurationBuilder::deep_health_checks)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::InstanceGroupHealthCheckConfiguration, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::InstanceGroupHealthCheckConfiguration {
            instance_group_name: self.instance_group_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "instance_group_name",
                    "instance_group_name was not specified but it is required when building InstanceGroupHealthCheckConfiguration",
                )
            })?,
            instance_ids: self.instance_ids,
            deep_health_checks: self.deep_health_checks.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "deep_health_checks",
                    "deep_health_checks was not specified but it is required when building InstanceGroupHealthCheckConfiguration",
                )
            })?,
        })
    }
}
