// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub struct StartSpeechSynthesisStreamInput {
    /// <p>Specifies the engine for Amazon Polly to use when processing input text for speech synthesis. Currently, only the <code>generative</code> engine is supported. If you specify a voice that the selected engine doesn't support, Amazon Polly returns an error.</p>
    pub engine: ::std::option::Option<crate::types::Engine>,
    /// <p>An optional parameter that sets the language code for the speech synthesis request. Specify this parameter only when using a bilingual voice. If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice.</p>
    pub language_code: ::std::option::Option<crate::types::LanguageCode>,
    /// <p>The names of one or more pronunciation lexicons for the service to apply during synthesis. Amazon Polly applies lexicons only when the lexicon language matches the voice language.</p>
    pub lexicon_names: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>The audio format for the synthesized speech. Currently, Amazon Polly does not support JSON speech marks.</p>
    pub output_format: ::std::option::Option<crate::types::OutputFormat>,
    /// <p>The audio frequency, specified in Hz.</p>
    pub sample_rate: ::std::option::Option<::std::string::String>,
    /// <p>The voice to use in synthesis. To get a list of available voice IDs, use the <a href="https://docs.aws.amazon.com/polly/latest/API/API_DescribeVoices.html">DescribeVoices</a> operation.</p>
    pub voice_id: ::std::option::Option<crate::types::VoiceId>,
    /// <p>The input event stream that contains text events and stream control events.</p>
    pub action_stream: ::aws_smithy_http::event_stream::EventStreamSender<
        crate::types::StartSpeechSynthesisStreamActionStream,
        crate::types::error::StartSpeechSynthesisStreamActionStreamError,
    >,
}
impl StartSpeechSynthesisStreamInput {
    /// <p>Specifies the engine for Amazon Polly to use when processing input text for speech synthesis. Currently, only the <code>generative</code> engine is supported. If you specify a voice that the selected engine doesn't support, Amazon Polly returns an error.</p>
    pub fn engine(&self) -> ::std::option::Option<&crate::types::Engine> {
        self.engine.as_ref()
    }
    /// <p>An optional parameter that sets the language code for the speech synthesis request. Specify this parameter only when using a bilingual voice. If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice.</p>
    pub fn language_code(&self) -> ::std::option::Option<&crate::types::LanguageCode> {
        self.language_code.as_ref()
    }
    /// <p>The names of one or more pronunciation lexicons for the service to apply during synthesis. Amazon Polly applies lexicons only when the lexicon language matches the voice language.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.lexicon_names.is_none()`.
    pub fn lexicon_names(&self) -> &[::std::string::String] {
        self.lexicon_names.as_deref().unwrap_or_default()
    }
    /// <p>The audio format for the synthesized speech. Currently, Amazon Polly does not support JSON speech marks.</p>
    pub fn output_format(&self) -> ::std::option::Option<&crate::types::OutputFormat> {
        self.output_format.as_ref()
    }
    /// <p>The audio frequency, specified in Hz.</p>
    pub fn sample_rate(&self) -> ::std::option::Option<&str> {
        self.sample_rate.as_deref()
    }
    /// <p>The voice to use in synthesis. To get a list of available voice IDs, use the <a href="https://docs.aws.amazon.com/polly/latest/API/API_DescribeVoices.html">DescribeVoices</a> operation.</p>
    pub fn voice_id(&self) -> ::std::option::Option<&crate::types::VoiceId> {
        self.voice_id.as_ref()
    }
    /// <p>The input event stream that contains text events and stream control events.</p>
    pub fn action_stream(
        &self,
    ) -> &::aws_smithy_http::event_stream::EventStreamSender<
        crate::types::StartSpeechSynthesisStreamActionStream,
        crate::types::error::StartSpeechSynthesisStreamActionStreamError,
    > {
        &self.action_stream
    }
}
impl StartSpeechSynthesisStreamInput {
    /// Creates a new builder-style object to manufacture [`StartSpeechSynthesisStreamInput`](crate::operation::start_speech_synthesis_stream::StartSpeechSynthesisStreamInput).
    pub fn builder() -> crate::operation::start_speech_synthesis_stream::builders::StartSpeechSynthesisStreamInputBuilder {
        crate::operation::start_speech_synthesis_stream::builders::StartSpeechSynthesisStreamInputBuilder::default()
    }
}

/// A builder for [`StartSpeechSynthesisStreamInput`](crate::operation::start_speech_synthesis_stream::StartSpeechSynthesisStreamInput).
#[derive(::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct StartSpeechSynthesisStreamInputBuilder {
    pub(crate) engine: ::std::option::Option<crate::types::Engine>,
    pub(crate) language_code: ::std::option::Option<crate::types::LanguageCode>,
    pub(crate) lexicon_names: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) output_format: ::std::option::Option<crate::types::OutputFormat>,
    pub(crate) sample_rate: ::std::option::Option<::std::string::String>,
    pub(crate) voice_id: ::std::option::Option<crate::types::VoiceId>,
    pub(crate) action_stream: ::std::option::Option<
        ::aws_smithy_http::event_stream::EventStreamSender<
            crate::types::StartSpeechSynthesisStreamActionStream,
            crate::types::error::StartSpeechSynthesisStreamActionStreamError,
        >,
    >,
}
impl StartSpeechSynthesisStreamInputBuilder {
    /// <p>Specifies the engine for Amazon Polly to use when processing input text for speech synthesis. Currently, only the <code>generative</code> engine is supported. If you specify a voice that the selected engine doesn't support, Amazon Polly returns an error.</p>
    /// This field is required.
    pub fn engine(mut self, input: crate::types::Engine) -> Self {
        self.engine = ::std::option::Option::Some(input);
        self
    }
    /// <p>Specifies the engine for Amazon Polly to use when processing input text for speech synthesis. Currently, only the <code>generative</code> engine is supported. If you specify a voice that the selected engine doesn't support, Amazon Polly returns an error.</p>
    pub fn set_engine(mut self, input: ::std::option::Option<crate::types::Engine>) -> Self {
        self.engine = input;
        self
    }
    /// <p>Specifies the engine for Amazon Polly to use when processing input text for speech synthesis. Currently, only the <code>generative</code> engine is supported. If you specify a voice that the selected engine doesn't support, Amazon Polly returns an error.</p>
    pub fn get_engine(&self) -> &::std::option::Option<crate::types::Engine> {
        &self.engine
    }
    /// <p>An optional parameter that sets the language code for the speech synthesis request. Specify this parameter only when using a bilingual voice. If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice.</p>
    pub fn language_code(mut self, input: crate::types::LanguageCode) -> Self {
        self.language_code = ::std::option::Option::Some(input);
        self
    }
    /// <p>An optional parameter that sets the language code for the speech synthesis request. Specify this parameter only when using a bilingual voice. If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice.</p>
    pub fn set_language_code(mut self, input: ::std::option::Option<crate::types::LanguageCode>) -> Self {
        self.language_code = input;
        self
    }
    /// <p>An optional parameter that sets the language code for the speech synthesis request. Specify this parameter only when using a bilingual voice. If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice.</p>
    pub fn get_language_code(&self) -> &::std::option::Option<crate::types::LanguageCode> {
        &self.language_code
    }
    /// Appends an item to `lexicon_names`.
    ///
    /// To override the contents of this collection use [`set_lexicon_names`](Self::set_lexicon_names).
    ///
    /// <p>The names of one or more pronunciation lexicons for the service to apply during synthesis. Amazon Polly applies lexicons only when the lexicon language matches the voice language.</p>
    pub fn lexicon_names(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.lexicon_names.unwrap_or_default();
        v.push(input.into());
        self.lexicon_names = ::std::option::Option::Some(v);
        self
    }
    /// <p>The names of one or more pronunciation lexicons for the service to apply during synthesis. Amazon Polly applies lexicons only when the lexicon language matches the voice language.</p>
    pub fn set_lexicon_names(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.lexicon_names = input;
        self
    }
    /// <p>The names of one or more pronunciation lexicons for the service to apply during synthesis. Amazon Polly applies lexicons only when the lexicon language matches the voice language.</p>
    pub fn get_lexicon_names(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.lexicon_names
    }
    /// <p>The audio format for the synthesized speech. Currently, Amazon Polly does not support JSON speech marks.</p>
    /// This field is required.
    pub fn output_format(mut self, input: crate::types::OutputFormat) -> Self {
        self.output_format = ::std::option::Option::Some(input);
        self
    }
    /// <p>The audio format for the synthesized speech. Currently, Amazon Polly does not support JSON speech marks.</p>
    pub fn set_output_format(mut self, input: ::std::option::Option<crate::types::OutputFormat>) -> Self {
        self.output_format = input;
        self
    }
    /// <p>The audio format for the synthesized speech. Currently, Amazon Polly does not support JSON speech marks.</p>
    pub fn get_output_format(&self) -> &::std::option::Option<crate::types::OutputFormat> {
        &self.output_format
    }
    /// <p>The audio frequency, specified in Hz.</p>
    pub fn sample_rate(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.sample_rate = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The audio frequency, specified in Hz.</p>
    pub fn set_sample_rate(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.sample_rate = input;
        self
    }
    /// <p>The audio frequency, specified in Hz.</p>
    pub fn get_sample_rate(&self) -> &::std::option::Option<::std::string::String> {
        &self.sample_rate
    }
    /// <p>The voice to use in synthesis. To get a list of available voice IDs, use the <a href="https://docs.aws.amazon.com/polly/latest/API/API_DescribeVoices.html">DescribeVoices</a> operation.</p>
    /// This field is required.
    pub fn voice_id(mut self, input: crate::types::VoiceId) -> Self {
        self.voice_id = ::std::option::Option::Some(input);
        self
    }
    /// <p>The voice to use in synthesis. To get a list of available voice IDs, use the <a href="https://docs.aws.amazon.com/polly/latest/API/API_DescribeVoices.html">DescribeVoices</a> operation.</p>
    pub fn set_voice_id(mut self, input: ::std::option::Option<crate::types::VoiceId>) -> Self {
        self.voice_id = input;
        self
    }
    /// <p>The voice to use in synthesis. To get a list of available voice IDs, use the <a href="https://docs.aws.amazon.com/polly/latest/API/API_DescribeVoices.html">DescribeVoices</a> operation.</p>
    pub fn get_voice_id(&self) -> &::std::option::Option<crate::types::VoiceId> {
        &self.voice_id
    }
    /// <p>The input event stream that contains text events and stream control events.</p>
    pub fn action_stream(
        mut self,
        input: ::aws_smithy_http::event_stream::EventStreamSender<
            crate::types::StartSpeechSynthesisStreamActionStream,
            crate::types::error::StartSpeechSynthesisStreamActionStreamError,
        >,
    ) -> Self {
        self.action_stream = ::std::option::Option::Some(input);
        self
    }
    /// <p>The input event stream that contains text events and stream control events.</p>
    pub fn set_action_stream(
        mut self,
        input: ::std::option::Option<
            ::aws_smithy_http::event_stream::EventStreamSender<
                crate::types::StartSpeechSynthesisStreamActionStream,
                crate::types::error::StartSpeechSynthesisStreamActionStreamError,
            >,
        >,
    ) -> Self {
        self.action_stream = input;
        self
    }
    /// <p>The input event stream that contains text events and stream control events.</p>
    pub fn get_action_stream(
        &self,
    ) -> &::std::option::Option<
        ::aws_smithy_http::event_stream::EventStreamSender<
            crate::types::StartSpeechSynthesisStreamActionStream,
            crate::types::error::StartSpeechSynthesisStreamActionStreamError,
        >,
    > {
        &self.action_stream
    }
    /// Consumes the builder and constructs a [`StartSpeechSynthesisStreamInput`](crate::operation::start_speech_synthesis_stream::StartSpeechSynthesisStreamInput).
    /// This method will fail if any of the following fields are not set:
    /// - [`action_stream`](crate::operation::start_speech_synthesis_stream::builders::StartSpeechSynthesisStreamInputBuilder::action_stream)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::start_speech_synthesis_stream::StartSpeechSynthesisStreamInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::start_speech_synthesis_stream::StartSpeechSynthesisStreamInput {
            engine: self.engine,
            language_code: self.language_code,
            lexicon_names: self.lexicon_names,
            output_format: self.output_format,
            sample_rate: self.sample_rate,
            voice_id: self.voice_id,
            action_stream: self.action_stream.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "action_stream",
                    "action_stream was not specified but it is required when building StartSpeechSynthesisStreamInput",
                )
            })?,
        })
    }
}
