// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_o_auth_client_credentials(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::OAuthClientCredentials,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.client_id {
        object.key("ClientId").string(var_1.as_str());
    }
    if let Some(var_2) = &input.client_secret {
        object.key("ClientSecret").string(var_2.as_str());
    }
    if let Some(var_3) = &input.username {
        object.key("Username").string(var_3.as_str());
    }
    Ok(())
}
