// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetArtifactInput {
    /// Unique identifier of the agent space
    pub agent_space_id: ::std::option::Option<::std::string::String>,
    /// Unique identifier of the artifact
    pub artifact_id: ::std::option::Option<::std::string::String>,
}
impl GetArtifactInput {
    /// Unique identifier of the agent space
    pub fn agent_space_id(&self) -> ::std::option::Option<&str> {
        self.agent_space_id.as_deref()
    }
    /// Unique identifier of the artifact
    pub fn artifact_id(&self) -> ::std::option::Option<&str> {
        self.artifact_id.as_deref()
    }
}
impl GetArtifactInput {
    /// Creates a new builder-style object to manufacture [`GetArtifactInput`](crate::operation::get_artifact::GetArtifactInput).
    pub fn builder() -> crate::operation::get_artifact::builders::GetArtifactInputBuilder {
        crate::operation::get_artifact::builders::GetArtifactInputBuilder::default()
    }
}

/// A builder for [`GetArtifactInput`](crate::operation::get_artifact::GetArtifactInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetArtifactInputBuilder {
    pub(crate) agent_space_id: ::std::option::Option<::std::string::String>,
    pub(crate) artifact_id: ::std::option::Option<::std::string::String>,
}
impl GetArtifactInputBuilder {
    /// Unique identifier of the agent space
    /// This field is required.
    pub fn agent_space_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.agent_space_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Unique identifier of the agent space
    pub fn set_agent_space_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.agent_space_id = input;
        self
    }
    /// Unique identifier of the agent space
    pub fn get_agent_space_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.agent_space_id
    }
    /// Unique identifier of the artifact
    /// This field is required.
    pub fn artifact_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.artifact_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Unique identifier of the artifact
    pub fn set_artifact_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.artifact_id = input;
        self
    }
    /// Unique identifier of the artifact
    pub fn get_artifact_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.artifact_id
    }
    /// Consumes the builder and constructs a [`GetArtifactInput`](crate::operation::get_artifact::GetArtifactInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::get_artifact::GetArtifactInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::get_artifact::GetArtifactInput {
            agent_space_id: self.agent_space_id,
            artifact_id: self.artifact_id,
        })
    }
}
