// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct StartAutomationJobInput {
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub aws_account_id: ::std::option::Option<::std::string::String>,
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub automation_group_id: ::std::option::Option<::std::string::String>,
    /// <p>The ID of the automation to run.</p>
    pub automation_id: ::std::option::Option<::std::string::String>,
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub input_payload: ::std::option::Option<::std::string::String>,
}
impl StartAutomationJobInput {
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn aws_account_id(&self) -> ::std::option::Option<&str> {
        self.aws_account_id.as_deref()
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn automation_group_id(&self) -> ::std::option::Option<&str> {
        self.automation_group_id.as_deref()
    }
    /// <p>The ID of the automation to run.</p>
    pub fn automation_id(&self) -> ::std::option::Option<&str> {
        self.automation_id.as_deref()
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn input_payload(&self) -> ::std::option::Option<&str> {
        self.input_payload.as_deref()
    }
}
impl ::std::fmt::Debug for StartAutomationJobInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("StartAutomationJobInput");
        formatter.field("aws_account_id", &self.aws_account_id);
        formatter.field("automation_group_id", &self.automation_group_id);
        formatter.field("automation_id", &self.automation_id);
        formatter.field("input_payload", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl StartAutomationJobInput {
    /// Creates a new builder-style object to manufacture [`StartAutomationJobInput`](crate::operation::start_automation_job::StartAutomationJobInput).
    pub fn builder() -> crate::operation::start_automation_job::builders::StartAutomationJobInputBuilder {
        crate::operation::start_automation_job::builders::StartAutomationJobInputBuilder::default()
    }
}

/// A builder for [`StartAutomationJobInput`](crate::operation::start_automation_job::StartAutomationJobInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct StartAutomationJobInputBuilder {
    pub(crate) aws_account_id: ::std::option::Option<::std::string::String>,
    pub(crate) automation_group_id: ::std::option::Option<::std::string::String>,
    pub(crate) automation_id: ::std::option::Option<::std::string::String>,
    pub(crate) input_payload: ::std::option::Option<::std::string::String>,
}
impl StartAutomationJobInputBuilder {
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    /// This field is required.
    pub fn aws_account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.aws_account_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn set_aws_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.aws_account_id = input;
        self
    }
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn get_aws_account_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.aws_account_id
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    /// This field is required.
    pub fn automation_group_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.automation_group_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn set_automation_group_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.automation_group_id = input;
        self
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn get_automation_group_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.automation_group_id
    }
    /// <p>The ID of the automation to run.</p>
    /// This field is required.
    pub fn automation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.automation_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the automation to run.</p>
    pub fn set_automation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.automation_id = input;
        self
    }
    /// <p>The ID of the automation to run.</p>
    pub fn get_automation_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.automation_id
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn input_payload(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.input_payload = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn set_input_payload(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.input_payload = input;
        self
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn get_input_payload(&self) -> &::std::option::Option<::std::string::String> {
        &self.input_payload
    }
    /// Consumes the builder and constructs a [`StartAutomationJobInput`](crate::operation::start_automation_job::StartAutomationJobInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::start_automation_job::StartAutomationJobInput, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::operation::start_automation_job::StartAutomationJobInput {
            aws_account_id: self.aws_account_id,
            automation_group_id: self.automation_group_id,
            automation_id: self.automation_id,
            input_payload: self.input_payload,
        })
    }
}
impl ::std::fmt::Debug for StartAutomationJobInputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("StartAutomationJobInputBuilder");
        formatter.field("aws_account_id", &self.aws_account_id);
        formatter.field("automation_group_id", &self.automation_group_id);
        formatter.field("automation_id", &self.automation_id);
        formatter.field("input_payload", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
