// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::start_automation_job::_start_automation_job_input::StartAutomationJobInputBuilder;

pub use crate::operation::start_automation_job::_start_automation_job_output::StartAutomationJobOutputBuilder;

impl crate::operation::start_automation_job::builders::StartAutomationJobInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::start_automation_job::StartAutomationJobOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::start_automation_job::StartAutomationJobError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let mut fluent_builder = client.start_automation_job();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `StartAutomationJob`.
///
/// <p>Starts a new job for a specified automation. The job runs the automation with the provided input payload.</p>
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct StartAutomationJobFluentBuilder {
    handle: ::std::sync::Arc<crate::client::Handle>,
    inner: crate::operation::start_automation_job::builders::StartAutomationJobInputBuilder,
    config_override: ::std::option::Option<crate::config::Builder>,
}
impl
    crate::client::customize::internal::CustomizableSend<
        crate::operation::start_automation_job::StartAutomationJobOutput,
        crate::operation::start_automation_job::StartAutomationJobError,
    > for StartAutomationJobFluentBuilder
{
    fn send(
        self,
        config_override: crate::config::Builder,
    ) -> crate::client::customize::internal::BoxFuture<
        crate::client::customize::internal::SendResult<
            crate::operation::start_automation_job::StartAutomationJobOutput,
            crate::operation::start_automation_job::StartAutomationJobError,
        >,
    > {
        ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
    }
}
impl StartAutomationJobFluentBuilder {
    /// Creates a new `StartAutomationJobFluentBuilder`.
    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
        Self {
            handle,
            inner: ::std::default::Default::default(),
            config_override: ::std::option::Option::None,
        }
    }
    /// Access the StartAutomationJob as a reference.
    pub fn as_input(&self) -> &crate::operation::start_automation_job::builders::StartAutomationJobInputBuilder {
        &self.inner
    }
    /// Sends the request and returns the response.
    ///
    /// If an error occurs, an `SdkError` will be returned with additional details that
    /// can be matched against.
    ///
    /// By default, any retryable failures will be retried twice. Retry behavior
    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
    /// set when configuring the client.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::start_automation_job::StartAutomationJobOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::start_automation_job::StartAutomationJobError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let input = self
            .inner
            .build()
            .map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
        let runtime_plugins = crate::operation::start_automation_job::StartAutomationJob::operation_runtime_plugins(
            self.handle.runtime_plugins.clone(),
            &self.handle.conf,
            self.config_override,
        );
        crate::operation::start_automation_job::StartAutomationJob::orchestrate(&runtime_plugins, input).await
    }

    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
    pub fn customize(
        self,
    ) -> crate::client::customize::CustomizableOperation<
        crate::operation::start_automation_job::StartAutomationJobOutput,
        crate::operation::start_automation_job::StartAutomationJobError,
        Self,
    > {
        crate::client::customize::CustomizableOperation::new(self)
    }
    pub(crate) fn config_override(mut self, config_override: impl ::std::convert::Into<crate::config::Builder>) -> Self {
        self.set_config_override(::std::option::Option::Some(config_override.into()));
        self
    }

    pub(crate) fn set_config_override(&mut self, config_override: ::std::option::Option<crate::config::Builder>) -> &mut Self {
        self.config_override = config_override;
        self
    }
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn aws_account_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.aws_account_id(input.into());
        self
    }
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn set_aws_account_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_aws_account_id(input);
        self
    }
    /// <p>The ID of the Amazon Web Services account that contains the automation.</p>
    pub fn get_aws_account_id(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_aws_account_id()
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn automation_group_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.automation_group_id(input.into());
        self
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn set_automation_group_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_automation_group_id(input);
        self
    }
    /// <p>The ID of the automation group that contains the automation to run.</p>
    pub fn get_automation_group_id(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_automation_group_id()
    }
    /// <p>The ID of the automation to run.</p>
    pub fn automation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.automation_id(input.into());
        self
    }
    /// <p>The ID of the automation to run.</p>
    pub fn set_automation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_automation_id(input);
        self
    }
    /// <p>The ID of the automation to run.</p>
    pub fn get_automation_id(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_automation_id()
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn input_payload(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.input_payload(input.into());
        self
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn set_input_payload(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_input_payload(input);
        self
    }
    /// <p>The input payload for the automation job, provided as a JSON string.</p>
    pub fn get_input_payload(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_input_payload()
    }
}
