// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListDiscoveredEndpoints`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder) operation.
    /// This operation supports pagination; See [`into_paginator()`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::into_paginator).
    ///
    /// - The fluent builder is configurable:
    ///   - [`max_results(i32)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::set_max_results):<br>required: **false**<br>Maximum number of discovered endpoints to return in a single request (default: 50)<br>
    ///   - [`pentest_job_id(impl Into<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::pentest_job_id) / [`set_pentest_job_id(Option<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::set_pentest_job_id):<br>required: **true**<br>Identifier of the pentest job for which to retrieve discovered endpoints<br>
    ///   - [`agent_space_id(impl Into<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::agent_space_id) / [`set_agent_space_id(Option<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::set_agent_space_id):<br>required: **true**<br>ID of the agent space where the pentest job exists<br>
    ///   - [`prefix(impl Into<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::prefix) / [`set_prefix(Option<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::set_prefix):<br>required: **false**<br>Optional URI prefix filter to narrow down results<br>
    ///   - [`next_token(impl Into<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::set_next_token):<br>required: **false**<br>Token for pagination<br>
    /// - On success, responds with [`ListDiscoveredEndpointsOutput`](crate::operation::list_discovered_endpoints::ListDiscoveredEndpointsOutput) with field(s):
    ///   - [`discovered_endpoints(Option<Vec::<DiscoveredEndpoint>>)`](crate::operation::list_discovered_endpoints::ListDiscoveredEndpointsOutput::discovered_endpoints): List of discovered endpoints for the pentest job
    ///   - [`next_token(Option<String>)`](crate::operation::list_discovered_endpoints::ListDiscoveredEndpointsOutput::next_token): Token for pagination to retrieve the next set of results
    /// - On failure, responds with [`SdkError<ListDiscoveredEndpointsError>`](crate::operation::list_discovered_endpoints::ListDiscoveredEndpointsError)
    pub fn list_discovered_endpoints(&self) -> crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder {
        crate::operation::list_discovered_endpoints::builders::ListDiscoveredEndpointsFluentBuilder::new(self.handle.clone())
    }
}
