// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The object describing the provided connectivity from the AWS region to the partner location.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct Connection {
    /// <p>The short identifier of the connection object.</p>
    pub id: ::std::string::String,
    /// <p>An ARN of a <code>Connection</code> object.</p>
    pub arn: ::std::string::String,
    /// <p>A descriptive name for the connection.</p>
    pub description: ::std::string::String,
    /// <p>The specific selected bandwidth of this connection.</p>
    pub bandwidth: ::std::string::String,
    /// <p>The Attach Point to which the connection should be associated."</p>
    pub attach_point: ::std::option::Option<crate::types::AttachPoint>,
    /// <p>The specific <code>Environment</code> this connection is placed upon.</p>
    pub environment_id: ::std::string::String,
    /// <p>The provider on the remote side of this <code>Connection</code>.</p>
    pub provider: ::std::option::Option<crate::types::Provider>,
    /// <p>The provider specific location on the remote side of this <code>Connection</code></p>
    pub location: ::std::string::String,
    /// <p>The specific product type of this <code>Connection</code>.</p>
    pub r#type: ::std::string::String,
    /// <ul>
    /// <li>
    /// <p><code>requested</code>: The initial state of a connection. The state will remain here until the Connection is accepted on the Partner portal.</p></li>
    /// <li>
    /// <p><code>pending</code>: The connection has been accepted and is being provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>available</code>: The connection has been fully provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>deleting</code>: The connection is being deleted.</p></li>
    /// <li>
    /// <p><code>deleted</code>: The connection has been deleted.</p></li>
    /// <li>
    /// <p><code>failed</code>: The connection has failed to be created.</p></li>
    /// <li>
    /// <p><code>updating</code>: The connection is being updated.</p></li>
    /// </ul>
    pub state: crate::types::ConnectionState,
    /// <p>An identifier used by both AWS and the remote partner to identify the specific connection.</p>
    pub shared_id: ::std::string::String,
    /// <p>The billing tier this connection is currently assigned.</p>
    pub billing_tier: ::std::option::Option<i32>,
    /// <p>The account that owns this <code>Connection</code></p>
    pub owner_account: ::std::string::String,
    /// <p>The Activation Key associated to this connection.</p>
    pub activation_key: ::std::string::String,
    /// <p>The tags on the <code>Connection</code></p>
    pub tags: ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>,
}
impl Connection {
    /// <p>The short identifier of the connection object.</p>
    pub fn id(&self) -> &str {
        use std::ops::Deref;
        self.id.deref()
    }
    /// <p>An ARN of a <code>Connection</code> object.</p>
    pub fn arn(&self) -> &str {
        use std::ops::Deref;
        self.arn.deref()
    }
    /// <p>A descriptive name for the connection.</p>
    pub fn description(&self) -> &str {
        use std::ops::Deref;
        self.description.deref()
    }
    /// <p>The specific selected bandwidth of this connection.</p>
    pub fn bandwidth(&self) -> &str {
        use std::ops::Deref;
        self.bandwidth.deref()
    }
    /// <p>The Attach Point to which the connection should be associated."</p>
    pub fn attach_point(&self) -> ::std::option::Option<&crate::types::AttachPoint> {
        self.attach_point.as_ref()
    }
    /// <p>The specific <code>Environment</code> this connection is placed upon.</p>
    pub fn environment_id(&self) -> &str {
        use std::ops::Deref;
        self.environment_id.deref()
    }
    /// <p>The provider on the remote side of this <code>Connection</code>.</p>
    pub fn provider(&self) -> ::std::option::Option<&crate::types::Provider> {
        self.provider.as_ref()
    }
    /// <p>The provider specific location on the remote side of this <code>Connection</code></p>
    pub fn location(&self) -> &str {
        use std::ops::Deref;
        self.location.deref()
    }
    /// <p>The specific product type of this <code>Connection</code>.</p>
    pub fn r#type(&self) -> &str {
        use std::ops::Deref;
        self.r#type.deref()
    }
    /// <ul>
    /// <li>
    /// <p><code>requested</code>: The initial state of a connection. The state will remain here until the Connection is accepted on the Partner portal.</p></li>
    /// <li>
    /// <p><code>pending</code>: The connection has been accepted and is being provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>available</code>: The connection has been fully provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>deleting</code>: The connection is being deleted.</p></li>
    /// <li>
    /// <p><code>deleted</code>: The connection has been deleted.</p></li>
    /// <li>
    /// <p><code>failed</code>: The connection has failed to be created.</p></li>
    /// <li>
    /// <p><code>updating</code>: The connection is being updated.</p></li>
    /// </ul>
    pub fn state(&self) -> &crate::types::ConnectionState {
        &self.state
    }
    /// <p>An identifier used by both AWS and the remote partner to identify the specific connection.</p>
    pub fn shared_id(&self) -> &str {
        use std::ops::Deref;
        self.shared_id.deref()
    }
    /// <p>The billing tier this connection is currently assigned.</p>
    pub fn billing_tier(&self) -> ::std::option::Option<i32> {
        self.billing_tier
    }
    /// <p>The account that owns this <code>Connection</code></p>
    pub fn owner_account(&self) -> &str {
        use std::ops::Deref;
        self.owner_account.deref()
    }
    /// <p>The Activation Key associated to this connection.</p>
    pub fn activation_key(&self) -> &str {
        use std::ops::Deref;
        self.activation_key.deref()
    }
    /// <p>The tags on the <code>Connection</code></p>
    pub fn tags(&self) -> ::std::option::Option<&::std::collections::HashMap<::std::string::String, ::std::string::String>> {
        self.tags.as_ref()
    }
}
impl ::std::fmt::Debug for Connection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("Connection");
        formatter.field("id", &self.id);
        formatter.field("arn", &self.arn);
        formatter.field("description", &self.description);
        formatter.field("bandwidth", &self.bandwidth);
        formatter.field("attach_point", &self.attach_point);
        formatter.field("environment_id", &self.environment_id);
        formatter.field("provider", &self.provider);
        formatter.field("location", &self.location);
        formatter.field("r#type", &self.r#type);
        formatter.field("state", &self.state);
        formatter.field("shared_id", &self.shared_id);
        formatter.field("billing_tier", &self.billing_tier);
        formatter.field("owner_account", &self.owner_account);
        formatter.field("activation_key", &"*** Sensitive Data Redacted ***");
        formatter.field("tags", &self.tags);
        formatter.finish()
    }
}
impl Connection {
    /// Creates a new builder-style object to manufacture [`Connection`](crate::types::Connection).
    pub fn builder() -> crate::types::builders::ConnectionBuilder {
        crate::types::builders::ConnectionBuilder::default()
    }
}

/// A builder for [`Connection`](crate::types::Connection).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct ConnectionBuilder {
    pub(crate) id: ::std::option::Option<::std::string::String>,
    pub(crate) arn: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) bandwidth: ::std::option::Option<::std::string::String>,
    pub(crate) attach_point: ::std::option::Option<crate::types::AttachPoint>,
    pub(crate) environment_id: ::std::option::Option<::std::string::String>,
    pub(crate) provider: ::std::option::Option<crate::types::Provider>,
    pub(crate) location: ::std::option::Option<::std::string::String>,
    pub(crate) r#type: ::std::option::Option<::std::string::String>,
    pub(crate) state: ::std::option::Option<crate::types::ConnectionState>,
    pub(crate) shared_id: ::std::option::Option<::std::string::String>,
    pub(crate) billing_tier: ::std::option::Option<i32>,
    pub(crate) owner_account: ::std::option::Option<::std::string::String>,
    pub(crate) activation_key: ::std::option::Option<::std::string::String>,
    pub(crate) tags: ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>,
}
impl ConnectionBuilder {
    /// <p>The short identifier of the connection object.</p>
    /// This field is required.
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The short identifier of the connection object.</p>
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input;
        self
    }
    /// <p>The short identifier of the connection object.</p>
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }
    /// <p>An ARN of a <code>Connection</code> object.</p>
    /// This field is required.
    pub fn arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>An ARN of a <code>Connection</code> object.</p>
    pub fn set_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.arn = input;
        self
    }
    /// <p>An ARN of a <code>Connection</code> object.</p>
    pub fn get_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.arn
    }
    /// <p>A descriptive name for the connection.</p>
    /// This field is required.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A descriptive name for the connection.</p>
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }
    /// <p>A descriptive name for the connection.</p>
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// <p>The specific selected bandwidth of this connection.</p>
    /// This field is required.
    pub fn bandwidth(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.bandwidth = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The specific selected bandwidth of this connection.</p>
    pub fn set_bandwidth(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.bandwidth = input;
        self
    }
    /// <p>The specific selected bandwidth of this connection.</p>
    pub fn get_bandwidth(&self) -> &::std::option::Option<::std::string::String> {
        &self.bandwidth
    }
    /// <p>The Attach Point to which the connection should be associated."</p>
    /// This field is required.
    pub fn attach_point(mut self, input: crate::types::AttachPoint) -> Self {
        self.attach_point = ::std::option::Option::Some(input);
        self
    }
    /// <p>The Attach Point to which the connection should be associated."</p>
    pub fn set_attach_point(mut self, input: ::std::option::Option<crate::types::AttachPoint>) -> Self {
        self.attach_point = input;
        self
    }
    /// <p>The Attach Point to which the connection should be associated."</p>
    pub fn get_attach_point(&self) -> &::std::option::Option<crate::types::AttachPoint> {
        &self.attach_point
    }
    /// <p>The specific <code>Environment</code> this connection is placed upon.</p>
    /// This field is required.
    pub fn environment_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.environment_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The specific <code>Environment</code> this connection is placed upon.</p>
    pub fn set_environment_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.environment_id = input;
        self
    }
    /// <p>The specific <code>Environment</code> this connection is placed upon.</p>
    pub fn get_environment_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.environment_id
    }
    /// <p>The provider on the remote side of this <code>Connection</code>.</p>
    /// This field is required.
    pub fn provider(mut self, input: crate::types::Provider) -> Self {
        self.provider = ::std::option::Option::Some(input);
        self
    }
    /// <p>The provider on the remote side of this <code>Connection</code>.</p>
    pub fn set_provider(mut self, input: ::std::option::Option<crate::types::Provider>) -> Self {
        self.provider = input;
        self
    }
    /// <p>The provider on the remote side of this <code>Connection</code>.</p>
    pub fn get_provider(&self) -> &::std::option::Option<crate::types::Provider> {
        &self.provider
    }
    /// <p>The provider specific location on the remote side of this <code>Connection</code></p>
    /// This field is required.
    pub fn location(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.location = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The provider specific location on the remote side of this <code>Connection</code></p>
    pub fn set_location(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.location = input;
        self
    }
    /// <p>The provider specific location on the remote side of this <code>Connection</code></p>
    pub fn get_location(&self) -> &::std::option::Option<::std::string::String> {
        &self.location
    }
    /// <p>The specific product type of this <code>Connection</code>.</p>
    /// This field is required.
    pub fn r#type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.r#type = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The specific product type of this <code>Connection</code>.</p>
    pub fn set_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.r#type = input;
        self
    }
    /// <p>The specific product type of this <code>Connection</code>.</p>
    pub fn get_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.r#type
    }
    /// <ul>
    /// <li>
    /// <p><code>requested</code>: The initial state of a connection. The state will remain here until the Connection is accepted on the Partner portal.</p></li>
    /// <li>
    /// <p><code>pending</code>: The connection has been accepted and is being provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>available</code>: The connection has been fully provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>deleting</code>: The connection is being deleted.</p></li>
    /// <li>
    /// <p><code>deleted</code>: The connection has been deleted.</p></li>
    /// <li>
    /// <p><code>failed</code>: The connection has failed to be created.</p></li>
    /// <li>
    /// <p><code>updating</code>: The connection is being updated.</p></li>
    /// </ul>
    /// This field is required.
    pub fn state(mut self, input: crate::types::ConnectionState) -> Self {
        self.state = ::std::option::Option::Some(input);
        self
    }
    /// <ul>
    /// <li>
    /// <p><code>requested</code>: The initial state of a connection. The state will remain here until the Connection is accepted on the Partner portal.</p></li>
    /// <li>
    /// <p><code>pending</code>: The connection has been accepted and is being provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>available</code>: The connection has been fully provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>deleting</code>: The connection is being deleted.</p></li>
    /// <li>
    /// <p><code>deleted</code>: The connection has been deleted.</p></li>
    /// <li>
    /// <p><code>failed</code>: The connection has failed to be created.</p></li>
    /// <li>
    /// <p><code>updating</code>: The connection is being updated.</p></li>
    /// </ul>
    pub fn set_state(mut self, input: ::std::option::Option<crate::types::ConnectionState>) -> Self {
        self.state = input;
        self
    }
    /// <ul>
    /// <li>
    /// <p><code>requested</code>: The initial state of a connection. The state will remain here until the Connection is accepted on the Partner portal.</p></li>
    /// <li>
    /// <p><code>pending</code>: The connection has been accepted and is being provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>available</code>: The connection has been fully provisioned between AWS and the Partner.</p></li>
    /// <li>
    /// <p><code>deleting</code>: The connection is being deleted.</p></li>
    /// <li>
    /// <p><code>deleted</code>: The connection has been deleted.</p></li>
    /// <li>
    /// <p><code>failed</code>: The connection has failed to be created.</p></li>
    /// <li>
    /// <p><code>updating</code>: The connection is being updated.</p></li>
    /// </ul>
    pub fn get_state(&self) -> &::std::option::Option<crate::types::ConnectionState> {
        &self.state
    }
    /// <p>An identifier used by both AWS and the remote partner to identify the specific connection.</p>
    /// This field is required.
    pub fn shared_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.shared_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>An identifier used by both AWS and the remote partner to identify the specific connection.</p>
    pub fn set_shared_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.shared_id = input;
        self
    }
    /// <p>An identifier used by both AWS and the remote partner to identify the specific connection.</p>
    pub fn get_shared_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.shared_id
    }
    /// <p>The billing tier this connection is currently assigned.</p>
    pub fn billing_tier(mut self, input: i32) -> Self {
        self.billing_tier = ::std::option::Option::Some(input);
        self
    }
    /// <p>The billing tier this connection is currently assigned.</p>
    pub fn set_billing_tier(mut self, input: ::std::option::Option<i32>) -> Self {
        self.billing_tier = input;
        self
    }
    /// <p>The billing tier this connection is currently assigned.</p>
    pub fn get_billing_tier(&self) -> &::std::option::Option<i32> {
        &self.billing_tier
    }
    /// <p>The account that owns this <code>Connection</code></p>
    /// This field is required.
    pub fn owner_account(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.owner_account = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The account that owns this <code>Connection</code></p>
    pub fn set_owner_account(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.owner_account = input;
        self
    }
    /// <p>The account that owns this <code>Connection</code></p>
    pub fn get_owner_account(&self) -> &::std::option::Option<::std::string::String> {
        &self.owner_account
    }
    /// <p>The Activation Key associated to this connection.</p>
    /// This field is required.
    pub fn activation_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.activation_key = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Activation Key associated to this connection.</p>
    pub fn set_activation_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.activation_key = input;
        self
    }
    /// <p>The Activation Key associated to this connection.</p>
    pub fn get_activation_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.activation_key
    }
    /// Adds a key-value pair to `tags`.
    ///
    /// To override the contents of this collection use [`set_tags`](Self::set_tags).
    ///
    /// <p>The tags on the <code>Connection</code></p>
    pub fn tags(mut self, k: impl ::std::convert::Into<::std::string::String>, v: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut hash_map = self.tags.unwrap_or_default();
        hash_map.insert(k.into(), v.into());
        self.tags = ::std::option::Option::Some(hash_map);
        self
    }
    /// <p>The tags on the <code>Connection</code></p>
    pub fn set_tags(mut self, input: ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>) -> Self {
        self.tags = input;
        self
    }
    /// <p>The tags on the <code>Connection</code></p>
    pub fn get_tags(&self) -> &::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>> {
        &self.tags
    }
    /// Consumes the builder and constructs a [`Connection`](crate::types::Connection).
    /// This method will fail if any of the following fields are not set:
    /// - [`id`](crate::types::builders::ConnectionBuilder::id)
    /// - [`arn`](crate::types::builders::ConnectionBuilder::arn)
    /// - [`description`](crate::types::builders::ConnectionBuilder::description)
    /// - [`bandwidth`](crate::types::builders::ConnectionBuilder::bandwidth)
    /// - [`environment_id`](crate::types::builders::ConnectionBuilder::environment_id)
    /// - [`location`](crate::types::builders::ConnectionBuilder::location)
    /// - [`r#type`](crate::types::builders::ConnectionBuilder::type)
    /// - [`state`](crate::types::builders::ConnectionBuilder::state)
    /// - [`shared_id`](crate::types::builders::ConnectionBuilder::shared_id)
    /// - [`owner_account`](crate::types::builders::ConnectionBuilder::owner_account)
    /// - [`activation_key`](crate::types::builders::ConnectionBuilder::activation_key)
    pub fn build(self) -> ::std::result::Result<crate::types::Connection, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::Connection {
            id: self.id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "id",
                    "id was not specified but it is required when building Connection",
                )
            })?,
            arn: self.arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "arn",
                    "arn was not specified but it is required when building Connection",
                )
            })?,
            description: self.description.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "description",
                    "description was not specified but it is required when building Connection",
                )
            })?,
            bandwidth: self.bandwidth.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "bandwidth",
                    "bandwidth was not specified but it is required when building Connection",
                )
            })?,
            attach_point: self.attach_point,
            environment_id: self.environment_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "environment_id",
                    "environment_id was not specified but it is required when building Connection",
                )
            })?,
            provider: self.provider,
            location: self.location.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "location",
                    "location was not specified but it is required when building Connection",
                )
            })?,
            r#type: self.r#type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "r#type",
                    "r#type was not specified but it is required when building Connection",
                )
            })?,
            state: self.state.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "state",
                    "state was not specified but it is required when building Connection",
                )
            })?,
            shared_id: self.shared_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "shared_id",
                    "shared_id was not specified but it is required when building Connection",
                )
            })?,
            billing_tier: self.billing_tier,
            owner_account: self.owner_account.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "owner_account",
                    "owner_account was not specified but it is required when building Connection",
                )
            })?,
            activation_key: self.activation_key.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "activation_key",
                    "activation_key was not specified but it is required when building Connection",
                )
            })?,
            tags: self.tags,
        })
    }
}
impl ::std::fmt::Debug for ConnectionBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ConnectionBuilder");
        formatter.field("id", &self.id);
        formatter.field("arn", &self.arn);
        formatter.field("description", &self.description);
        formatter.field("bandwidth", &self.bandwidth);
        formatter.field("attach_point", &self.attach_point);
        formatter.field("environment_id", &self.environment_id);
        formatter.field("provider", &self.provider);
        formatter.field("location", &self.location);
        formatter.field("r#type", &self.r#type);
        formatter.field("state", &self.state);
        formatter.field("shared_id", &self.shared_id);
        formatter.field("billing_tier", &self.billing_tier);
        formatter.field("owner_account", &self.owner_account);
        formatter.field("activation_key", &"*** Sensitive Data Redacted ***");
        formatter.field("tags", &self.tags);
        formatter.finish()
    }
}
