// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct BatchGetStepInput {
    /// <p>The list of step identifiers to retrieve. You can specify up to 100 identifiers per request.</p>
    pub identifiers: ::std::option::Option<::std::vec::Vec<crate::types::BatchGetStepIdentifier>>,
}
impl BatchGetStepInput {
    /// <p>The list of step identifiers to retrieve. You can specify up to 100 identifiers per request.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.identifiers.is_none()`.
    pub fn identifiers(&self) -> &[crate::types::BatchGetStepIdentifier] {
        self.identifiers.as_deref().unwrap_or_default()
    }
}
impl BatchGetStepInput {
    /// Creates a new builder-style object to manufacture [`BatchGetStepInput`](crate::operation::batch_get_step::BatchGetStepInput).
    pub fn builder() -> crate::operation::batch_get_step::builders::BatchGetStepInputBuilder {
        crate::operation::batch_get_step::builders::BatchGetStepInputBuilder::default()
    }
}

/// A builder for [`BatchGetStepInput`](crate::operation::batch_get_step::BatchGetStepInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct BatchGetStepInputBuilder {
    pub(crate) identifiers: ::std::option::Option<::std::vec::Vec<crate::types::BatchGetStepIdentifier>>,
}
impl BatchGetStepInputBuilder {
    /// Appends an item to `identifiers`.
    ///
    /// To override the contents of this collection use [`set_identifiers`](Self::set_identifiers).
    ///
    /// <p>The list of step identifiers to retrieve. You can specify up to 100 identifiers per request.</p>
    pub fn identifiers(mut self, input: crate::types::BatchGetStepIdentifier) -> Self {
        let mut v = self.identifiers.unwrap_or_default();
        v.push(input);
        self.identifiers = ::std::option::Option::Some(v);
        self
    }
    /// <p>The list of step identifiers to retrieve. You can specify up to 100 identifiers per request.</p>
    pub fn set_identifiers(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::BatchGetStepIdentifier>>) -> Self {
        self.identifiers = input;
        self
    }
    /// <p>The list of step identifiers to retrieve. You can specify up to 100 identifiers per request.</p>
    pub fn get_identifiers(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::BatchGetStepIdentifier>> {
        &self.identifiers
    }
    /// Consumes the builder and constructs a [`BatchGetStepInput`](crate::operation::batch_get_step::BatchGetStepInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::batch_get_step::BatchGetStepInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::batch_get_step::BatchGetStepInput {
            identifiers: self.identifiers,
        })
    }
}
