// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Service details for Event Channel integration.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct EventChannelDetails {
    /// The type of event channel
    pub r#type: ::std::option::Option<crate::types::EventChannelType>,
}
impl EventChannelDetails {
    /// The type of event channel
    pub fn r#type(&self) -> ::std::option::Option<&crate::types::EventChannelType> {
        self.r#type.as_ref()
    }
}
impl EventChannelDetails {
    /// Creates a new builder-style object to manufacture [`EventChannelDetails`](crate::types::EventChannelDetails).
    pub fn builder() -> crate::types::builders::EventChannelDetailsBuilder {
        crate::types::builders::EventChannelDetailsBuilder::default()
    }
}

/// A builder for [`EventChannelDetails`](crate::types::EventChannelDetails).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct EventChannelDetailsBuilder {
    pub(crate) r#type: ::std::option::Option<crate::types::EventChannelType>,
}
impl EventChannelDetailsBuilder {
    /// The type of event channel
    pub fn r#type(mut self, input: crate::types::EventChannelType) -> Self {
        self.r#type = ::std::option::Option::Some(input);
        self
    }
    /// The type of event channel
    pub fn set_type(mut self, input: ::std::option::Option<crate::types::EventChannelType>) -> Self {
        self.r#type = input;
        self
    }
    /// The type of event channel
    pub fn get_type(&self) -> &::std::option::Option<crate::types::EventChannelType> {
        &self.r#type
    }
    /// Consumes the builder and constructs a [`EventChannelDetails`](crate::types::EventChannelDetails).
    pub fn build(self) -> crate::types::EventChannelDetails {
        crate::types::EventChannelDetails { r#type: self.r#type }
    }
}
