// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Content of a goal
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GoalContent {
    /// A detailed description of the goal.
    pub description: ::std::string::String,
    /// The objectives to be achieved for this goal.
    pub objectives: ::std::string::String,
}
impl GoalContent {
    /// A detailed description of the goal.
    pub fn description(&self) -> &str {
        use std::ops::Deref;
        self.description.deref()
    }
    /// The objectives to be achieved for this goal.
    pub fn objectives(&self) -> &str {
        use std::ops::Deref;
        self.objectives.deref()
    }
}
impl GoalContent {
    /// Creates a new builder-style object to manufacture [`GoalContent`](crate::types::GoalContent).
    pub fn builder() -> crate::types::builders::GoalContentBuilder {
        crate::types::builders::GoalContentBuilder::default()
    }
}

/// A builder for [`GoalContent`](crate::types::GoalContent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GoalContentBuilder {
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) objectives: ::std::option::Option<::std::string::String>,
}
impl GoalContentBuilder {
    /// A detailed description of the goal.
    /// This field is required.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// A detailed description of the goal.
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }
    /// A detailed description of the goal.
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// The objectives to be achieved for this goal.
    /// This field is required.
    pub fn objectives(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.objectives = ::std::option::Option::Some(input.into());
        self
    }
    /// The objectives to be achieved for this goal.
    pub fn set_objectives(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.objectives = input;
        self
    }
    /// The objectives to be achieved for this goal.
    pub fn get_objectives(&self) -> &::std::option::Option<::std::string::String> {
        &self.objectives
    }
    /// Consumes the builder and constructs a [`GoalContent`](crate::types::GoalContent).
    /// This method will fail if any of the following fields are not set:
    /// - [`description`](crate::types::builders::GoalContentBuilder::description)
    /// - [`objectives`](crate::types::builders::GoalContentBuilder::objectives)
    pub fn build(self) -> ::std::result::Result<crate::types::GoalContent, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::GoalContent {
            description: self.description.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "description",
                    "description was not specified but it is required when building GoalContent",
                )
            })?,
            objectives: self.objectives.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "objectives",
                    "objectives was not specified but it is required when building GoalContent",
                )
            })?,
        })
    }
}
