// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Details specific to a registered SigV4-authenticated MCP server.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct RegisteredMcpServerSigV4Details {
    /// MCP server name.
    pub name: ::std::string::String,
    /// MCP server endpoint URL.
    pub endpoint: ::std::string::String,
    /// Optional description for the MCP server.
    pub description: ::std::option::Option<::std::string::String>,
    /// AWS region for SigV4 signing.
    pub region: ::std::string::String,
    /// AWS service name for SigV4 signing.
    pub service: ::std::string::String,
    /// IAM role ARN to assume for SigV4 signing.
    pub role_arn: ::std::string::String,
}
impl RegisteredMcpServerSigV4Details {
    /// MCP server name.
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
    /// MCP server endpoint URL.
    pub fn endpoint(&self) -> &str {
        use std::ops::Deref;
        self.endpoint.deref()
    }
    /// Optional description for the MCP server.
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    /// AWS region for SigV4 signing.
    pub fn region(&self) -> &str {
        use std::ops::Deref;
        self.region.deref()
    }
    /// AWS service name for SigV4 signing.
    pub fn service(&self) -> &str {
        use std::ops::Deref;
        self.service.deref()
    }
    /// IAM role ARN to assume for SigV4 signing.
    pub fn role_arn(&self) -> &str {
        use std::ops::Deref;
        self.role_arn.deref()
    }
}
impl ::std::fmt::Debug for RegisteredMcpServerSigV4Details {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("RegisteredMcpServerSigV4Details");
        formatter.field("name", &self.name);
        formatter.field("endpoint", &self.endpoint);
        formatter.field("description", &"*** Sensitive Data Redacted ***");
        formatter.field("region", &self.region);
        formatter.field("service", &self.service);
        formatter.field("role_arn", &self.role_arn);
        formatter.finish()
    }
}
impl RegisteredMcpServerSigV4Details {
    /// Creates a new builder-style object to manufacture [`RegisteredMcpServerSigV4Details`](crate::types::RegisteredMcpServerSigV4Details).
    pub fn builder() -> crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder {
        crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::default()
    }
}

/// A builder for [`RegisteredMcpServerSigV4Details`](crate::types::RegisteredMcpServerSigV4Details).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct RegisteredMcpServerSigV4DetailsBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) region: ::std::option::Option<::std::string::String>,
    pub(crate) service: ::std::option::Option<::std::string::String>,
    pub(crate) role_arn: ::std::option::Option<::std::string::String>,
}
impl RegisteredMcpServerSigV4DetailsBuilder {
    /// MCP server name.
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// MCP server name.
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// MCP server name.
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// MCP server endpoint URL.
    /// This field is required.
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    /// MCP server endpoint URL.
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input;
        self
    }
    /// MCP server endpoint URL.
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    /// Optional description for the MCP server.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// Optional description for the MCP server.
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }
    /// Optional description for the MCP server.
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// AWS region for SigV4 signing.
    /// This field is required.
    pub fn region(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.region = ::std::option::Option::Some(input.into());
        self
    }
    /// AWS region for SigV4 signing.
    pub fn set_region(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.region = input;
        self
    }
    /// AWS region for SigV4 signing.
    pub fn get_region(&self) -> &::std::option::Option<::std::string::String> {
        &self.region
    }
    /// AWS service name for SigV4 signing.
    /// This field is required.
    pub fn service(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.service = ::std::option::Option::Some(input.into());
        self
    }
    /// AWS service name for SigV4 signing.
    pub fn set_service(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.service = input;
        self
    }
    /// AWS service name for SigV4 signing.
    pub fn get_service(&self) -> &::std::option::Option<::std::string::String> {
        &self.service
    }
    /// IAM role ARN to assume for SigV4 signing.
    /// This field is required.
    pub fn role_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.role_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// IAM role ARN to assume for SigV4 signing.
    pub fn set_role_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.role_arn = input;
        self
    }
    /// IAM role ARN to assume for SigV4 signing.
    pub fn get_role_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.role_arn
    }
    /// Consumes the builder and constructs a [`RegisteredMcpServerSigV4Details`](crate::types::RegisteredMcpServerSigV4Details).
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::name)
    /// - [`endpoint`](crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::endpoint)
    /// - [`region`](crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::region)
    /// - [`service`](crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::service)
    /// - [`role_arn`](crate::types::builders::RegisteredMcpServerSigV4DetailsBuilder::role_arn)
    pub fn build(self) -> ::std::result::Result<crate::types::RegisteredMcpServerSigV4Details, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::RegisteredMcpServerSigV4Details {
            name: self.name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "name",
                    "name was not specified but it is required when building RegisteredMcpServerSigV4Details",
                )
            })?,
            endpoint: self.endpoint.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "endpoint",
                    "endpoint was not specified but it is required when building RegisteredMcpServerSigV4Details",
                )
            })?,
            description: self.description,
            region: self.region.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "region",
                    "region was not specified but it is required when building RegisteredMcpServerSigV4Details",
                )
            })?,
            service: self.service.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "service",
                    "service was not specified but it is required when building RegisteredMcpServerSigV4Details",
                )
            })?,
            role_arn: self.role_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "role_arn",
                    "role_arn was not specified but it is required when building RegisteredMcpServerSigV4Details",
                )
            })?,
        })
    }
}
impl ::std::fmt::Debug for RegisteredMcpServerSigV4DetailsBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("RegisteredMcpServerSigV4DetailsBuilder");
        formatter.field("name", &self.name);
        formatter.field("endpoint", &self.endpoint);
        formatter.field("description", &"*** Sensitive Data Redacted ***");
        formatter.field("region", &self.region);
        formatter.field("service", &self.service);
        formatter.field("role_arn", &self.role_arn);
        formatter.finish()
    }
}
