// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_connection_input_input(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::operation::update_connection::UpdateConnectionInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    encoder.begin_map();
    if let Some(var_1) = &input.identifier {
        encoder.str("identifier").str(var_1.as_str());
    }
    if let Some(var_2) = &input.description {
        encoder.str("description").str(var_2.as_str());
    }
    if let Some(var_3) = &input.bandwidth {
        encoder.str("bandwidth").str(var_3.as_str());
    }
    if let Some(var_4) = &input.client_token {
        encoder.str("clientToken").str(var_4.as_str());
    }
    encoder.end();
    Ok(())
}
