// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::update_data_automation_library::_update_data_automation_library_input::UpdateDataAutomationLibraryInputBuilder;

pub use crate::operation::update_data_automation_library::_update_data_automation_library_output::UpdateDataAutomationLibraryOutputBuilder;

impl crate::operation::update_data_automation_library::builders::UpdateDataAutomationLibraryInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::update_data_automation_library::UpdateDataAutomationLibraryError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let mut fluent_builder = client.update_data_automation_library();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `UpdateDataAutomationLibrary`.
///
/// Updates an existing Amazon Bedrock Data Automation Library
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct UpdateDataAutomationLibraryFluentBuilder {
    handle: ::std::sync::Arc<crate::client::Handle>,
    inner: crate::operation::update_data_automation_library::builders::UpdateDataAutomationLibraryInputBuilder,
    config_override: ::std::option::Option<crate::config::Builder>,
}
impl
    crate::client::customize::internal::CustomizableSend<
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryOutput,
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryError,
    > for UpdateDataAutomationLibraryFluentBuilder
{
    fn send(
        self,
        config_override: crate::config::Builder,
    ) -> crate::client::customize::internal::BoxFuture<
        crate::client::customize::internal::SendResult<
            crate::operation::update_data_automation_library::UpdateDataAutomationLibraryOutput,
            crate::operation::update_data_automation_library::UpdateDataAutomationLibraryError,
        >,
    > {
        ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
    }
}
impl UpdateDataAutomationLibraryFluentBuilder {
    /// Creates a new `UpdateDataAutomationLibraryFluentBuilder`.
    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
        Self {
            handle,
            inner: ::std::default::Default::default(),
            config_override: ::std::option::Option::None,
        }
    }
    /// Access the UpdateDataAutomationLibrary as a reference.
    pub fn as_input(&self) -> &crate::operation::update_data_automation_library::builders::UpdateDataAutomationLibraryInputBuilder {
        &self.inner
    }
    /// Sends the request and returns the response.
    ///
    /// If an error occurs, an `SdkError` will be returned with additional details that
    /// can be matched against.
    ///
    /// By default, any retryable failures will be retried twice. Retry behavior
    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
    /// set when configuring the client.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::update_data_automation_library::UpdateDataAutomationLibraryError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let input = self
            .inner
            .build()
            .map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
        let runtime_plugins = crate::operation::update_data_automation_library::UpdateDataAutomationLibrary::operation_runtime_plugins(
            self.handle.runtime_plugins.clone(),
            &self.handle.conf,
            self.config_override,
        );
        crate::operation::update_data_automation_library::UpdateDataAutomationLibrary::orchestrate(&runtime_plugins, input).await
    }

    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
    pub fn customize(
        self,
    ) -> crate::client::customize::CustomizableOperation<
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryOutput,
        crate::operation::update_data_automation_library::UpdateDataAutomationLibraryError,
        Self,
    > {
        crate::client::customize::CustomizableOperation::new(self)
    }
    pub(crate) fn config_override(mut self, config_override: impl ::std::convert::Into<crate::config::Builder>) -> Self {
        self.set_config_override(::std::option::Option::Some(config_override.into()));
        self
    }

    pub(crate) fn set_config_override(&mut self, config_override: ::std::option::Option<crate::config::Builder>) -> &mut Self {
        self.config_override = config_override;
        self
    }
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn library_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.library_arn(input.into());
        self
    }
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn set_library_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_library_arn(input);
        self
    }
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn get_library_arn(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_library_arn()
    }
    /// Description of the DataAutomationLibrary
    pub fn library_description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.library_description(input.into());
        self
    }
    /// Description of the DataAutomationLibrary
    pub fn set_library_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_library_description(input);
        self
    }
    /// Description of the DataAutomationLibrary
    pub fn get_library_description(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_library_description()
    }
    /// Client specified token used for idempotency checks
    pub fn client_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.client_token(input.into());
        self
    }
    /// Client specified token used for idempotency checks
    pub fn set_client_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_client_token(input);
        self
    }
    /// Client specified token used for idempotency checks
    pub fn get_client_token(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_client_token()
    }
}
