// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// List DataAutomationLibraryIngestionJobs Request
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListDataAutomationLibraryIngestionJobsInput {
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub library_arn: ::std::option::Option<::std::string::String>,
    /// Max Results
    pub max_results: ::std::option::Option<i32>,
    /// Pagination token for retrieving the next set of results
    pub next_token: ::std::option::Option<::std::string::String>,
}
impl ListDataAutomationLibraryIngestionJobsInput {
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn library_arn(&self) -> ::std::option::Option<&str> {
        self.library_arn.as_deref()
    }
    /// Max Results
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
    /// Pagination token for retrieving the next set of results
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ListDataAutomationLibraryIngestionJobsInput {
    /// Creates a new builder-style object to manufacture [`ListDataAutomationLibraryIngestionJobsInput`](crate::operation::list_data_automation_library_ingestion_jobs::ListDataAutomationLibraryIngestionJobsInput).
    pub fn builder() -> crate::operation::list_data_automation_library_ingestion_jobs::builders::ListDataAutomationLibraryIngestionJobsInputBuilder {
        crate::operation::list_data_automation_library_ingestion_jobs::builders::ListDataAutomationLibraryIngestionJobsInputBuilder::default()
    }
}

/// A builder for [`ListDataAutomationLibraryIngestionJobsInput`](crate::operation::list_data_automation_library_ingestion_jobs::ListDataAutomationLibraryIngestionJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListDataAutomationLibraryIngestionJobsInputBuilder {
    pub(crate) library_arn: ::std::option::Option<::std::string::String>,
    pub(crate) max_results: ::std::option::Option<i32>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
}
impl ListDataAutomationLibraryIngestionJobsInputBuilder {
    /// ARN generated at the server side when a DataAutomationLibrary is created
    /// This field is required.
    pub fn library_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.library_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn set_library_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.library_arn = input;
        self
    }
    /// ARN generated at the server side when a DataAutomationLibrary is created
    pub fn get_library_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.library_arn
    }
    /// Max Results
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// Max Results
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// Max Results
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// Pagination token for retrieving the next set of results
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// Pagination token for retrieving the next set of results
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// Pagination token for retrieving the next set of results
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// Consumes the builder and constructs a [`ListDataAutomationLibraryIngestionJobsInput`](crate::operation::list_data_automation_library_ingestion_jobs::ListDataAutomationLibraryIngestionJobsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::list_data_automation_library_ingestion_jobs::ListDataAutomationLibraryIngestionJobsInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::list_data_automation_library_ingestion_jobs::ListDataAutomationLibraryIngestionJobsInput {
                library_arn: self.library_arn,
                max_results: self.max_results,
                next_token: self.next_token,
            },
        )
    }
}
