// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The result of a <code>ListInsights</code> request. Contains the list of insights and a pagination token for retrieving the next page of results.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListInsightsOutput {
    /// <p>The list of insights returned for the specified entity.</p>
    pub insights: ::std::option::Option<::std::vec::Vec<crate::types::Insight>>,
    /// <p>When <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Send the request again using the returned token to retrieve the next page.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListInsightsOutput {
    /// <p>The list of insights returned for the specified entity.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.insights.is_none()`.
    pub fn insights(&self) -> &[crate::types::Insight] {
        self.insights.as_deref().unwrap_or_default()
    }
    /// <p>When <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Send the request again using the returned token to retrieve the next page.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ::aws_types::request_id::RequestId for ListInsightsOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl ListInsightsOutput {
    /// Creates a new builder-style object to manufacture [`ListInsightsOutput`](crate::operation::list_insights::ListInsightsOutput).
    pub fn builder() -> crate::operation::list_insights::builders::ListInsightsOutputBuilder {
        crate::operation::list_insights::builders::ListInsightsOutputBuilder::default()
    }
}

/// A builder for [`ListInsightsOutput`](crate::operation::list_insights::ListInsightsOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListInsightsOutputBuilder {
    pub(crate) insights: ::std::option::Option<::std::vec::Vec<crate::types::Insight>>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListInsightsOutputBuilder {
    /// Appends an item to `insights`.
    ///
    /// To override the contents of this collection use [`set_insights`](Self::set_insights).
    ///
    /// <p>The list of insights returned for the specified entity.</p>
    pub fn insights(mut self, input: crate::types::Insight) -> Self {
        let mut v = self.insights.unwrap_or_default();
        v.push(input);
        self.insights = ::std::option::Option::Some(v);
        self
    }
    /// <p>The list of insights returned for the specified entity.</p>
    pub fn set_insights(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Insight>>) -> Self {
        self.insights = input;
        self
    }
    /// <p>The list of insights returned for the specified entity.</p>
    pub fn get_insights(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Insight>> {
        &self.insights
    }
    /// <p>When <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Send the request again using the returned token to retrieve the next page.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>When <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Send the request again using the returned token to retrieve the next page.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>When <code>NextToken</code> is returned, there are more results available. The value of <code>NextToken</code> is a unique pagination token for each page. Send the request again using the returned token to retrieve the next page.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`ListInsightsOutput`](crate::operation::list_insights::ListInsightsOutput).
    pub fn build(self) -> crate::operation::list_insights::ListInsightsOutput {
        crate::operation::list_insights::ListInsightsOutput {
            insights: self.insights,
            next_token: self.next_token,
            _request_id: self._request_id,
        }
    }
}
