// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListAttachPointsOutput {
    /// <p>The valid <code>AttachPoint</code></p>
    pub attach_points: ::std::vec::Vec<crate::types::AttachPointDescriptor>,
    /// <p>A pagination token indicating that there are more results that can be fetched.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListAttachPointsOutput {
    /// <p>The valid <code>AttachPoint</code></p>
    pub fn attach_points(&self) -> &[crate::types::AttachPointDescriptor] {
        use std::ops::Deref;
        self.attach_points.deref()
    }
    /// <p>A pagination token indicating that there are more results that can be fetched.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ::aws_types::request_id::RequestId for ListAttachPointsOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl ListAttachPointsOutput {
    /// Creates a new builder-style object to manufacture [`ListAttachPointsOutput`](crate::operation::list_attach_points::ListAttachPointsOutput).
    pub fn builder() -> crate::operation::list_attach_points::builders::ListAttachPointsOutputBuilder {
        crate::operation::list_attach_points::builders::ListAttachPointsOutputBuilder::default()
    }
}

/// A builder for [`ListAttachPointsOutput`](crate::operation::list_attach_points::ListAttachPointsOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListAttachPointsOutputBuilder {
    pub(crate) attach_points: ::std::option::Option<::std::vec::Vec<crate::types::AttachPointDescriptor>>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl ListAttachPointsOutputBuilder {
    /// Appends an item to `attach_points`.
    ///
    /// To override the contents of this collection use [`set_attach_points`](Self::set_attach_points).
    ///
    /// <p>The valid <code>AttachPoint</code></p>
    pub fn attach_points(mut self, input: crate::types::AttachPointDescriptor) -> Self {
        let mut v = self.attach_points.unwrap_or_default();
        v.push(input);
        self.attach_points = ::std::option::Option::Some(v);
        self
    }
    /// <p>The valid <code>AttachPoint</code></p>
    pub fn set_attach_points(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::AttachPointDescriptor>>) -> Self {
        self.attach_points = input;
        self
    }
    /// <p>The valid <code>AttachPoint</code></p>
    pub fn get_attach_points(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::AttachPointDescriptor>> {
        &self.attach_points
    }
    /// <p>A pagination token indicating that there are more results that can be fetched.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A pagination token indicating that there are more results that can be fetched.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>A pagination token indicating that there are more results that can be fetched.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`ListAttachPointsOutput`](crate::operation::list_attach_points::ListAttachPointsOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`attach_points`](crate::operation::list_attach_points::builders::ListAttachPointsOutputBuilder::attach_points)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::list_attach_points::ListAttachPointsOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::list_attach_points::ListAttachPointsOutput {
            attach_points: self.attach_points.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "attach_points",
                    "attach_points was not specified but it is required when building ListAttachPointsOutput",
                )
            })?,
            next_token: self.next_token,
            _request_id: self._request_id,
        })
    }
}
