// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListMountTargets`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder) operation.
    /// This operation supports pagination; See [`into_paginator()`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::into_paginator).
    ///
    /// - The fluent builder is configurable:
    ///   - [`file_system_id(impl Into<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::file_system_id) / [`set_file_system_id(Option<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::set_file_system_id):<br>required: **false**<br><p>Optional filter to list only mount targets associated with the specified S3 File System ID or Amazon Resource Name (ARN). If provided, only mount targets for this file system will be returned in the response.</p><br>
    ///   - [`access_point_id(impl Into<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::access_point_id) / [`set_access_point_id(Option<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::set_access_point_id):<br>required: **false**<br><p>Optional filter to list only mount targets associated with the specified access point ID or Amazon Resource Name (ARN).</p><br>
    ///   - [`max_results(i32)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::set_max_results):<br>required: **false**<br><p>The maximum number of mount targets to return in a single response.</p><br>
    ///   - [`next_token(impl Into<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::set_next_token):<br>required: **false**<br><p>A pagination token returned from a previous call to continue listing mount targets.</p><br>
    /// - On success, responds with [`ListMountTargetsOutput`](crate::operation::list_mount_targets::ListMountTargetsOutput) with field(s):
    ///   - [`next_token(Option<String>)`](crate::operation::list_mount_targets::ListMountTargetsOutput::next_token): <p>A pagination token to use in a subsequent request if more results are available.</p>
    ///   - [`mount_targets(Vec::<ListMountTargetsDescription>)`](crate::operation::list_mount_targets::ListMountTargetsOutput::mount_targets): <p>An array of mount target descriptions.</p>
    /// - On failure, responds with [`SdkError<ListMountTargetsError>`](crate::operation::list_mount_targets::ListMountTargetsError)
    pub fn list_mount_targets(&self) -> crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder {
        crate::operation::list_mount_targets::builders::ListMountTargetsFluentBuilder::new(self.handle.clone())
    }
}
