// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PutFileSystemPolicy`](crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`file_system_id(impl Into<String>)`](crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder::file_system_id) / [`set_file_system_id(Option<String>)`](crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder::set_file_system_id):<br>required: **true**<br><p>The ID or Amazon Resource Name (ARN) of the S3 File System to apply the resource policy to.</p><br>
    ///   - [`policy(impl Into<String>)`](crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder::policy) / [`set_policy(Option<String>)`](crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder::set_policy):<br>required: **true**<br><p>The JSON-formatted resource policy to apply to the file system. The policy defines the permissions for accessing the file system. The policy must be a valid JSON document that follows IAM policy syntax.</p><br>
    /// - On success, responds with [`PutFileSystemPolicyOutput`](crate::operation::put_file_system_policy::PutFileSystemPolicyOutput)
    /// - On failure, responds with [`SdkError<PutFileSystemPolicyError>`](crate::operation::put_file_system_policy::PutFileSystemPolicyError)
    pub fn put_file_system_policy(&self) -> crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder {
        crate::operation::put_file_system_policy::builders::PutFileSystemPolicyFluentBuilder::new(self.handle.clone())
    }
}
