// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DescribeRcsAgentCountryLaunchStatusInput {
    /// <p>The unique identifier of the RCS agent. You can use either the RcsAgentId or RcsAgentArn.</p>
    pub rcs_agent_id: ::std::option::Option<::std::string::String>,
    /// <p>An array of two-character ISO country codes, in ISO 3166-1 alpha-2 format, to filter the results.</p>
    pub iso_country_codes: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>An array of CountryLaunchStatusFilter objects to filter the results.</p>
    pub filters: ::std::option::Option<::std::vec::Vec<crate::types::CountryLaunchStatusFilter>>,
    /// <p>The maximum number of results to return per each request.</p>
    pub max_results: ::std::option::Option<i32>,
    /// <p>The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
}
impl DescribeRcsAgentCountryLaunchStatusInput {
    /// <p>The unique identifier of the RCS agent. You can use either the RcsAgentId or RcsAgentArn.</p>
    pub fn rcs_agent_id(&self) -> ::std::option::Option<&str> {
        self.rcs_agent_id.as_deref()
    }
    /// <p>An array of two-character ISO country codes, in ISO 3166-1 alpha-2 format, to filter the results.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.iso_country_codes.is_none()`.
    pub fn iso_country_codes(&self) -> &[::std::string::String] {
        self.iso_country_codes.as_deref().unwrap_or_default()
    }
    /// <p>An array of CountryLaunchStatusFilter objects to filter the results.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.filters.is_none()`.
    pub fn filters(&self) -> &[crate::types::CountryLaunchStatusFilter] {
        self.filters.as_deref().unwrap_or_default()
    }
    /// <p>The maximum number of results to return per each request.</p>
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
    /// <p>The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl DescribeRcsAgentCountryLaunchStatusInput {
    /// Creates a new builder-style object to manufacture [`DescribeRcsAgentCountryLaunchStatusInput`](crate::operation::describe_rcs_agent_country_launch_status::DescribeRcsAgentCountryLaunchStatusInput).
    pub fn builder() -> crate::operation::describe_rcs_agent_country_launch_status::builders::DescribeRcsAgentCountryLaunchStatusInputBuilder {
        crate::operation::describe_rcs_agent_country_launch_status::builders::DescribeRcsAgentCountryLaunchStatusInputBuilder::default()
    }
}

/// A builder for [`DescribeRcsAgentCountryLaunchStatusInput`](crate::operation::describe_rcs_agent_country_launch_status::DescribeRcsAgentCountryLaunchStatusInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DescribeRcsAgentCountryLaunchStatusInputBuilder {
    pub(crate) rcs_agent_id: ::std::option::Option<::std::string::String>,
    pub(crate) iso_country_codes: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) filters: ::std::option::Option<::std::vec::Vec<crate::types::CountryLaunchStatusFilter>>,
    pub(crate) max_results: ::std::option::Option<i32>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
}
impl DescribeRcsAgentCountryLaunchStatusInputBuilder {
    /// <p>The unique identifier of the RCS agent. You can use either the RcsAgentId or RcsAgentArn.</p>
    /// This field is required.
    pub fn rcs_agent_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.rcs_agent_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the RCS agent. You can use either the RcsAgentId or RcsAgentArn.</p>
    pub fn set_rcs_agent_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.rcs_agent_id = input;
        self
    }
    /// <p>The unique identifier of the RCS agent. You can use either the RcsAgentId or RcsAgentArn.</p>
    pub fn get_rcs_agent_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.rcs_agent_id
    }
    /// Appends an item to `iso_country_codes`.
    ///
    /// To override the contents of this collection use [`set_iso_country_codes`](Self::set_iso_country_codes).
    ///
    /// <p>An array of two-character ISO country codes, in ISO 3166-1 alpha-2 format, to filter the results.</p>
    pub fn iso_country_codes(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.iso_country_codes.unwrap_or_default();
        v.push(input.into());
        self.iso_country_codes = ::std::option::Option::Some(v);
        self
    }
    /// <p>An array of two-character ISO country codes, in ISO 3166-1 alpha-2 format, to filter the results.</p>
    pub fn set_iso_country_codes(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.iso_country_codes = input;
        self
    }
    /// <p>An array of two-character ISO country codes, in ISO 3166-1 alpha-2 format, to filter the results.</p>
    pub fn get_iso_country_codes(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.iso_country_codes
    }
    /// Appends an item to `filters`.
    ///
    /// To override the contents of this collection use [`set_filters`](Self::set_filters).
    ///
    /// <p>An array of CountryLaunchStatusFilter objects to filter the results.</p>
    pub fn filters(mut self, input: crate::types::CountryLaunchStatusFilter) -> Self {
        let mut v = self.filters.unwrap_or_default();
        v.push(input);
        self.filters = ::std::option::Option::Some(v);
        self
    }
    /// <p>An array of CountryLaunchStatusFilter objects to filter the results.</p>
    pub fn set_filters(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::CountryLaunchStatusFilter>>) -> Self {
        self.filters = input;
        self
    }
    /// <p>An array of CountryLaunchStatusFilter objects to filter the results.</p>
    pub fn get_filters(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::CountryLaunchStatusFilter>> {
        &self.filters
    }
    /// <p>The maximum number of results to return per each request.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// <p>The maximum number of results to return per each request.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// <p>The maximum number of results to return per each request.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// <p>The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// Consumes the builder and constructs a [`DescribeRcsAgentCountryLaunchStatusInput`](crate::operation::describe_rcs_agent_country_launch_status::DescribeRcsAgentCountryLaunchStatusInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::describe_rcs_agent_country_launch_status::DescribeRcsAgentCountryLaunchStatusInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::describe_rcs_agent_country_launch_status::DescribeRcsAgentCountryLaunchStatusInput {
                rcs_agent_id: self.rcs_agent_id,
                iso_country_codes: self.iso_country_codes,
                filters: self.filters,
                max_results: self.max_results,
                next_token: self.next_token,
            },
        )
    }
}
