// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Configuration for bidirectional URL redirection between the streaming session and the local client. Use HostToClient to redirect URLs from the remote desktop to the local browser.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContentRedirection {
    /// <p>Configuration for redirecting URLs from the remote desktop to the local client browser.</p>
    pub host_to_client: ::std::option::Option<crate::types::UrlRedirectionConfig>,
}
impl ContentRedirection {
    /// <p>Configuration for redirecting URLs from the remote desktop to the local client browser.</p>
    pub fn host_to_client(&self) -> ::std::option::Option<&crate::types::UrlRedirectionConfig> {
        self.host_to_client.as_ref()
    }
}
impl ContentRedirection {
    /// Creates a new builder-style object to manufacture [`ContentRedirection`](crate::types::ContentRedirection).
    pub fn builder() -> crate::types::builders::ContentRedirectionBuilder {
        crate::types::builders::ContentRedirectionBuilder::default()
    }
}

/// A builder for [`ContentRedirection`](crate::types::ContentRedirection).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContentRedirectionBuilder {
    pub(crate) host_to_client: ::std::option::Option<crate::types::UrlRedirectionConfig>,
}
impl ContentRedirectionBuilder {
    /// <p>Configuration for redirecting URLs from the remote desktop to the local client browser.</p>
    pub fn host_to_client(mut self, input: crate::types::UrlRedirectionConfig) -> Self {
        self.host_to_client = ::std::option::Option::Some(input);
        self
    }
    /// <p>Configuration for redirecting URLs from the remote desktop to the local client browser.</p>
    pub fn set_host_to_client(mut self, input: ::std::option::Option<crate::types::UrlRedirectionConfig>) -> Self {
        self.host_to_client = input;
        self
    }
    /// <p>Configuration for redirecting URLs from the remote desktop to the local client browser.</p>
    pub fn get_host_to_client(&self) -> &::std::option::Option<crate::types::UrlRedirectionConfig> {
        &self.host_to_client
    }
    /// Consumes the builder and constructs a [`ContentRedirection`](crate::types::ContentRedirection).
    pub fn build(self) -> crate::types::ContentRedirection {
        crate::types::ContentRedirection {
            host_to_client: self.host_to_client,
        }
    }
}
