// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Represents the updated content of a <code>Custom</code> related item.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CustomUpdateContent {
    /// <p>List of updated field values for the <code>Custom</code> related item. All existing and new fields, and their associated values should be included. Fields not included as part of this request will be removed.</p>
    pub fields: ::std::vec::Vec<crate::types::FieldValue>,
}
impl CustomUpdateContent {
    /// <p>List of updated field values for the <code>Custom</code> related item. All existing and new fields, and their associated values should be included. Fields not included as part of this request will be removed.</p>
    pub fn fields(&self) -> &[crate::types::FieldValue] {
        use std::ops::Deref;
        self.fields.deref()
    }
}
impl CustomUpdateContent {
    /// Creates a new builder-style object to manufacture [`CustomUpdateContent`](crate::types::CustomUpdateContent).
    pub fn builder() -> crate::types::builders::CustomUpdateContentBuilder {
        crate::types::builders::CustomUpdateContentBuilder::default()
    }
}

/// A builder for [`CustomUpdateContent`](crate::types::CustomUpdateContent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CustomUpdateContentBuilder {
    pub(crate) fields: ::std::option::Option<::std::vec::Vec<crate::types::FieldValue>>,
}
impl CustomUpdateContentBuilder {
    /// Appends an item to `fields`.
    ///
    /// To override the contents of this collection use [`set_fields`](Self::set_fields).
    ///
    /// <p>List of updated field values for the <code>Custom</code> related item. All existing and new fields, and their associated values should be included. Fields not included as part of this request will be removed.</p>
    pub fn fields(mut self, input: crate::types::FieldValue) -> Self {
        let mut v = self.fields.unwrap_or_default();
        v.push(input);
        self.fields = ::std::option::Option::Some(v);
        self
    }
    /// <p>List of updated field values for the <code>Custom</code> related item. All existing and new fields, and their associated values should be included. Fields not included as part of this request will be removed.</p>
    pub fn set_fields(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::FieldValue>>) -> Self {
        self.fields = input;
        self
    }
    /// <p>List of updated field values for the <code>Custom</code> related item. All existing and new fields, and their associated values should be included. Fields not included as part of this request will be removed.</p>
    pub fn get_fields(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::FieldValue>> {
        &self.fields
    }
    /// Consumes the builder and constructs a [`CustomUpdateContent`](crate::types::CustomUpdateContent).
    /// This method will fail if any of the following fields are not set:
    /// - [`fields`](crate::types::builders::CustomUpdateContentBuilder::fields)
    pub fn build(self) -> ::std::result::Result<crate::types::CustomUpdateContent, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::CustomUpdateContent {
            fields: self.fields.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "fields",
                    "fields was not specified but it is required when building CustomUpdateContent",
                )
            })?,
        })
    }
}
