// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When writing a match expression against `BillingAdjustmentReasonCode`, it is important to ensure
/// your code is forward-compatible. That is, if a match arm handles a case for a
/// feature that is supported by the service but has not been represented as an enum
/// variant in a current version of SDK, your code should continue to work when you
/// upgrade SDK to a future version in which the enum does include a variant for that
/// feature.
///
/// Here is an example of how you can make a match expression forward-compatible:
///
/// ```text
/// # let billingadjustmentreasoncode = unimplemented!();
/// match billingadjustmentreasoncode {
///     BillingAdjustmentReasonCode::AlternativeProcurementChannel => { /* ... */ },
///     BillingAdjustmentReasonCode::BuyerDissatisfaction => { /* ... */ },
///     BillingAdjustmentReasonCode::IncorrectMetering => { /* ... */ },
///     BillingAdjustmentReasonCode::IncorrectTermsAccepted => { /* ... */ },
///     BillingAdjustmentReasonCode::Other => { /* ... */ },
///     BillingAdjustmentReasonCode::TestEnvironmentCharges => { /* ... */ },
///     BillingAdjustmentReasonCode::UnintendedRenewal => { /* ... */ },
///     other @ _ if other.as_str() == "NewFeature" => { /* handles a case for `NewFeature` */ },
///     _ => { /* ... */ },
/// }
/// ```
/// The above code demonstrates that when `billingadjustmentreasoncode` represents
/// `NewFeature`, the execution path will lead to the second last match arm,
/// even though the enum does not contain a variant `BillingAdjustmentReasonCode::NewFeature`
/// in the current version of SDK. The reason is that the variable `other`,
/// created by the `@` operator, is bound to
/// `BillingAdjustmentReasonCode::Unknown(UnknownVariantValue("NewFeature".to_owned()))`
/// and calling `as_str` on it yields `"NewFeature"`.
/// This match expression is forward-compatible when executed with a newer
/// version of SDK where the variant `BillingAdjustmentReasonCode::NewFeature` is defined.
/// Specifically, when `billingadjustmentreasoncode` represents `NewFeature`,
/// the execution path will hit the second last match arm as before by virtue of
/// calling `as_str` on `BillingAdjustmentReasonCode::NewFeature` also yielding `"NewFeature"`.
///
/// Explicitly matching on the `Unknown` variant should
/// be avoided for two reasons:
/// - The inner data `UnknownVariantValue` is opaque, and no further information can be extracted.
/// - It might inadvertently shadow other intended match arms.
///
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::Ord, ::std::cmp::PartialEq, ::std::cmp::PartialOrd, ::std::fmt::Debug, ::std::hash::Hash,
)]
pub enum BillingAdjustmentReasonCode {
    #[allow(missing_docs)] // documentation missing in model
    AlternativeProcurementChannel,
    #[allow(missing_docs)] // documentation missing in model
    BuyerDissatisfaction,
    #[allow(missing_docs)] // documentation missing in model
    IncorrectMetering,
    #[allow(missing_docs)] // documentation missing in model
    IncorrectTermsAccepted,
    #[allow(missing_docs)] // documentation missing in model
    Other,
    #[allow(missing_docs)] // documentation missing in model
    TestEnvironmentCharges,
    #[allow(missing_docs)] // documentation missing in model
    UnintendedRenewal,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants.")]
    Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for BillingAdjustmentReasonCode {
    fn from(s: &str) -> Self {
        match s {
            "ALTERNATIVE_PROCUREMENT_CHANNEL" => BillingAdjustmentReasonCode::AlternativeProcurementChannel,
            "BUYER_DISSATISFACTION" => BillingAdjustmentReasonCode::BuyerDissatisfaction,
            "INCORRECT_METERING" => BillingAdjustmentReasonCode::IncorrectMetering,
            "INCORRECT_TERMS_ACCEPTED" => BillingAdjustmentReasonCode::IncorrectTermsAccepted,
            "OTHER" => BillingAdjustmentReasonCode::Other,
            "TEST_ENVIRONMENT_CHARGES" => BillingAdjustmentReasonCode::TestEnvironmentCharges,
            "UNINTENDED_RENEWAL" => BillingAdjustmentReasonCode::UnintendedRenewal,
            other => BillingAdjustmentReasonCode::Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue(other.to_owned())),
        }
    }
}
impl ::std::str::FromStr for BillingAdjustmentReasonCode {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(BillingAdjustmentReasonCode::from(s))
    }
}
impl BillingAdjustmentReasonCode {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            BillingAdjustmentReasonCode::AlternativeProcurementChannel => "ALTERNATIVE_PROCUREMENT_CHANNEL",
            BillingAdjustmentReasonCode::BuyerDissatisfaction => "BUYER_DISSATISFACTION",
            BillingAdjustmentReasonCode::IncorrectMetering => "INCORRECT_METERING",
            BillingAdjustmentReasonCode::IncorrectTermsAccepted => "INCORRECT_TERMS_ACCEPTED",
            BillingAdjustmentReasonCode::Other => "OTHER",
            BillingAdjustmentReasonCode::TestEnvironmentCharges => "TEST_ENVIRONMENT_CHARGES",
            BillingAdjustmentReasonCode::UnintendedRenewal => "UNINTENDED_RENEWAL",
            BillingAdjustmentReasonCode::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &[
            "ALTERNATIVE_PROCUREMENT_CHANNEL",
            "BUYER_DISSATISFACTION",
            "INCORRECT_METERING",
            "INCORRECT_TERMS_ACCEPTED",
            "OTHER",
            "TEST_ENVIRONMENT_CHARGES",
            "UNINTENDED_RENEWAL",
        ]
    }
}
impl ::std::convert::AsRef<str> for BillingAdjustmentReasonCode {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl BillingAdjustmentReasonCode {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(value: &str) -> ::std::result::Result<Self, crate::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => ::std::result::Result::Err(crate::error::UnknownVariantError::new(value)),
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for BillingAdjustmentReasonCode {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            BillingAdjustmentReasonCode::AlternativeProcurementChannel => write!(f, "ALTERNATIVE_PROCUREMENT_CHANNEL"),
            BillingAdjustmentReasonCode::BuyerDissatisfaction => write!(f, "BUYER_DISSATISFACTION"),
            BillingAdjustmentReasonCode::IncorrectMetering => write!(f, "INCORRECT_METERING"),
            BillingAdjustmentReasonCode::IncorrectTermsAccepted => write!(f, "INCORRECT_TERMS_ACCEPTED"),
            BillingAdjustmentReasonCode::Other => write!(f, "OTHER"),
            BillingAdjustmentReasonCode::TestEnvironmentCharges => write!(f, "TEST_ENVIRONMENT_CHARGES"),
            BillingAdjustmentReasonCode::UnintendedRenewal => write!(f, "UNINTENDED_RENEWAL"),
            BillingAdjustmentReasonCode::Unknown(value) => write!(f, "{value}"),
        }
    }
}
