// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_account_enforced_guardrail_inference_input_configuration(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::AccountEnforcedGuardrailInferenceInputConfiguration,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("guardrailIdentifier").string(input.guardrail_identifier.as_str());
    }
    {
        object.key("guardrailVersion").string(input.guardrail_version.as_str());
    }
    if let Some(var_1) = &input.selective_content_guarding {
        #[allow(unused_mut)]
        let mut object_2 = object.key("selectiveContentGuarding").start_object();
        crate::protocol_serde::shape_selective_content_guarding::ser_selective_content_guarding(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.model_enforcement {
        #[allow(unused_mut)]
        let mut object_4 = object.key("modelEnforcement").start_object();
        crate::protocol_serde::shape_model_enforcement::ser_model_enforcement(&mut object_4, var_3)?;
        object_4.finish();
    }
    Ok(())
}
