// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains configuration for the fiscal year granularities (e.g., <code>YEARLY_FISCAL</code>, <code>QUARTERLY_FISCAL</code>.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GranularityConfiguration {
    /// <p>The month (1-12) when the fiscal year begins. Used for <code>YEARLY_FISCAL</code> and <code>QUARTERLY_FISCAL</code> granularity. Defaults to 1 (January).</p>
    pub fiscal_year_start_month: i32,
}
impl GranularityConfiguration {
    /// <p>The month (1-12) when the fiscal year begins. Used for <code>YEARLY_FISCAL</code> and <code>QUARTERLY_FISCAL</code> granularity. Defaults to 1 (January).</p>
    pub fn fiscal_year_start_month(&self) -> i32 {
        self.fiscal_year_start_month
    }
}
impl GranularityConfiguration {
    /// Creates a new builder-style object to manufacture [`GranularityConfiguration`](crate::types::GranularityConfiguration).
    pub fn builder() -> crate::types::builders::GranularityConfigurationBuilder {
        crate::types::builders::GranularityConfigurationBuilder::default()
    }
}

/// A builder for [`GranularityConfiguration`](crate::types::GranularityConfiguration).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GranularityConfigurationBuilder {
    pub(crate) fiscal_year_start_month: ::std::option::Option<i32>,
}
impl GranularityConfigurationBuilder {
    /// <p>The month (1-12) when the fiscal year begins. Used for <code>YEARLY_FISCAL</code> and <code>QUARTERLY_FISCAL</code> granularity. Defaults to 1 (January).</p>
    pub fn fiscal_year_start_month(mut self, input: i32) -> Self {
        self.fiscal_year_start_month = ::std::option::Option::Some(input);
        self
    }
    /// <p>The month (1-12) when the fiscal year begins. Used for <code>YEARLY_FISCAL</code> and <code>QUARTERLY_FISCAL</code> granularity. Defaults to 1 (January).</p>
    pub fn set_fiscal_year_start_month(mut self, input: ::std::option::Option<i32>) -> Self {
        self.fiscal_year_start_month = input;
        self
    }
    /// <p>The month (1-12) when the fiscal year begins. Used for <code>YEARLY_FISCAL</code> and <code>QUARTERLY_FISCAL</code> granularity. Defaults to 1 (January).</p>
    pub fn get_fiscal_year_start_month(&self) -> &::std::option::Option<i32> {
        &self.fiscal_year_start_month
    }
    /// Consumes the builder and constructs a [`GranularityConfiguration`](crate::types::GranularityConfiguration).
    pub fn build(self) -> crate::types::GranularityConfiguration {
        crate::types::GranularityConfiguration {
            fiscal_year_start_month: self.fiscal_year_start_month.unwrap_or(1),
        }
    }
}
