// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains the authorization data that is returned when a gateway target is configured with a credential provider with authorization code grant type and requires user federation.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum AuthorizationData {
    /// <p>OAuth2 authorization data for the gateway target.</p>
    Oauth2(crate::types::OAuth2AuthorizationData),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl AuthorizationData {
    #[allow(irrefutable_let_patterns)]
    /// Tries to convert the enum instance into [`Oauth2`](crate::types::AuthorizationData::Oauth2), extracting the inner [`OAuth2AuthorizationData`](crate::types::OAuth2AuthorizationData).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_oauth2(&self) -> ::std::result::Result<&crate::types::OAuth2AuthorizationData, &Self> {
        if let AuthorizationData::Oauth2(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`Oauth2`](crate::types::AuthorizationData::Oauth2).
    pub fn is_oauth2(&self) -> bool {
        self.as_oauth2().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
