// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Configuration for synchronizing from a URL-based MCP server.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct FromUrlSynchronizationConfiguration {
    /// <p>The HTTPS URL of the MCP server to synchronize from.</p>
    pub url: ::std::string::String,
    /// <p>Optional list of credential provider configurations for authenticating with the MCP server. At most one credential provider configuration can be specified.</p>
    pub credential_provider_configurations: ::std::option::Option<::std::vec::Vec<crate::types::RegistryRecordCredentialProviderConfiguration>>,
}
impl FromUrlSynchronizationConfiguration {
    /// <p>The HTTPS URL of the MCP server to synchronize from.</p>
    pub fn url(&self) -> &str {
        use std::ops::Deref;
        self.url.deref()
    }
    /// <p>Optional list of credential provider configurations for authenticating with the MCP server. At most one credential provider configuration can be specified.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.credential_provider_configurations.is_none()`.
    pub fn credential_provider_configurations(&self) -> &[crate::types::RegistryRecordCredentialProviderConfiguration] {
        self.credential_provider_configurations.as_deref().unwrap_or_default()
    }
}
impl FromUrlSynchronizationConfiguration {
    /// Creates a new builder-style object to manufacture [`FromUrlSynchronizationConfiguration`](crate::types::FromUrlSynchronizationConfiguration).
    pub fn builder() -> crate::types::builders::FromUrlSynchronizationConfigurationBuilder {
        crate::types::builders::FromUrlSynchronizationConfigurationBuilder::default()
    }
}

/// A builder for [`FromUrlSynchronizationConfiguration`](crate::types::FromUrlSynchronizationConfiguration).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct FromUrlSynchronizationConfigurationBuilder {
    pub(crate) url: ::std::option::Option<::std::string::String>,
    pub(crate) credential_provider_configurations:
        ::std::option::Option<::std::vec::Vec<crate::types::RegistryRecordCredentialProviderConfiguration>>,
}
impl FromUrlSynchronizationConfigurationBuilder {
    /// <p>The HTTPS URL of the MCP server to synchronize from.</p>
    /// This field is required.
    pub fn url(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.url = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The HTTPS URL of the MCP server to synchronize from.</p>
    pub fn set_url(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.url = input;
        self
    }
    /// <p>The HTTPS URL of the MCP server to synchronize from.</p>
    pub fn get_url(&self) -> &::std::option::Option<::std::string::String> {
        &self.url
    }
    /// Appends an item to `credential_provider_configurations`.
    ///
    /// To override the contents of this collection use [`set_credential_provider_configurations`](Self::set_credential_provider_configurations).
    ///
    /// <p>Optional list of credential provider configurations for authenticating with the MCP server. At most one credential provider configuration can be specified.</p>
    pub fn credential_provider_configurations(mut self, input: crate::types::RegistryRecordCredentialProviderConfiguration) -> Self {
        let mut v = self.credential_provider_configurations.unwrap_or_default();
        v.push(input);
        self.credential_provider_configurations = ::std::option::Option::Some(v);
        self
    }
    /// <p>Optional list of credential provider configurations for authenticating with the MCP server. At most one credential provider configuration can be specified.</p>
    pub fn set_credential_provider_configurations(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<crate::types::RegistryRecordCredentialProviderConfiguration>>,
    ) -> Self {
        self.credential_provider_configurations = input;
        self
    }
    /// <p>Optional list of credential provider configurations for authenticating with the MCP server. At most one credential provider configuration can be specified.</p>
    pub fn get_credential_provider_configurations(
        &self,
    ) -> &::std::option::Option<::std::vec::Vec<crate::types::RegistryRecordCredentialProviderConfiguration>> {
        &self.credential_provider_configurations
    }
    /// Consumes the builder and constructs a [`FromUrlSynchronizationConfiguration`](crate::types::FromUrlSynchronizationConfiguration).
    /// This method will fail if any of the following fields are not set:
    /// - [`url`](crate::types::builders::FromUrlSynchronizationConfigurationBuilder::url)
    pub fn build(self) -> ::std::result::Result<crate::types::FromUrlSynchronizationConfiguration, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::FromUrlSynchronizationConfiguration {
            url: self.url.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "url",
                    "url was not specified but it is required when building FromUrlSynchronizationConfiguration",
                )
            })?,
            credential_provider_configurations: self.credential_provider_configurations,
        })
    }
}
