// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Wrapper for updating an optional approval configuration field with PATCH semantics. When present in an update request, the approval configuration is replaced with the provided value. When absent, the approval configuration is left unchanged.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdatedApprovalConfiguration {
    /// <p>The updated approval configuration value. Set to <code>null</code> to unset the approval configuration.</p>
    pub optional_value: ::std::option::Option<crate::types::ApprovalConfiguration>,
}
impl UpdatedApprovalConfiguration {
    /// <p>The updated approval configuration value. Set to <code>null</code> to unset the approval configuration.</p>
    pub fn optional_value(&self) -> ::std::option::Option<&crate::types::ApprovalConfiguration> {
        self.optional_value.as_ref()
    }
}
impl UpdatedApprovalConfiguration {
    /// Creates a new builder-style object to manufacture [`UpdatedApprovalConfiguration`](crate::types::UpdatedApprovalConfiguration).
    pub fn builder() -> crate::types::builders::UpdatedApprovalConfigurationBuilder {
        crate::types::builders::UpdatedApprovalConfigurationBuilder::default()
    }
}

/// A builder for [`UpdatedApprovalConfiguration`](crate::types::UpdatedApprovalConfiguration).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpdatedApprovalConfigurationBuilder {
    pub(crate) optional_value: ::std::option::Option<crate::types::ApprovalConfiguration>,
}
impl UpdatedApprovalConfigurationBuilder {
    /// <p>The updated approval configuration value. Set to <code>null</code> to unset the approval configuration.</p>
    pub fn optional_value(mut self, input: crate::types::ApprovalConfiguration) -> Self {
        self.optional_value = ::std::option::Option::Some(input);
        self
    }
    /// <p>The updated approval configuration value. Set to <code>null</code> to unset the approval configuration.</p>
    pub fn set_optional_value(mut self, input: ::std::option::Option<crate::types::ApprovalConfiguration>) -> Self {
        self.optional_value = input;
        self
    }
    /// <p>The updated approval configuration value. Set to <code>null</code> to unset the approval configuration.</p>
    pub fn get_optional_value(&self) -> &::std::option::Option<crate::types::ApprovalConfiguration> {
        &self.optional_value
    }
    /// Consumes the builder and constructs a [`UpdatedApprovalConfiguration`](crate::types::UpdatedApprovalConfiguration).
    pub fn build(self) -> crate::types::UpdatedApprovalConfiguration {
        crate::types::UpdatedApprovalConfiguration {
            optional_value: self.optional_value,
        }
    }
}
