// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct GetRegistryRecordOutput {
    /// <p>The Amazon Resource Name (ARN) of the registry that contains the record.</p>
    pub registry_arn: ::std::string::String,
    /// <p>The Amazon Resource Name (ARN) of the registry record.</p>
    pub record_arn: ::std::string::String,
    /// <p>The unique identifier of the registry record.</p>
    pub record_id: ::std::string::String,
    /// <p>The name of the registry record.</p>
    pub name: ::std::string::String,
    /// <p>The description of the registry record.</p>
    pub description: ::std::option::Option<::std::string::String>,
    /// <p>The descriptor type of the registry record. Possible values are <code>MCP</code>, <code>A2A</code>, <code>CUSTOM</code>, and <code>AGENT_SKILLS</code>.</p>
    pub descriptor_type: crate::types::DescriptorType,
    /// <p>The descriptor-type-specific configuration containing the resource schema and metadata. For details, see the <code>Descriptors</code> data type.</p>
    pub descriptors: ::std::option::Option<crate::types::Descriptors>,
    /// <p>The version of the registry record.</p>
    pub record_version: ::std::option::Option<::std::string::String>,
    /// <p>The current status of the registry record. Possible values include <code>CREATING</code>, <code>DRAFT</code>, <code>APPROVED</code>, <code>PENDING_APPROVAL</code>, <code>REJECTED</code>, <code>DEPRECATED</code>, <code>UPDATING</code>, <code>CREATE_FAILED</code>, and <code>UPDATE_FAILED</code>. A record transitions from <code>CREATING</code> to <code>DRAFT</code>, then to <code>PENDING_APPROVAL</code> (via <code>SubmitRegistryRecordForApproval</code>), and finally to <code>APPROVED</code> upon approval.</p>
    pub status: crate::types::RegistryRecordStatus,
    /// <p>The timestamp when the registry record was created.</p>
    pub created_at: ::aws_smithy_types::DateTime,
    /// <p>The timestamp when the registry record was last updated.</p>
    pub updated_at: ::aws_smithy_types::DateTime,
    /// <p>The reason for the current status, typically set when the status is a failure state.</p>
    pub status_reason: ::std::option::Option<::std::string::String>,
    /// <p>The type of synchronization used for this record.</p>
    pub synchronization_type: ::std::option::Option<crate::types::SynchronizationType>,
    /// <p>The configuration for synchronizing registry record metadata from an external source.</p>
    pub synchronization_configuration: ::std::option::Option<crate::types::SynchronizationConfiguration>,
    _request_id: Option<String>,
}
impl GetRegistryRecordOutput {
    /// <p>The Amazon Resource Name (ARN) of the registry that contains the record.</p>
    pub fn registry_arn(&self) -> &str {
        use std::ops::Deref;
        self.registry_arn.deref()
    }
    /// <p>The Amazon Resource Name (ARN) of the registry record.</p>
    pub fn record_arn(&self) -> &str {
        use std::ops::Deref;
        self.record_arn.deref()
    }
    /// <p>The unique identifier of the registry record.</p>
    pub fn record_id(&self) -> &str {
        use std::ops::Deref;
        self.record_id.deref()
    }
    /// <p>The name of the registry record.</p>
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
    /// <p>The description of the registry record.</p>
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    /// <p>The descriptor type of the registry record. Possible values are <code>MCP</code>, <code>A2A</code>, <code>CUSTOM</code>, and <code>AGENT_SKILLS</code>.</p>
    pub fn descriptor_type(&self) -> &crate::types::DescriptorType {
        &self.descriptor_type
    }
    /// <p>The descriptor-type-specific configuration containing the resource schema and metadata. For details, see the <code>Descriptors</code> data type.</p>
    pub fn descriptors(&self) -> ::std::option::Option<&crate::types::Descriptors> {
        self.descriptors.as_ref()
    }
    /// <p>The version of the registry record.</p>
    pub fn record_version(&self) -> ::std::option::Option<&str> {
        self.record_version.as_deref()
    }
    /// <p>The current status of the registry record. Possible values include <code>CREATING</code>, <code>DRAFT</code>, <code>APPROVED</code>, <code>PENDING_APPROVAL</code>, <code>REJECTED</code>, <code>DEPRECATED</code>, <code>UPDATING</code>, <code>CREATE_FAILED</code>, and <code>UPDATE_FAILED</code>. A record transitions from <code>CREATING</code> to <code>DRAFT</code>, then to <code>PENDING_APPROVAL</code> (via <code>SubmitRegistryRecordForApproval</code>), and finally to <code>APPROVED</code> upon approval.</p>
    pub fn status(&self) -> &crate::types::RegistryRecordStatus {
        &self.status
    }
    /// <p>The timestamp when the registry record was created.</p>
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
    /// <p>The timestamp when the registry record was last updated.</p>
    pub fn updated_at(&self) -> &::aws_smithy_types::DateTime {
        &self.updated_at
    }
    /// <p>The reason for the current status, typically set when the status is a failure state.</p>
    pub fn status_reason(&self) -> ::std::option::Option<&str> {
        self.status_reason.as_deref()
    }
    /// <p>The type of synchronization used for this record.</p>
    pub fn synchronization_type(&self) -> ::std::option::Option<&crate::types::SynchronizationType> {
        self.synchronization_type.as_ref()
    }
    /// <p>The configuration for synchronizing registry record metadata from an external source.</p>
    pub fn synchronization_configuration(&self) -> ::std::option::Option<&crate::types::SynchronizationConfiguration> {
        self.synchronization_configuration.as_ref()
    }
}
impl ::std::fmt::Debug for GetRegistryRecordOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetRegistryRecordOutput");
        formatter.field("registry_arn", &self.registry_arn);
        formatter.field("record_arn", &self.record_arn);
        formatter.field("record_id", &self.record_id);
        formatter.field("name", &self.name);
        formatter.field("description", &"*** Sensitive Data Redacted ***");
        formatter.field("descriptor_type", &self.descriptor_type);
        formatter.field("descriptors", &self.descriptors);
        formatter.field("record_version", &self.record_version);
        formatter.field("status", &self.status);
        formatter.field("created_at", &self.created_at);
        formatter.field("updated_at", &self.updated_at);
        formatter.field("status_reason", &self.status_reason);
        formatter.field("synchronization_type", &self.synchronization_type);
        formatter.field("synchronization_configuration", &self.synchronization_configuration);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
impl ::aws_types::request_id::RequestId for GetRegistryRecordOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl GetRegistryRecordOutput {
    /// Creates a new builder-style object to manufacture [`GetRegistryRecordOutput`](crate::operation::get_registry_record::GetRegistryRecordOutput).
    pub fn builder() -> crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder {
        crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::default()
    }
}

/// A builder for [`GetRegistryRecordOutput`](crate::operation::get_registry_record::GetRegistryRecordOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct GetRegistryRecordOutputBuilder {
    pub(crate) registry_arn: ::std::option::Option<::std::string::String>,
    pub(crate) record_arn: ::std::option::Option<::std::string::String>,
    pub(crate) record_id: ::std::option::Option<::std::string::String>,
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) descriptor_type: ::std::option::Option<crate::types::DescriptorType>,
    pub(crate) descriptors: ::std::option::Option<crate::types::Descriptors>,
    pub(crate) record_version: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::RegistryRecordStatus>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) updated_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) status_reason: ::std::option::Option<::std::string::String>,
    pub(crate) synchronization_type: ::std::option::Option<crate::types::SynchronizationType>,
    pub(crate) synchronization_configuration: ::std::option::Option<crate::types::SynchronizationConfiguration>,
    _request_id: Option<String>,
}
impl GetRegistryRecordOutputBuilder {
    /// <p>The Amazon Resource Name (ARN) of the registry that contains the record.</p>
    /// This field is required.
    pub fn registry_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.registry_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the registry that contains the record.</p>
    pub fn set_registry_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.registry_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the registry that contains the record.</p>
    pub fn get_registry_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.registry_arn
    }
    /// <p>The Amazon Resource Name (ARN) of the registry record.</p>
    /// This field is required.
    pub fn record_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.record_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the registry record.</p>
    pub fn set_record_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.record_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the registry record.</p>
    pub fn get_record_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.record_arn
    }
    /// <p>The unique identifier of the registry record.</p>
    /// This field is required.
    pub fn record_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.record_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the registry record.</p>
    pub fn set_record_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.record_id = input;
        self
    }
    /// <p>The unique identifier of the registry record.</p>
    pub fn get_record_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.record_id
    }
    /// <p>The name of the registry record.</p>
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the registry record.</p>
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// <p>The name of the registry record.</p>
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// <p>The description of the registry record.</p>
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The description of the registry record.</p>
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }
    /// <p>The description of the registry record.</p>
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// <p>The descriptor type of the registry record. Possible values are <code>MCP</code>, <code>A2A</code>, <code>CUSTOM</code>, and <code>AGENT_SKILLS</code>.</p>
    /// This field is required.
    pub fn descriptor_type(mut self, input: crate::types::DescriptorType) -> Self {
        self.descriptor_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The descriptor type of the registry record. Possible values are <code>MCP</code>, <code>A2A</code>, <code>CUSTOM</code>, and <code>AGENT_SKILLS</code>.</p>
    pub fn set_descriptor_type(mut self, input: ::std::option::Option<crate::types::DescriptorType>) -> Self {
        self.descriptor_type = input;
        self
    }
    /// <p>The descriptor type of the registry record. Possible values are <code>MCP</code>, <code>A2A</code>, <code>CUSTOM</code>, and <code>AGENT_SKILLS</code>.</p>
    pub fn get_descriptor_type(&self) -> &::std::option::Option<crate::types::DescriptorType> {
        &self.descriptor_type
    }
    /// <p>The descriptor-type-specific configuration containing the resource schema and metadata. For details, see the <code>Descriptors</code> data type.</p>
    /// This field is required.
    pub fn descriptors(mut self, input: crate::types::Descriptors) -> Self {
        self.descriptors = ::std::option::Option::Some(input);
        self
    }
    /// <p>The descriptor-type-specific configuration containing the resource schema and metadata. For details, see the <code>Descriptors</code> data type.</p>
    pub fn set_descriptors(mut self, input: ::std::option::Option<crate::types::Descriptors>) -> Self {
        self.descriptors = input;
        self
    }
    /// <p>The descriptor-type-specific configuration containing the resource schema and metadata. For details, see the <code>Descriptors</code> data type.</p>
    pub fn get_descriptors(&self) -> &::std::option::Option<crate::types::Descriptors> {
        &self.descriptors
    }
    /// <p>The version of the registry record.</p>
    pub fn record_version(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.record_version = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The version of the registry record.</p>
    pub fn set_record_version(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.record_version = input;
        self
    }
    /// <p>The version of the registry record.</p>
    pub fn get_record_version(&self) -> &::std::option::Option<::std::string::String> {
        &self.record_version
    }
    /// <p>The current status of the registry record. Possible values include <code>CREATING</code>, <code>DRAFT</code>, <code>APPROVED</code>, <code>PENDING_APPROVAL</code>, <code>REJECTED</code>, <code>DEPRECATED</code>, <code>UPDATING</code>, <code>CREATE_FAILED</code>, and <code>UPDATE_FAILED</code>. A record transitions from <code>CREATING</code> to <code>DRAFT</code>, then to <code>PENDING_APPROVAL</code> (via <code>SubmitRegistryRecordForApproval</code>), and finally to <code>APPROVED</code> upon approval.</p>
    /// This field is required.
    pub fn status(mut self, input: crate::types::RegistryRecordStatus) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    /// <p>The current status of the registry record. Possible values include <code>CREATING</code>, <code>DRAFT</code>, <code>APPROVED</code>, <code>PENDING_APPROVAL</code>, <code>REJECTED</code>, <code>DEPRECATED</code>, <code>UPDATING</code>, <code>CREATE_FAILED</code>, and <code>UPDATE_FAILED</code>. A record transitions from <code>CREATING</code> to <code>DRAFT</code>, then to <code>PENDING_APPROVAL</code> (via <code>SubmitRegistryRecordForApproval</code>), and finally to <code>APPROVED</code> upon approval.</p>
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::RegistryRecordStatus>) -> Self {
        self.status = input;
        self
    }
    /// <p>The current status of the registry record. Possible values include <code>CREATING</code>, <code>DRAFT</code>, <code>APPROVED</code>, <code>PENDING_APPROVAL</code>, <code>REJECTED</code>, <code>DEPRECATED</code>, <code>UPDATING</code>, <code>CREATE_FAILED</code>, and <code>UPDATE_FAILED</code>. A record transitions from <code>CREATING</code> to <code>DRAFT</code>, then to <code>PENDING_APPROVAL</code> (via <code>SubmitRegistryRecordForApproval</code>), and finally to <code>APPROVED</code> upon approval.</p>
    pub fn get_status(&self) -> &::std::option::Option<crate::types::RegistryRecordStatus> {
        &self.status
    }
    /// <p>The timestamp when the registry record was created.</p>
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    /// <p>The timestamp when the registry record was created.</p>
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input;
        self
    }
    /// <p>The timestamp when the registry record was created.</p>
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// <p>The timestamp when the registry record was last updated.</p>
    /// This field is required.
    pub fn updated_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.updated_at = ::std::option::Option::Some(input);
        self
    }
    /// <p>The timestamp when the registry record was last updated.</p>
    pub fn set_updated_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.updated_at = input;
        self
    }
    /// <p>The timestamp when the registry record was last updated.</p>
    pub fn get_updated_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.updated_at
    }
    /// <p>The reason for the current status, typically set when the status is a failure state.</p>
    pub fn status_reason(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.status_reason = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The reason for the current status, typically set when the status is a failure state.</p>
    pub fn set_status_reason(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.status_reason = input;
        self
    }
    /// <p>The reason for the current status, typically set when the status is a failure state.</p>
    pub fn get_status_reason(&self) -> &::std::option::Option<::std::string::String> {
        &self.status_reason
    }
    /// <p>The type of synchronization used for this record.</p>
    pub fn synchronization_type(mut self, input: crate::types::SynchronizationType) -> Self {
        self.synchronization_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The type of synchronization used for this record.</p>
    pub fn set_synchronization_type(mut self, input: ::std::option::Option<crate::types::SynchronizationType>) -> Self {
        self.synchronization_type = input;
        self
    }
    /// <p>The type of synchronization used for this record.</p>
    pub fn get_synchronization_type(&self) -> &::std::option::Option<crate::types::SynchronizationType> {
        &self.synchronization_type
    }
    /// <p>The configuration for synchronizing registry record metadata from an external source.</p>
    pub fn synchronization_configuration(mut self, input: crate::types::SynchronizationConfiguration) -> Self {
        self.synchronization_configuration = ::std::option::Option::Some(input);
        self
    }
    /// <p>The configuration for synchronizing registry record metadata from an external source.</p>
    pub fn set_synchronization_configuration(mut self, input: ::std::option::Option<crate::types::SynchronizationConfiguration>) -> Self {
        self.synchronization_configuration = input;
        self
    }
    /// <p>The configuration for synchronizing registry record metadata from an external source.</p>
    pub fn get_synchronization_configuration(&self) -> &::std::option::Option<crate::types::SynchronizationConfiguration> {
        &self.synchronization_configuration
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`GetRegistryRecordOutput`](crate::operation::get_registry_record::GetRegistryRecordOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`registry_arn`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::registry_arn)
    /// - [`record_arn`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::record_arn)
    /// - [`record_id`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::record_id)
    /// - [`name`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::name)
    /// - [`descriptor_type`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::descriptor_type)
    /// - [`status`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::status)
    /// - [`created_at`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::created_at)
    /// - [`updated_at`](crate::operation::get_registry_record::builders::GetRegistryRecordOutputBuilder::updated_at)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::get_registry_record::GetRegistryRecordOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::get_registry_record::GetRegistryRecordOutput {
            registry_arn: self.registry_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "registry_arn",
                    "registry_arn was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            record_arn: self.record_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "record_arn",
                    "record_arn was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            record_id: self.record_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "record_id",
                    "record_id was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            name: self.name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "name",
                    "name was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            description: self.description,
            descriptor_type: self.descriptor_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "descriptor_type",
                    "descriptor_type was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            descriptors: self.descriptors,
            record_version: self.record_version,
            status: self.status.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "status",
                    "status was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            created_at: self.created_at.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "created_at",
                    "created_at was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            updated_at: self.updated_at.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "updated_at",
                    "updated_at was not specified but it is required when building GetRegistryRecordOutput",
                )
            })?,
            status_reason: self.status_reason,
            synchronization_type: self.synchronization_type,
            synchronization_configuration: self.synchronization_configuration,
            _request_id: self._request_id,
        })
    }
}
impl ::std::fmt::Debug for GetRegistryRecordOutputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetRegistryRecordOutputBuilder");
        formatter.field("registry_arn", &self.registry_arn);
        formatter.field("record_arn", &self.record_arn);
        formatter.field("record_id", &self.record_id);
        formatter.field("name", &self.name);
        formatter.field("description", &"*** Sensitive Data Redacted ***");
        formatter.field("descriptor_type", &self.descriptor_type);
        formatter.field("descriptors", &self.descriptors);
        formatter.field("record_version", &self.record_version);
        formatter.field("status", &self.status);
        formatter.field("created_at", &self.created_at);
        formatter.field("updated_at", &self.updated_at);
        formatter.field("status_reason", &self.status_reason);
        formatter.field("synchronization_type", &self.synchronization_type);
        formatter.field("synchronization_configuration", &self.synchronization_configuration);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
