// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Filters certificates by DNS name.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DnsNameFilter {
    /// <p>The DNS name value to match against.</p>
    pub value: ::std::string::String,
    /// <p>The comparison operator to use.</p>
    pub comparison_operator: crate::types::ComparisonOperator,
}
impl DnsNameFilter {
    /// <p>The DNS name value to match against.</p>
    pub fn value(&self) -> &str {
        use std::ops::Deref;
        self.value.deref()
    }
    /// <p>The comparison operator to use.</p>
    pub fn comparison_operator(&self) -> &crate::types::ComparisonOperator {
        &self.comparison_operator
    }
}
impl DnsNameFilter {
    /// Creates a new builder-style object to manufacture [`DnsNameFilter`](crate::types::DnsNameFilter).
    pub fn builder() -> crate::types::builders::DnsNameFilterBuilder {
        crate::types::builders::DnsNameFilterBuilder::default()
    }
}

/// A builder for [`DnsNameFilter`](crate::types::DnsNameFilter).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DnsNameFilterBuilder {
    pub(crate) value: ::std::option::Option<::std::string::String>,
    pub(crate) comparison_operator: ::std::option::Option<crate::types::ComparisonOperator>,
}
impl DnsNameFilterBuilder {
    /// <p>The DNS name value to match against.</p>
    /// This field is required.
    pub fn value(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The DNS name value to match against.</p>
    pub fn set_value(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.value = input;
        self
    }
    /// <p>The DNS name value to match against.</p>
    pub fn get_value(&self) -> &::std::option::Option<::std::string::String> {
        &self.value
    }
    /// <p>The comparison operator to use.</p>
    /// This field is required.
    pub fn comparison_operator(mut self, input: crate::types::ComparisonOperator) -> Self {
        self.comparison_operator = ::std::option::Option::Some(input);
        self
    }
    /// <p>The comparison operator to use.</p>
    pub fn set_comparison_operator(mut self, input: ::std::option::Option<crate::types::ComparisonOperator>) -> Self {
        self.comparison_operator = input;
        self
    }
    /// <p>The comparison operator to use.</p>
    pub fn get_comparison_operator(&self) -> &::std::option::Option<crate::types::ComparisonOperator> {
        &self.comparison_operator
    }
    /// Consumes the builder and constructs a [`DnsNameFilter`](crate::types::DnsNameFilter).
    /// This method will fail if any of the following fields are not set:
    /// - [`value`](crate::types::builders::DnsNameFilterBuilder::value)
    /// - [`comparison_operator`](crate::types::builders::DnsNameFilterBuilder::comparison_operator)
    pub fn build(self) -> ::std::result::Result<crate::types::DnsNameFilter, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::DnsNameFilter {
            value: self.value.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "value",
                    "value was not specified but it is required when building DnsNameFilter",
                )
            })?,
            comparison_operator: self.comparison_operator.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "comparison_operator",
                    "comparison_operator was not specified but it is required when building DnsNameFilter",
                )
            })?,
        })
    }
}
