// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreatePolicyPreviewConfigurationInput {
    /// <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request and have no additional effect.</p>
    pub client_token: ::std::option::Option<::std::string::String>,
    /// <p>The scope of the policy preview configuration. Currently only <code>GLOBAL</code> is supported.</p>
    pub scope: ::std::option::Option<crate::types::PolicyPreviewScope>,
}
impl CreatePolicyPreviewConfigurationInput {
    /// <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request and have no additional effect.</p>
    pub fn client_token(&self) -> ::std::option::Option<&str> {
        self.client_token.as_deref()
    }
    /// <p>The scope of the policy preview configuration. Currently only <code>GLOBAL</code> is supported.</p>
    pub fn scope(&self) -> ::std::option::Option<&crate::types::PolicyPreviewScope> {
        self.scope.as_ref()
    }
}
impl CreatePolicyPreviewConfigurationInput {
    /// Creates a new builder-style object to manufacture [`CreatePolicyPreviewConfigurationInput`](crate::operation::create_policy_preview_configuration::CreatePolicyPreviewConfigurationInput).
    pub fn builder() -> crate::operation::create_policy_preview_configuration::builders::CreatePolicyPreviewConfigurationInputBuilder {
        crate::operation::create_policy_preview_configuration::builders::CreatePolicyPreviewConfigurationInputBuilder::default()
    }
}

/// A builder for [`CreatePolicyPreviewConfigurationInput`](crate::operation::create_policy_preview_configuration::CreatePolicyPreviewConfigurationInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreatePolicyPreviewConfigurationInputBuilder {
    pub(crate) client_token: ::std::option::Option<::std::string::String>,
    pub(crate) scope: ::std::option::Option<crate::types::PolicyPreviewScope>,
}
impl CreatePolicyPreviewConfigurationInputBuilder {
    /// <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request and have no additional effect.</p>
    pub fn client_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.client_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request and have no additional effect.</p>
    pub fn set_client_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.client_token = input;
        self
    }
    /// <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request and have no additional effect.</p>
    pub fn get_client_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.client_token
    }
    /// <p>The scope of the policy preview configuration. Currently only <code>GLOBAL</code> is supported.</p>
    pub fn scope(mut self, input: crate::types::PolicyPreviewScope) -> Self {
        self.scope = ::std::option::Option::Some(input);
        self
    }
    /// <p>The scope of the policy preview configuration. Currently only <code>GLOBAL</code> is supported.</p>
    pub fn set_scope(mut self, input: ::std::option::Option<crate::types::PolicyPreviewScope>) -> Self {
        self.scope = input;
        self
    }
    /// <p>The scope of the policy preview configuration. Currently only <code>GLOBAL</code> is supported.</p>
    pub fn get_scope(&self) -> &::std::option::Option<crate::types::PolicyPreviewScope> {
        &self.scope
    }
    /// Consumes the builder and constructs a [`CreatePolicyPreviewConfigurationInput`](crate::operation::create_policy_preview_configuration::CreatePolicyPreviewConfigurationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_policy_preview_configuration::CreatePolicyPreviewConfigurationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::create_policy_preview_configuration::CreatePolicyPreviewConfigurationInput {
                client_token: self.client_token,
                scope: self.scope,
            },
        )
    }
}
