// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Content event containing stdout or stderr output
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContentDeltaEvent {
    /// Standard output content
    pub stdout: ::std::option::Option<::std::string::String>,
    /// Standard error content
    pub stderr: ::std::option::Option<::std::string::String>,
}
impl ContentDeltaEvent {
    /// Standard output content
    pub fn stdout(&self) -> ::std::option::Option<&str> {
        self.stdout.as_deref()
    }
    /// Standard error content
    pub fn stderr(&self) -> ::std::option::Option<&str> {
        self.stderr.as_deref()
    }
}
impl ContentDeltaEvent {
    /// Creates a new builder-style object to manufacture [`ContentDeltaEvent`](crate::types::ContentDeltaEvent).
    pub fn builder() -> crate::types::builders::ContentDeltaEventBuilder {
        crate::types::builders::ContentDeltaEventBuilder::default()
    }
}

/// A builder for [`ContentDeltaEvent`](crate::types::ContentDeltaEvent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContentDeltaEventBuilder {
    pub(crate) stdout: ::std::option::Option<::std::string::String>,
    pub(crate) stderr: ::std::option::Option<::std::string::String>,
}
impl ContentDeltaEventBuilder {
    /// Standard output content
    pub fn stdout(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.stdout = ::std::option::Option::Some(input.into());
        self
    }
    /// Standard output content
    pub fn set_stdout(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.stdout = input;
        self
    }
    /// Standard output content
    pub fn get_stdout(&self) -> &::std::option::Option<::std::string::String> {
        &self.stdout
    }
    /// Standard error content
    pub fn stderr(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.stderr = ::std::option::Option::Some(input.into());
        self
    }
    /// Standard error content
    pub fn set_stderr(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.stderr = input;
        self
    }
    /// Standard error content
    pub fn get_stderr(&self) -> &::std::option::Option<::std::string::String> {
        &self.stderr
    }
    /// Consumes the builder and constructs a [`ContentDeltaEvent`](crate::types::ContentDeltaEvent).
    pub fn build(self) -> crate::types::ContentDeltaEvent {
        crate::types::ContentDeltaEvent {
            stdout: self.stdout,
            stderr: self.stderr,
        }
    }
}
