// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains filter criteria for listing sessions.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SessionFilter {
    /// <p>The event filter condition to apply. Use this to filter sessions based on event presence.</p>
    pub event_filter: ::std::option::Option<crate::types::EventFilterCondition>,
}
impl SessionFilter {
    /// <p>The event filter condition to apply. Use this to filter sessions based on event presence.</p>
    pub fn event_filter(&self) -> ::std::option::Option<&crate::types::EventFilterCondition> {
        self.event_filter.as_ref()
    }
}
impl SessionFilter {
    /// Creates a new builder-style object to manufacture [`SessionFilter`](crate::types::SessionFilter).
    pub fn builder() -> crate::types::builders::SessionFilterBuilder {
        crate::types::builders::SessionFilterBuilder::default()
    }
}

/// A builder for [`SessionFilter`](crate::types::SessionFilter).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SessionFilterBuilder {
    pub(crate) event_filter: ::std::option::Option<crate::types::EventFilterCondition>,
}
impl SessionFilterBuilder {
    /// <p>The event filter condition to apply. Use this to filter sessions based on event presence.</p>
    pub fn event_filter(mut self, input: crate::types::EventFilterCondition) -> Self {
        self.event_filter = ::std::option::Option::Some(input);
        self
    }
    /// <p>The event filter condition to apply. Use this to filter sessions based on event presence.</p>
    pub fn set_event_filter(mut self, input: ::std::option::Option<crate::types::EventFilterCondition>) -> Self {
        self.event_filter = input;
        self
    }
    /// <p>The event filter condition to apply. Use this to filter sessions based on event presence.</p>
    pub fn get_event_filter(&self) -> &::std::option::Option<crate::types::EventFilterCondition> {
        &self.event_filter
    }
    /// Consumes the builder and constructs a [`SessionFilter`](crate::types::SessionFilter).
    pub fn build(self) -> crate::types::SessionFilter {
        crate::types::SessionFilter {
            event_filter: self.event_filter,
        }
    }
}
