// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The skill markdown definition for agent skills descriptors.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SkillMdDefinition {
    /// <p>The inline markdown content of the skill definition.</p>
    pub inline_content: ::std::option::Option<::std::string::String>,
}
impl SkillMdDefinition {
    /// <p>The inline markdown content of the skill definition.</p>
    pub fn inline_content(&self) -> ::std::option::Option<&str> {
        self.inline_content.as_deref()
    }
}
impl SkillMdDefinition {
    /// Creates a new builder-style object to manufacture [`SkillMdDefinition`](crate::types::SkillMdDefinition).
    pub fn builder() -> crate::types::builders::SkillMdDefinitionBuilder {
        crate::types::builders::SkillMdDefinitionBuilder::default()
    }
}

/// A builder for [`SkillMdDefinition`](crate::types::SkillMdDefinition).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SkillMdDefinitionBuilder {
    pub(crate) inline_content: ::std::option::Option<::std::string::String>,
}
impl SkillMdDefinitionBuilder {
    /// <p>The inline markdown content of the skill definition.</p>
    pub fn inline_content(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inline_content = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The inline markdown content of the skill definition.</p>
    pub fn set_inline_content(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inline_content = input;
        self
    }
    /// <p>The inline markdown content of the skill definition.</p>
    pub fn get_inline_content(&self) -> &::std::option::Option<::std::string::String> {
        &self.inline_content
    }
    /// Consumes the builder and constructs a [`SkillMdDefinition`](crate::types::SkillMdDefinition).
    pub fn build(self) -> crate::types::SkillMdDefinition {
        crate::types::SkillMdDefinition {
            inline_content: self.inline_content,
        }
    }
}
