// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DescribeDaemonTaskDefinition`](crate::operation::describe_daemon_task_definition::builders::DescribeDaemonTaskDefinitionFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`daemon_task_definition(impl Into<String>)`](crate::operation::describe_daemon_task_definition::builders::DescribeDaemonTaskDefinitionFluentBuilder::daemon_task_definition) / [`set_daemon_task_definition(Option<String>)`](crate::operation::describe_daemon_task_definition::builders::DescribeDaemonTaskDefinitionFluentBuilder::set_daemon_task_definition):<br>required: **true**<br><p>The <code>family</code> for the latest <code>ACTIVE</code> revision, <code>family</code> and <code>revision</code> (<code>family:revision</code>) for a specific revision in the family, or full Amazon Resource Name (ARN) of the daemon task definition to describe.</p><br>
    /// - On success, responds with [`DescribeDaemonTaskDefinitionOutput`](crate::operation::describe_daemon_task_definition::DescribeDaemonTaskDefinitionOutput) with field(s):
    ///   - [`daemon_task_definition(Option<DaemonTaskDefinition>)`](crate::operation::describe_daemon_task_definition::DescribeDaemonTaskDefinitionOutput::daemon_task_definition): <p>The full daemon task definition description.</p>
    /// - On failure, responds with [`SdkError<DescribeDaemonTaskDefinitionError>`](crate::operation::describe_daemon_task_definition::DescribeDaemonTaskDefinitionError)
    pub fn describe_daemon_task_definition(
        &self,
    ) -> crate::operation::describe_daemon_task_definition::builders::DescribeDaemonTaskDefinitionFluentBuilder {
        crate::operation::describe_daemon_task_definition::builders::DescribeDaemonTaskDefinitionFluentBuilder::new(self.handle.clone())
    }
}
