// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListAgreementInvoiceLineItemsInput {
    /// <p>The unique identifier of the agreement.</p>
    pub agreement_id: ::std::option::Option<::std::string::String>,
    /// <p>Specifies a grouping strategy for line items. Currently supports <code>INVOICE_ID</code>.</p>
    pub group_by: ::std::option::Option<crate::types::LineItemGroupBy>,
    /// <p>An optional filter to retrieve invoice information for a specific invoice.</p>
    pub invoice_id: ::std::option::Option<::std::string::String>,
    /// <p>An optional filter for the type of invoice. Valid values are <code>INVOICE</code> and <code>CREDIT_MEMO</code>.</p>
    pub invoice_type: ::std::option::Option<crate::types::InvoiceType>,
    /// <p>An optional filter for the billing period associated with the invoice.</p>
    pub invoice_billing_period: ::std::option::Option<crate::types::InvoiceBillingPeriod>,
    /// <p>An optional filter for invoices issued before the specified timestamp.</p>
    pub before_issued_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    /// <p>An optional filter for invoices issued after the specified timestamp.</p>
    pub after_issued_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    /// <p>The maximum number of results to return in the response.</p>
    pub max_results: ::std::option::Option<i32>,
    /// <p>A token to specify where to start pagination.</p>
    pub next_token: ::std::option::Option<::std::string::String>,
}
impl ListAgreementInvoiceLineItemsInput {
    /// <p>The unique identifier of the agreement.</p>
    pub fn agreement_id(&self) -> ::std::option::Option<&str> {
        self.agreement_id.as_deref()
    }
    /// <p>Specifies a grouping strategy for line items. Currently supports <code>INVOICE_ID</code>.</p>
    pub fn group_by(&self) -> ::std::option::Option<&crate::types::LineItemGroupBy> {
        self.group_by.as_ref()
    }
    /// <p>An optional filter to retrieve invoice information for a specific invoice.</p>
    pub fn invoice_id(&self) -> ::std::option::Option<&str> {
        self.invoice_id.as_deref()
    }
    /// <p>An optional filter for the type of invoice. Valid values are <code>INVOICE</code> and <code>CREDIT_MEMO</code>.</p>
    pub fn invoice_type(&self) -> ::std::option::Option<&crate::types::InvoiceType> {
        self.invoice_type.as_ref()
    }
    /// <p>An optional filter for the billing period associated with the invoice.</p>
    pub fn invoice_billing_period(&self) -> ::std::option::Option<&crate::types::InvoiceBillingPeriod> {
        self.invoice_billing_period.as_ref()
    }
    /// <p>An optional filter for invoices issued before the specified timestamp.</p>
    pub fn before_issued_time(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.before_issued_time.as_ref()
    }
    /// <p>An optional filter for invoices issued after the specified timestamp.</p>
    pub fn after_issued_time(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.after_issued_time.as_ref()
    }
    /// <p>The maximum number of results to return in the response.</p>
    pub fn max_results(&self) -> ::std::option::Option<i32> {
        self.max_results
    }
    /// <p>A token to specify where to start pagination.</p>
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }
}
impl ListAgreementInvoiceLineItemsInput {
    /// Creates a new builder-style object to manufacture [`ListAgreementInvoiceLineItemsInput`](crate::operation::list_agreement_invoice_line_items::ListAgreementInvoiceLineItemsInput).
    pub fn builder() -> crate::operation::list_agreement_invoice_line_items::builders::ListAgreementInvoiceLineItemsInputBuilder {
        crate::operation::list_agreement_invoice_line_items::builders::ListAgreementInvoiceLineItemsInputBuilder::default()
    }
}

/// A builder for [`ListAgreementInvoiceLineItemsInput`](crate::operation::list_agreement_invoice_line_items::ListAgreementInvoiceLineItemsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListAgreementInvoiceLineItemsInputBuilder {
    pub(crate) agreement_id: ::std::option::Option<::std::string::String>,
    pub(crate) group_by: ::std::option::Option<crate::types::LineItemGroupBy>,
    pub(crate) invoice_id: ::std::option::Option<::std::string::String>,
    pub(crate) invoice_type: ::std::option::Option<crate::types::InvoiceType>,
    pub(crate) invoice_billing_period: ::std::option::Option<crate::types::InvoiceBillingPeriod>,
    pub(crate) before_issued_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) after_issued_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) max_results: ::std::option::Option<i32>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
}
impl ListAgreementInvoiceLineItemsInputBuilder {
    /// <p>The unique identifier of the agreement.</p>
    /// This field is required.
    pub fn agreement_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.agreement_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the agreement.</p>
    pub fn set_agreement_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.agreement_id = input;
        self
    }
    /// <p>The unique identifier of the agreement.</p>
    pub fn get_agreement_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.agreement_id
    }
    /// <p>Specifies a grouping strategy for line items. Currently supports <code>INVOICE_ID</code>.</p>
    /// This field is required.
    pub fn group_by(mut self, input: crate::types::LineItemGroupBy) -> Self {
        self.group_by = ::std::option::Option::Some(input);
        self
    }
    /// <p>Specifies a grouping strategy for line items. Currently supports <code>INVOICE_ID</code>.</p>
    pub fn set_group_by(mut self, input: ::std::option::Option<crate::types::LineItemGroupBy>) -> Self {
        self.group_by = input;
        self
    }
    /// <p>Specifies a grouping strategy for line items. Currently supports <code>INVOICE_ID</code>.</p>
    pub fn get_group_by(&self) -> &::std::option::Option<crate::types::LineItemGroupBy> {
        &self.group_by
    }
    /// <p>An optional filter to retrieve invoice information for a specific invoice.</p>
    pub fn invoice_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.invoice_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>An optional filter to retrieve invoice information for a specific invoice.</p>
    pub fn set_invoice_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.invoice_id = input;
        self
    }
    /// <p>An optional filter to retrieve invoice information for a specific invoice.</p>
    pub fn get_invoice_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.invoice_id
    }
    /// <p>An optional filter for the type of invoice. Valid values are <code>INVOICE</code> and <code>CREDIT_MEMO</code>.</p>
    pub fn invoice_type(mut self, input: crate::types::InvoiceType) -> Self {
        self.invoice_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>An optional filter for the type of invoice. Valid values are <code>INVOICE</code> and <code>CREDIT_MEMO</code>.</p>
    pub fn set_invoice_type(mut self, input: ::std::option::Option<crate::types::InvoiceType>) -> Self {
        self.invoice_type = input;
        self
    }
    /// <p>An optional filter for the type of invoice. Valid values are <code>INVOICE</code> and <code>CREDIT_MEMO</code>.</p>
    pub fn get_invoice_type(&self) -> &::std::option::Option<crate::types::InvoiceType> {
        &self.invoice_type
    }
    /// <p>An optional filter for the billing period associated with the invoice.</p>
    pub fn invoice_billing_period(mut self, input: crate::types::InvoiceBillingPeriod) -> Self {
        self.invoice_billing_period = ::std::option::Option::Some(input);
        self
    }
    /// <p>An optional filter for the billing period associated with the invoice.</p>
    pub fn set_invoice_billing_period(mut self, input: ::std::option::Option<crate::types::InvoiceBillingPeriod>) -> Self {
        self.invoice_billing_period = input;
        self
    }
    /// <p>An optional filter for the billing period associated with the invoice.</p>
    pub fn get_invoice_billing_period(&self) -> &::std::option::Option<crate::types::InvoiceBillingPeriod> {
        &self.invoice_billing_period
    }
    /// <p>An optional filter for invoices issued before the specified timestamp.</p>
    pub fn before_issued_time(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.before_issued_time = ::std::option::Option::Some(input);
        self
    }
    /// <p>An optional filter for invoices issued before the specified timestamp.</p>
    pub fn set_before_issued_time(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.before_issued_time = input;
        self
    }
    /// <p>An optional filter for invoices issued before the specified timestamp.</p>
    pub fn get_before_issued_time(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.before_issued_time
    }
    /// <p>An optional filter for invoices issued after the specified timestamp.</p>
    pub fn after_issued_time(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.after_issued_time = ::std::option::Option::Some(input);
        self
    }
    /// <p>An optional filter for invoices issued after the specified timestamp.</p>
    pub fn set_after_issued_time(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.after_issued_time = input;
        self
    }
    /// <p>An optional filter for invoices issued after the specified timestamp.</p>
    pub fn get_after_issued_time(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.after_issued_time
    }
    /// <p>The maximum number of results to return in the response.</p>
    pub fn max_results(mut self, input: i32) -> Self {
        self.max_results = ::std::option::Option::Some(input);
        self
    }
    /// <p>The maximum number of results to return in the response.</p>
    pub fn set_max_results(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_results = input;
        self
    }
    /// <p>The maximum number of results to return in the response.</p>
    pub fn get_max_results(&self) -> &::std::option::Option<i32> {
        &self.max_results
    }
    /// <p>A token to specify where to start pagination.</p>
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A token to specify where to start pagination.</p>
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }
    /// <p>A token to specify where to start pagination.</p>
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }
    /// Consumes the builder and constructs a [`ListAgreementInvoiceLineItemsInput`](crate::operation::list_agreement_invoice_line_items::ListAgreementInvoiceLineItemsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::list_agreement_invoice_line_items::ListAgreementInvoiceLineItemsInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::list_agreement_invoice_line_items::ListAgreementInvoiceLineItemsInput {
            agreement_id: self.agreement_id,
            group_by: self.group_by,
            invoice_id: self.invoice_id,
            invoice_type: self.invoice_type,
            invoice_billing_period: self.invoice_billing_period,
            before_issued_time: self.before_issued_time,
            after_issued_time: self.after_issued_time,
            max_results: self.max_results,
            next_token: self.next_token,
        })
    }
}
