// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Information about an entity type in the DataAutomationLibrary
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct EntityTypeInfo {
    /// Entity types supported in DataAutomationLibraries
    pub entity_type: crate::types::EntityType,
    /// JSON string representing relevant metadata for the entity type
    pub entity_metadata: ::std::option::Option<::std::string::String>,
}
impl EntityTypeInfo {
    /// Entity types supported in DataAutomationLibraries
    pub fn entity_type(&self) -> &crate::types::EntityType {
        &self.entity_type
    }
    /// JSON string representing relevant metadata for the entity type
    pub fn entity_metadata(&self) -> ::std::option::Option<&str> {
        self.entity_metadata.as_deref()
    }
}
impl EntityTypeInfo {
    /// Creates a new builder-style object to manufacture [`EntityTypeInfo`](crate::types::EntityTypeInfo).
    pub fn builder() -> crate::types::builders::EntityTypeInfoBuilder {
        crate::types::builders::EntityTypeInfoBuilder::default()
    }
}

/// A builder for [`EntityTypeInfo`](crate::types::EntityTypeInfo).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct EntityTypeInfoBuilder {
    pub(crate) entity_type: ::std::option::Option<crate::types::EntityType>,
    pub(crate) entity_metadata: ::std::option::Option<::std::string::String>,
}
impl EntityTypeInfoBuilder {
    /// Entity types supported in DataAutomationLibraries
    /// This field is required.
    pub fn entity_type(mut self, input: crate::types::EntityType) -> Self {
        self.entity_type = ::std::option::Option::Some(input);
        self
    }
    /// Entity types supported in DataAutomationLibraries
    pub fn set_entity_type(mut self, input: ::std::option::Option<crate::types::EntityType>) -> Self {
        self.entity_type = input;
        self
    }
    /// Entity types supported in DataAutomationLibraries
    pub fn get_entity_type(&self) -> &::std::option::Option<crate::types::EntityType> {
        &self.entity_type
    }
    /// JSON string representing relevant metadata for the entity type
    pub fn entity_metadata(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.entity_metadata = ::std::option::Option::Some(input.into());
        self
    }
    /// JSON string representing relevant metadata for the entity type
    pub fn set_entity_metadata(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.entity_metadata = input;
        self
    }
    /// JSON string representing relevant metadata for the entity type
    pub fn get_entity_metadata(&self) -> &::std::option::Option<::std::string::String> {
        &self.entity_metadata
    }
    /// Consumes the builder and constructs a [`EntityTypeInfo`](crate::types::EntityTypeInfo).
    /// This method will fail if any of the following fields are not set:
    /// - [`entity_type`](crate::types::builders::EntityTypeInfoBuilder::entity_type)
    pub fn build(self) -> ::std::result::Result<crate::types::EntityTypeInfo, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::EntityTypeInfo {
            entity_type: self.entity_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "entity_type",
                    "entity_type was not specified but it is required when building EntityTypeInfo",
                )
            })?,
            entity_metadata: self.entity_metadata,
        })
    }
}
