// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Defines an area to avoid during calculations using one of several supported geometry types. The service will prefer routes that avoid these areas when possible.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct IsolineAvoidanceAreaGeometry {
    /// <p>A rectangular area defined by its southwest and northeast corners: <code>\[min longitude, min latitude, max longitude, max latitude\]</code>.</p>
    pub bounding_box: ::std::option::Option<::std::vec::Vec<f64>>,
    /// <p>A buffer zone around a line, defined by a series of coordinates and a radius in meters.</p>
    pub corridor: ::std::option::Option<crate::types::Corridor>,
    /// <p>A polygon defined by a list of coordinate rings. The first ring defines the outer boundary; subsequent rings will be ignored.</p>
    pub polygon: ::std::option::Option<::std::vec::Vec<::std::vec::Vec<::std::vec::Vec<f64>>>>,
    /// <p>A buffer zone around a compressed polyline, defined by an encoded polyline string and a radius in meters. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub polyline_corridor: ::std::option::Option<crate::types::PolylineCorridor>,
    /// <p>A polygon defined by encoded polyline strings. The first string defines the outer boundary; subsequent strings will be ignored. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub polyline_polygon: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
}
impl IsolineAvoidanceAreaGeometry {
    /// <p>A rectangular area defined by its southwest and northeast corners: <code>\[min longitude, min latitude, max longitude, max latitude\]</code>.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.bounding_box.is_none()`.
    pub fn bounding_box(&self) -> &[f64] {
        self.bounding_box.as_deref().unwrap_or_default()
    }
    /// <p>A buffer zone around a line, defined by a series of coordinates and a radius in meters.</p>
    pub fn corridor(&self) -> ::std::option::Option<&crate::types::Corridor> {
        self.corridor.as_ref()
    }
    /// <p>A polygon defined by a list of coordinate rings. The first ring defines the outer boundary; subsequent rings will be ignored.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.polygon.is_none()`.
    pub fn polygon(&self) -> &[::std::vec::Vec<::std::vec::Vec<f64>>] {
        self.polygon.as_deref().unwrap_or_default()
    }
    /// <p>A buffer zone around a compressed polyline, defined by an encoded polyline string and a radius in meters. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn polyline_corridor(&self) -> ::std::option::Option<&crate::types::PolylineCorridor> {
        self.polyline_corridor.as_ref()
    }
    /// <p>A polygon defined by encoded polyline strings. The first string defines the outer boundary; subsequent strings will be ignored. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.polyline_polygon.is_none()`.
    pub fn polyline_polygon(&self) -> &[::std::string::String] {
        self.polyline_polygon.as_deref().unwrap_or_default()
    }
}
impl ::std::fmt::Debug for IsolineAvoidanceAreaGeometry {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("IsolineAvoidanceAreaGeometry");
        formatter.field("bounding_box", &"*** Sensitive Data Redacted ***");
        formatter.field("corridor", &"*** Sensitive Data Redacted ***");
        formatter.field("polygon", &"*** Sensitive Data Redacted ***");
        formatter.field("polyline_corridor", &"*** Sensitive Data Redacted ***");
        formatter.field("polyline_polygon", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl IsolineAvoidanceAreaGeometry {
    /// Creates a new builder-style object to manufacture [`IsolineAvoidanceAreaGeometry`](crate::types::IsolineAvoidanceAreaGeometry).
    pub fn builder() -> crate::types::builders::IsolineAvoidanceAreaGeometryBuilder {
        crate::types::builders::IsolineAvoidanceAreaGeometryBuilder::default()
    }
}

/// A builder for [`IsolineAvoidanceAreaGeometry`](crate::types::IsolineAvoidanceAreaGeometry).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct IsolineAvoidanceAreaGeometryBuilder {
    pub(crate) bounding_box: ::std::option::Option<::std::vec::Vec<f64>>,
    pub(crate) corridor: ::std::option::Option<crate::types::Corridor>,
    pub(crate) polygon: ::std::option::Option<::std::vec::Vec<::std::vec::Vec<::std::vec::Vec<f64>>>>,
    pub(crate) polyline_corridor: ::std::option::Option<crate::types::PolylineCorridor>,
    pub(crate) polyline_polygon: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
}
impl IsolineAvoidanceAreaGeometryBuilder {
    /// Appends an item to `bounding_box`.
    ///
    /// To override the contents of this collection use [`set_bounding_box`](Self::set_bounding_box).
    ///
    /// <p>A rectangular area defined by its southwest and northeast corners: <code>\[min longitude, min latitude, max longitude, max latitude\]</code>.</p>
    pub fn bounding_box(mut self, input: f64) -> Self {
        let mut v = self.bounding_box.unwrap_or_default();
        v.push(input);
        self.bounding_box = ::std::option::Option::Some(v);
        self
    }
    /// <p>A rectangular area defined by its southwest and northeast corners: <code>\[min longitude, min latitude, max longitude, max latitude\]</code>.</p>
    pub fn set_bounding_box(mut self, input: ::std::option::Option<::std::vec::Vec<f64>>) -> Self {
        self.bounding_box = input;
        self
    }
    /// <p>A rectangular area defined by its southwest and northeast corners: <code>\[min longitude, min latitude, max longitude, max latitude\]</code>.</p>
    pub fn get_bounding_box(&self) -> &::std::option::Option<::std::vec::Vec<f64>> {
        &self.bounding_box
    }
    /// <p>A buffer zone around a line, defined by a series of coordinates and a radius in meters.</p>
    pub fn corridor(mut self, input: crate::types::Corridor) -> Self {
        self.corridor = ::std::option::Option::Some(input);
        self
    }
    /// <p>A buffer zone around a line, defined by a series of coordinates and a radius in meters.</p>
    pub fn set_corridor(mut self, input: ::std::option::Option<crate::types::Corridor>) -> Self {
        self.corridor = input;
        self
    }
    /// <p>A buffer zone around a line, defined by a series of coordinates and a radius in meters.</p>
    pub fn get_corridor(&self) -> &::std::option::Option<crate::types::Corridor> {
        &self.corridor
    }
    /// Appends an item to `polygon`.
    ///
    /// To override the contents of this collection use [`set_polygon`](Self::set_polygon).
    ///
    /// <p>A polygon defined by a list of coordinate rings. The first ring defines the outer boundary; subsequent rings will be ignored.</p>
    pub fn polygon(mut self, input: ::std::vec::Vec<::std::vec::Vec<f64>>) -> Self {
        let mut v = self.polygon.unwrap_or_default();
        v.push(input);
        self.polygon = ::std::option::Option::Some(v);
        self
    }
    /// <p>A polygon defined by a list of coordinate rings. The first ring defines the outer boundary; subsequent rings will be ignored.</p>
    pub fn set_polygon(mut self, input: ::std::option::Option<::std::vec::Vec<::std::vec::Vec<::std::vec::Vec<f64>>>>) -> Self {
        self.polygon = input;
        self
    }
    /// <p>A polygon defined by a list of coordinate rings. The first ring defines the outer boundary; subsequent rings will be ignored.</p>
    pub fn get_polygon(&self) -> &::std::option::Option<::std::vec::Vec<::std::vec::Vec<::std::vec::Vec<f64>>>> {
        &self.polygon
    }
    /// <p>A buffer zone around a compressed polyline, defined by an encoded polyline string and a radius in meters. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn polyline_corridor(mut self, input: crate::types::PolylineCorridor) -> Self {
        self.polyline_corridor = ::std::option::Option::Some(input);
        self
    }
    /// <p>A buffer zone around a compressed polyline, defined by an encoded polyline string and a radius in meters. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn set_polyline_corridor(mut self, input: ::std::option::Option<crate::types::PolylineCorridor>) -> Self {
        self.polyline_corridor = input;
        self
    }
    /// <p>A buffer zone around a compressed polyline, defined by an encoded polyline string and a radius in meters. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn get_polyline_corridor(&self) -> &::std::option::Option<crate::types::PolylineCorridor> {
        &self.polyline_corridor
    }
    /// Appends an item to `polyline_polygon`.
    ///
    /// To override the contents of this collection use [`set_polyline_polygon`](Self::set_polyline_polygon).
    ///
    /// <p>A polygon defined by encoded polyline strings. The first string defines the outer boundary; subsequent strings will be ignored. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn polyline_polygon(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.polyline_polygon.unwrap_or_default();
        v.push(input.into());
        self.polyline_polygon = ::std::option::Option::Some(v);
        self
    }
    /// <p>A polygon defined by encoded polyline strings. The first string defines the outer boundary; subsequent strings will be ignored. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn set_polyline_polygon(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.polyline_polygon = input;
        self
    }
    /// <p>A polygon defined by encoded polyline strings. The first string defines the outer boundary; subsequent strings will be ignored. For more information on polyline encoding, see <a href="https://github.com/aws-geospatial/polyline">https://github.com/aws-geospatial/polyline</a>.</p>
    pub fn get_polyline_polygon(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.polyline_polygon
    }
    /// Consumes the builder and constructs a [`IsolineAvoidanceAreaGeometry`](crate::types::IsolineAvoidanceAreaGeometry).
    pub fn build(self) -> crate::types::IsolineAvoidanceAreaGeometry {
        crate::types::IsolineAvoidanceAreaGeometry {
            bounding_box: self.bounding_box,
            corridor: self.corridor,
            polygon: self.polygon,
            polyline_corridor: self.polyline_corridor,
            polyline_polygon: self.polyline_polygon,
        }
    }
}
impl ::std::fmt::Debug for IsolineAvoidanceAreaGeometryBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("IsolineAvoidanceAreaGeometryBuilder");
        formatter.field("bounding_box", &"*** Sensitive Data Redacted ***");
        formatter.field("corridor", &"*** Sensitive Data Redacted ***");
        formatter.field("polygon", &"*** Sensitive Data Redacted ***");
        formatter.field("polyline_corridor", &"*** Sensitive Data Redacted ***");
        formatter.field("polyline_polygon", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
