// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Types of regulated zones that may affect routing.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct IsolineAvoidanceZoneCategory {
    /// <p>The type of regulated zone: <code>CongestionPricing</code> for toll zones based on traffic levels, <code>Environmental</code> for low-emission zones, or <code>Vignette</code> for areas requiring special permits or stickers.</p>
    pub category: ::std::option::Option<crate::types::IsolineZoneCategory>,
}
impl IsolineAvoidanceZoneCategory {
    /// <p>The type of regulated zone: <code>CongestionPricing</code> for toll zones based on traffic levels, <code>Environmental</code> for low-emission zones, or <code>Vignette</code> for areas requiring special permits or stickers.</p>
    pub fn category(&self) -> ::std::option::Option<&crate::types::IsolineZoneCategory> {
        self.category.as_ref()
    }
}
impl IsolineAvoidanceZoneCategory {
    /// Creates a new builder-style object to manufacture [`IsolineAvoidanceZoneCategory`](crate::types::IsolineAvoidanceZoneCategory).
    pub fn builder() -> crate::types::builders::IsolineAvoidanceZoneCategoryBuilder {
        crate::types::builders::IsolineAvoidanceZoneCategoryBuilder::default()
    }
}

/// A builder for [`IsolineAvoidanceZoneCategory`](crate::types::IsolineAvoidanceZoneCategory).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct IsolineAvoidanceZoneCategoryBuilder {
    pub(crate) category: ::std::option::Option<crate::types::IsolineZoneCategory>,
}
impl IsolineAvoidanceZoneCategoryBuilder {
    /// <p>The type of regulated zone: <code>CongestionPricing</code> for toll zones based on traffic levels, <code>Environmental</code> for low-emission zones, or <code>Vignette</code> for areas requiring special permits or stickers.</p>
    pub fn category(mut self, input: crate::types::IsolineZoneCategory) -> Self {
        self.category = ::std::option::Option::Some(input);
        self
    }
    /// <p>The type of regulated zone: <code>CongestionPricing</code> for toll zones based on traffic levels, <code>Environmental</code> for low-emission zones, or <code>Vignette</code> for areas requiring special permits or stickers.</p>
    pub fn set_category(mut self, input: ::std::option::Option<crate::types::IsolineZoneCategory>) -> Self {
        self.category = input;
        self
    }
    /// <p>The type of regulated zone: <code>CongestionPricing</code> for toll zones based on traffic levels, <code>Environmental</code> for low-emission zones, or <code>Vignette</code> for areas requiring special permits or stickers.</p>
    pub fn get_category(&self) -> &::std::option::Option<crate::types::IsolineZoneCategory> {
        &self.category
    }
    /// Consumes the builder and constructs a [`IsolineAvoidanceZoneCategory`](crate::types::IsolineAvoidanceZoneCategory).
    pub fn build(self) -> crate::types::IsolineAvoidanceZoneCategory {
        crate::types::IsolineAvoidanceZoneCategory { category: self.category }
    }
}
