// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Traffic options for the route.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct RouteTrafficOptions {
    /// <p>Duration for which flow traffic is considered valid. For this period, the flow traffic is used over historical traffic data. Flow traffic refers to congestion, which changes very quickly. Duration in seconds for which flow traffic event would be considered valid. While flow traffic event is valid it will be used over the historical traffic data.</p>
    pub flow_event_threshold_override: i64,
    /// <p>Specifies how traffic data should be used when calculating routes.</p>
    /// <p>Default Value: <code>UseTrafficData</code></p><note>
    /// <p>Traffic data usage depends on the time parameters in your route request:</p>
    /// <ul>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>UseTrafficData</code>:</p>
    /// <ul>
    /// <li>
    /// <p>If <code>DepartNow</code> is set to <code>true</code>, or if you specify <code>DepartureTime</code> or <code>ArrivalTime</code>, then all traffic data is considered (including live traffic and closures).</p></li>
    /// <li>
    /// <p>If <code>DepartNow</code>, <code>DepartureTime</code>, and <code>ArrivalTime</code> are all unspecified, then only long-term closures are considered, regardless of this setting.</p></li>
    /// </ul></li>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>IgnoreTrafficData</code>, then all traffic data is ignored regardless of the time parameters in your route request.</p></li>
    /// </ul>
    /// </note>
    pub usage: ::std::option::Option<crate::types::TrafficUsage>,
}
impl RouteTrafficOptions {
    /// <p>Duration for which flow traffic is considered valid. For this period, the flow traffic is used over historical traffic data. Flow traffic refers to congestion, which changes very quickly. Duration in seconds for which flow traffic event would be considered valid. While flow traffic event is valid it will be used over the historical traffic data.</p>
    pub fn flow_event_threshold_override(&self) -> i64 {
        self.flow_event_threshold_override
    }
    /// <p>Specifies how traffic data should be used when calculating routes.</p>
    /// <p>Default Value: <code>UseTrafficData</code></p><note>
    /// <p>Traffic data usage depends on the time parameters in your route request:</p>
    /// <ul>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>UseTrafficData</code>:</p>
    /// <ul>
    /// <li>
    /// <p>If <code>DepartNow</code> is set to <code>true</code>, or if you specify <code>DepartureTime</code> or <code>ArrivalTime</code>, then all traffic data is considered (including live traffic and closures).</p></li>
    /// <li>
    /// <p>If <code>DepartNow</code>, <code>DepartureTime</code>, and <code>ArrivalTime</code> are all unspecified, then only long-term closures are considered, regardless of this setting.</p></li>
    /// </ul></li>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>IgnoreTrafficData</code>, then all traffic data is ignored regardless of the time parameters in your route request.</p></li>
    /// </ul>
    /// </note>
    pub fn usage(&self) -> ::std::option::Option<&crate::types::TrafficUsage> {
        self.usage.as_ref()
    }
}
impl ::std::fmt::Debug for RouteTrafficOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("RouteTrafficOptions");
        formatter.field("flow_event_threshold_override", &"*** Sensitive Data Redacted ***");
        formatter.field("usage", &self.usage);
        formatter.finish()
    }
}
impl RouteTrafficOptions {
    /// Creates a new builder-style object to manufacture [`RouteTrafficOptions`](crate::types::RouteTrafficOptions).
    pub fn builder() -> crate::types::builders::RouteTrafficOptionsBuilder {
        crate::types::builders::RouteTrafficOptionsBuilder::default()
    }
}

/// A builder for [`RouteTrafficOptions`](crate::types::RouteTrafficOptions).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct RouteTrafficOptionsBuilder {
    pub(crate) flow_event_threshold_override: ::std::option::Option<i64>,
    pub(crate) usage: ::std::option::Option<crate::types::TrafficUsage>,
}
impl RouteTrafficOptionsBuilder {
    /// <p>Duration for which flow traffic is considered valid. For this period, the flow traffic is used over historical traffic data. Flow traffic refers to congestion, which changes very quickly. Duration in seconds for which flow traffic event would be considered valid. While flow traffic event is valid it will be used over the historical traffic data.</p>
    pub fn flow_event_threshold_override(mut self, input: i64) -> Self {
        self.flow_event_threshold_override = ::std::option::Option::Some(input);
        self
    }
    /// <p>Duration for which flow traffic is considered valid. For this period, the flow traffic is used over historical traffic data. Flow traffic refers to congestion, which changes very quickly. Duration in seconds for which flow traffic event would be considered valid. While flow traffic event is valid it will be used over the historical traffic data.</p>
    pub fn set_flow_event_threshold_override(mut self, input: ::std::option::Option<i64>) -> Self {
        self.flow_event_threshold_override = input;
        self
    }
    /// <p>Duration for which flow traffic is considered valid. For this period, the flow traffic is used over historical traffic data. Flow traffic refers to congestion, which changes very quickly. Duration in seconds for which flow traffic event would be considered valid. While flow traffic event is valid it will be used over the historical traffic data.</p>
    pub fn get_flow_event_threshold_override(&self) -> &::std::option::Option<i64> {
        &self.flow_event_threshold_override
    }
    /// <p>Specifies how traffic data should be used when calculating routes.</p>
    /// <p>Default Value: <code>UseTrafficData</code></p><note>
    /// <p>Traffic data usage depends on the time parameters in your route request:</p>
    /// <ul>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>UseTrafficData</code>:</p>
    /// <ul>
    /// <li>
    /// <p>If <code>DepartNow</code> is set to <code>true</code>, or if you specify <code>DepartureTime</code> or <code>ArrivalTime</code>, then all traffic data is considered (including live traffic and closures).</p></li>
    /// <li>
    /// <p>If <code>DepartNow</code>, <code>DepartureTime</code>, and <code>ArrivalTime</code> are all unspecified, then only long-term closures are considered, regardless of this setting.</p></li>
    /// </ul></li>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>IgnoreTrafficData</code>, then all traffic data is ignored regardless of the time parameters in your route request.</p></li>
    /// </ul>
    /// </note>
    pub fn usage(mut self, input: crate::types::TrafficUsage) -> Self {
        self.usage = ::std::option::Option::Some(input);
        self
    }
    /// <p>Specifies how traffic data should be used when calculating routes.</p>
    /// <p>Default Value: <code>UseTrafficData</code></p><note>
    /// <p>Traffic data usage depends on the time parameters in your route request:</p>
    /// <ul>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>UseTrafficData</code>:</p>
    /// <ul>
    /// <li>
    /// <p>If <code>DepartNow</code> is set to <code>true</code>, or if you specify <code>DepartureTime</code> or <code>ArrivalTime</code>, then all traffic data is considered (including live traffic and closures).</p></li>
    /// <li>
    /// <p>If <code>DepartNow</code>, <code>DepartureTime</code>, and <code>ArrivalTime</code> are all unspecified, then only long-term closures are considered, regardless of this setting.</p></li>
    /// </ul></li>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>IgnoreTrafficData</code>, then all traffic data is ignored regardless of the time parameters in your route request.</p></li>
    /// </ul>
    /// </note>
    pub fn set_usage(mut self, input: ::std::option::Option<crate::types::TrafficUsage>) -> Self {
        self.usage = input;
        self
    }
    /// <p>Specifies how traffic data should be used when calculating routes.</p>
    /// <p>Default Value: <code>UseTrafficData</code></p><note>
    /// <p>Traffic data usage depends on the time parameters in your route request:</p>
    /// <ul>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>UseTrafficData</code>:</p>
    /// <ul>
    /// <li>
    /// <p>If <code>DepartNow</code> is set to <code>true</code>, or if you specify <code>DepartureTime</code> or <code>ArrivalTime</code>, then all traffic data is considered (including live traffic and closures).</p></li>
    /// <li>
    /// <p>If <code>DepartNow</code>, <code>DepartureTime</code>, and <code>ArrivalTime</code> are all unspecified, then only long-term closures are considered, regardless of this setting.</p></li>
    /// </ul></li>
    /// <li>
    /// <p>When <code>Usage</code> is set to <code>IgnoreTrafficData</code>, then all traffic data is ignored regardless of the time parameters in your route request.</p></li>
    /// </ul>
    /// </note>
    pub fn get_usage(&self) -> &::std::option::Option<crate::types::TrafficUsage> {
        &self.usage
    }
    /// Consumes the builder and constructs a [`RouteTrafficOptions`](crate::types::RouteTrafficOptions).
    pub fn build(self) -> crate::types::RouteTrafficOptions {
        crate::types::RouteTrafficOptions {
            flow_event_threshold_override: self.flow_event_threshold_override.unwrap_or_default(),
            usage: self.usage,
        }
    }
}
impl ::std::fmt::Debug for RouteTrafficOptionsBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("RouteTrafficOptionsBuilder");
        formatter.field("flow_event_threshold_override", &"*** Sensitive Data Redacted ***");
        formatter.field("usage", &self.usage);
        formatter.finish()
    }
}
