// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_batch_create_billing_adjustment_request_entry(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::BatchCreateBillingAdjustmentRequestEntry,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("agreementId").string(input.agreement_id.as_str());
    }
    {
        object.key("originalInvoiceId").string(input.original_invoice_id.as_str());
    }
    {
        object.key("adjustmentAmount").string(input.adjustment_amount.as_str());
    }
    {
        object.key("currencyCode").string(input.currency_code.as_str());
    }
    {
        object.key("adjustmentReasonCode").string(input.adjustment_reason_code.as_str());
    }
    if let Some(var_1) = &input.description {
        object.key("description").string(var_1.as_str());
    }
    {
        object.key("clientToken").string(input.client_token.as_str());
    }
    Ok(())
}
