// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>A badge indicating a special attribute of a purchase option, such as private pricing or future dated.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PurchaseOptionBadge {
    /// <p>The human-readable name of the badge.</p>
    pub display_name: ::std::string::String,
    /// <p>The machine-readable type of the badge.</p>
    pub badge_type: crate::types::PurchaseOptionBadgeType,
}
impl PurchaseOptionBadge {
    /// <p>The human-readable name of the badge.</p>
    pub fn display_name(&self) -> &str {
        use std::ops::Deref;
        self.display_name.deref()
    }
    /// <p>The machine-readable type of the badge.</p>
    pub fn badge_type(&self) -> &crate::types::PurchaseOptionBadgeType {
        &self.badge_type
    }
}
impl PurchaseOptionBadge {
    /// Creates a new builder-style object to manufacture [`PurchaseOptionBadge`](crate::types::PurchaseOptionBadge).
    pub fn builder() -> crate::types::builders::PurchaseOptionBadgeBuilder {
        crate::types::builders::PurchaseOptionBadgeBuilder::default()
    }
}

/// A builder for [`PurchaseOptionBadge`](crate::types::PurchaseOptionBadge).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct PurchaseOptionBadgeBuilder {
    pub(crate) display_name: ::std::option::Option<::std::string::String>,
    pub(crate) badge_type: ::std::option::Option<crate::types::PurchaseOptionBadgeType>,
}
impl PurchaseOptionBadgeBuilder {
    /// <p>The human-readable name of the badge.</p>
    /// This field is required.
    pub fn display_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.display_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The human-readable name of the badge.</p>
    pub fn set_display_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.display_name = input;
        self
    }
    /// <p>The human-readable name of the badge.</p>
    pub fn get_display_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.display_name
    }
    /// <p>The machine-readable type of the badge.</p>
    /// This field is required.
    pub fn badge_type(mut self, input: crate::types::PurchaseOptionBadgeType) -> Self {
        self.badge_type = ::std::option::Option::Some(input);
        self
    }
    /// <p>The machine-readable type of the badge.</p>
    pub fn set_badge_type(mut self, input: ::std::option::Option<crate::types::PurchaseOptionBadgeType>) -> Self {
        self.badge_type = input;
        self
    }
    /// <p>The machine-readable type of the badge.</p>
    pub fn get_badge_type(&self) -> &::std::option::Option<crate::types::PurchaseOptionBadgeType> {
        &self.badge_type
    }
    /// Consumes the builder and constructs a [`PurchaseOptionBadge`](crate::types::PurchaseOptionBadge).
    /// This method will fail if any of the following fields are not set:
    /// - [`display_name`](crate::types::builders::PurchaseOptionBadgeBuilder::display_name)
    /// - [`badge_type`](crate::types::builders::PurchaseOptionBadgeBuilder::badge_type)
    pub fn build(self) -> ::std::result::Result<crate::types::PurchaseOptionBadge, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::PurchaseOptionBadge {
            display_name: self.display_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "display_name",
                    "display_name was not specified but it is required when building PurchaseOptionBadge",
                )
            })?,
            badge_type: self.badge_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "badge_type",
                    "badge_type was not specified but it is required when building PurchaseOptionBadge",
                )
            })?,
        })
    }
}
