// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Recommended instance types for training and inference with a SageMaker algorithm.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SageMakerAlgorithmRecommendation {
    /// <p>The recommended instance type for batch inference.</p>
    pub recommended_batch_transform_instance_type: ::std::string::String,
    /// <p>The recommended instance type for real-time inference.</p>
    pub recommended_realtime_inference_instance_type: ::std::option::Option<::std::string::String>,
    /// <p>The recommended instance type for training.</p>
    pub recommended_training_instance_type: ::std::string::String,
}
impl SageMakerAlgorithmRecommendation {
    /// <p>The recommended instance type for batch inference.</p>
    pub fn recommended_batch_transform_instance_type(&self) -> &str {
        use std::ops::Deref;
        self.recommended_batch_transform_instance_type.deref()
    }
    /// <p>The recommended instance type for real-time inference.</p>
    pub fn recommended_realtime_inference_instance_type(&self) -> ::std::option::Option<&str> {
        self.recommended_realtime_inference_instance_type.as_deref()
    }
    /// <p>The recommended instance type for training.</p>
    pub fn recommended_training_instance_type(&self) -> &str {
        use std::ops::Deref;
        self.recommended_training_instance_type.deref()
    }
}
impl SageMakerAlgorithmRecommendation {
    /// Creates a new builder-style object to manufacture [`SageMakerAlgorithmRecommendation`](crate::types::SageMakerAlgorithmRecommendation).
    pub fn builder() -> crate::types::builders::SageMakerAlgorithmRecommendationBuilder {
        crate::types::builders::SageMakerAlgorithmRecommendationBuilder::default()
    }
}

/// A builder for [`SageMakerAlgorithmRecommendation`](crate::types::SageMakerAlgorithmRecommendation).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SageMakerAlgorithmRecommendationBuilder {
    pub(crate) recommended_batch_transform_instance_type: ::std::option::Option<::std::string::String>,
    pub(crate) recommended_realtime_inference_instance_type: ::std::option::Option<::std::string::String>,
    pub(crate) recommended_training_instance_type: ::std::option::Option<::std::string::String>,
}
impl SageMakerAlgorithmRecommendationBuilder {
    /// <p>The recommended instance type for batch inference.</p>
    /// This field is required.
    pub fn recommended_batch_transform_instance_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.recommended_batch_transform_instance_type = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The recommended instance type for batch inference.</p>
    pub fn set_recommended_batch_transform_instance_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.recommended_batch_transform_instance_type = input;
        self
    }
    /// <p>The recommended instance type for batch inference.</p>
    pub fn get_recommended_batch_transform_instance_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.recommended_batch_transform_instance_type
    }
    /// <p>The recommended instance type for real-time inference.</p>
    pub fn recommended_realtime_inference_instance_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.recommended_realtime_inference_instance_type = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The recommended instance type for real-time inference.</p>
    pub fn set_recommended_realtime_inference_instance_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.recommended_realtime_inference_instance_type = input;
        self
    }
    /// <p>The recommended instance type for real-time inference.</p>
    pub fn get_recommended_realtime_inference_instance_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.recommended_realtime_inference_instance_type
    }
    /// <p>The recommended instance type for training.</p>
    /// This field is required.
    pub fn recommended_training_instance_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.recommended_training_instance_type = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The recommended instance type for training.</p>
    pub fn set_recommended_training_instance_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.recommended_training_instance_type = input;
        self
    }
    /// <p>The recommended instance type for training.</p>
    pub fn get_recommended_training_instance_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.recommended_training_instance_type
    }
    /// Consumes the builder and constructs a [`SageMakerAlgorithmRecommendation`](crate::types::SageMakerAlgorithmRecommendation).
    /// This method will fail if any of the following fields are not set:
    /// - [`recommended_batch_transform_instance_type`](crate::types::builders::SageMakerAlgorithmRecommendationBuilder::recommended_batch_transform_instance_type)
    /// - [`recommended_training_instance_type`](crate::types::builders::SageMakerAlgorithmRecommendationBuilder::recommended_training_instance_type)
    pub fn build(self) -> ::std::result::Result<crate::types::SageMakerAlgorithmRecommendation, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::SageMakerAlgorithmRecommendation {
            recommended_batch_transform_instance_type: self.recommended_batch_transform_instance_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "recommended_batch_transform_instance_type",
                    "recommended_batch_transform_instance_type was not specified but it is required when building SageMakerAlgorithmRecommendation",
                )
            })?,
            recommended_realtime_inference_instance_type: self.recommended_realtime_inference_instance_type,
            recommended_training_instance_type: self.recommended_training_instance_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "recommended_training_instance_type",
                    "recommended_training_instance_type was not specified but it is required when building SageMakerAlgorithmRecommendation",
                )
            })?,
        })
    }
}
