// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Information about a seller, including the profile identifier and display name.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SellerInformation {
    /// <p>The unique identifier of the seller profile.</p>
    pub seller_profile_id: ::std::string::String,
    /// <p>The human-readable name of the seller.</p>
    pub display_name: ::std::string::String,
}
impl SellerInformation {
    /// <p>The unique identifier of the seller profile.</p>
    pub fn seller_profile_id(&self) -> &str {
        use std::ops::Deref;
        self.seller_profile_id.deref()
    }
    /// <p>The human-readable name of the seller.</p>
    pub fn display_name(&self) -> &str {
        use std::ops::Deref;
        self.display_name.deref()
    }
}
impl SellerInformation {
    /// Creates a new builder-style object to manufacture [`SellerInformation`](crate::types::SellerInformation).
    pub fn builder() -> crate::types::builders::SellerInformationBuilder {
        crate::types::builders::SellerInformationBuilder::default()
    }
}

/// A builder for [`SellerInformation`](crate::types::SellerInformation).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SellerInformationBuilder {
    pub(crate) seller_profile_id: ::std::option::Option<::std::string::String>,
    pub(crate) display_name: ::std::option::Option<::std::string::String>,
}
impl SellerInformationBuilder {
    /// <p>The unique identifier of the seller profile.</p>
    /// This field is required.
    pub fn seller_profile_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.seller_profile_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the seller profile.</p>
    pub fn set_seller_profile_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.seller_profile_id = input;
        self
    }
    /// <p>The unique identifier of the seller profile.</p>
    pub fn get_seller_profile_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.seller_profile_id
    }
    /// <p>The human-readable name of the seller.</p>
    /// This field is required.
    pub fn display_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.display_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The human-readable name of the seller.</p>
    pub fn set_display_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.display_name = input;
        self
    }
    /// <p>The human-readable name of the seller.</p>
    pub fn get_display_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.display_name
    }
    /// Consumes the builder and constructs a [`SellerInformation`](crate::types::SellerInformation).
    /// This method will fail if any of the following fields are not set:
    /// - [`seller_profile_id`](crate::types::builders::SellerInformationBuilder::seller_profile_id)
    /// - [`display_name`](crate::types::builders::SellerInformationBuilder::display_name)
    pub fn build(self) -> ::std::result::Result<crate::types::SellerInformation, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::SellerInformation {
            seller_profile_id: self.seller_profile_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "seller_profile_id",
                    "seller_profile_id was not specified but it is required when building SellerInformation",
                )
            })?,
            display_name: self.display_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "display_name",
                    "display_name was not specified but it is required when building SellerInformation",
                )
            })?,
        })
    }
}
